# Meteo prognoza — CatBoost 

Ova bilježnica koristi isti memorijski štedljiv pipeline kao prethodna verzija, ali omogućuje treniranje  modela `CatBoost`

## 1. Importi i konfiguracija

In [7]:
%pip install catboost
%pip install numpy
%pip install optuna
%pip install pandas

Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib (from catboost)
  Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from catboost) (2.5.2)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from catboost) (3.0.5)
Collecting scipy (from catboost)
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting plotly (from catboost)
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: six in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Collecting contourpy>=1.0.1 (from matplotlib->catboost)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->catboost)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib->catboost)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->catboost)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from matplotlib->catboost) (26.2)
Collecting pillow>=9 (from matplotlib->catboost)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib->catboost)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   -- ------------------------------------- 6.0/101.7 MB 31.8 MB/s eta 0:00:04
   ------- -------------------------------- 18.9/101.7 MB 47.9 MB/s eta 0:00:02
   ------------ --------------------------- 31.5/101.7 MB 52.2 MB/s eta 0:00:02
   ----------------- ---------------------- 44.0/101.7 MB 54.5 MB/s eta 0:00:02
   ---------------------- ----------------- 56.6/101.7 MB 55.7 MB/s eta 0:00:01
   -------------------------- ------------- 67.6/101.7 MB 56.5 MB/s eta 0:00:01
   ------------------------------- -------- 80.2/101.7 MB 56.1 MB/s eta 0:00:01
   ----------------------------------- ---- 89.1/101.7 MB 54.3 MB/s eta 0:00:01
   -------------------------------------- - 97.5/101.7 MB 52.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 52.3 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 46.4 MB/s  0:00:02
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --------------------------------- ------ 7.9/9.5 MB 38.5 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 34.4 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 33.9 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 34.5 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -------------------------------- ------- 8.1/9.9 MB 41.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 36.2 MB/s  0:00:00
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   -------- ------------------------------- 8.4/37.3 MB 40.1 MB/s eta 0:00:01
   ------------------- -------------------- 17.8/37.3 MB 42.6 MB/s eta 0:00:01
   ----------------------------- ---------- 27.3/37.3 MB 43.5 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.3 MB 43.9 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 39.3 MB/s  0:00:00
Installing collected packages: scipy, pyparsing, pillow, narwhals, kiwisolver, graphviz, fonttools, cycler, contourpy, plotly, matplotlib, catboost

   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   ----------------------------------------  0/12 [scipy]
   --- ------------------------------------  1/12 [pyparsing]
   --- ------------------------------------  1/12 [pyparsing]
   --- ------------------------------------  1/12 [pyparsing]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------------- -----------------------  5/12 [graphviz]
   ---------------- -----------------------  5/12 [graphviz]
   ---------------- -----------------------  5/12 [graphviz]
   ---------------- -----------------------  5/12 [graphviz]
   ---------------- -----------------------  5/12 [graphviz]
   ---------------- -----------------------  5/12 [graphviz]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script plotly_get_chrome.exe is installed in 'c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Using cached colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from optuna) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from optuna) (26.2)
INFO: pip is looking at multiple versions of optuna to determine which version is compatible with other requirements. This could take a while.
Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.4.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
INFO: pip is still looking at multiple versions of optuna to determine which version is compatible with other requirements. This could take a while.
  Downloading optuna-4.2.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-4.1.0-py3-none-any.whl.metadata (16 kB)
  Downloading optuna-4.0.0-py3-none-any.whl.metadata (16 kB)
  Downloading optuna-3.6.2-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.6.1-py3-none-any.whl.metadata (17 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading optuna-3.6.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.5.1-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.5.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.4.1-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.4.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.3.0-py3-none-any.whl.metadata (17 kB)
Collecting cmaes>=0.10.0 (from optuna)
  Downloading cmaes-0.13.0-py3-none-any.whl.metadata (29 kB)
Collecting optuna
  Downloading optuna-3.2.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-3.1.1-py3-none-any.whl.metadata (14 kB)
  Downloading optuna-3.1.0-py3-none-any.whl.metadata (14 kB)
  Downloading optuna-3.0.6-py3-none-any.whl.metadata (15 kB)
Collecting cliff (from optuna)
  Downloading cliff-4.15.0-py3-none-any.whl.metadata (2.1 kB)
Collecting importlib-metadata<5.0.0 (from optuna)
  Downloading importlib_metadata-4.13.0-py3-none-any.whl.metadata (4.9 kB)
Collecting optuna
  Downloading optuna-3.0.5-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-3.0.4-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-3.0.3-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-3.0.2-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-3.0.1-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-3.0.0-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-2.10.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: scipy!=1.4.0 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from optuna) (1.18.0)
  Downloading optuna-2.10.0-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-2.9.1-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-2.9.0-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-2.8.0-py3-none-any.whl.metadata (15 kB)
  Downloading optuna-2.7.0-py3-none-any.whl.metadata (17 kB)
  Downloading optuna-2.6.0-py3-none-any.whl.metadata (17 kB)
Collecting numpy<1.20.0 (from optuna)
  Downloading numpy-1.19.5.zip (7.3 MB)
     ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
     -------------------------------- ------- 6.0/7.3 MB 37.9 MB/s eta 0:00:01
     ---------------------------------------- 7.3/7.3 MB 34.4 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/ac/24/7c731839566d30dc70556d9824ef17692d896c15e3df627bce8c16f753e1/optuna-4.8.0-py3-none-any.whl.metadata

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\cli\base_command.py", line 109, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\cli\base_command.py", line 102, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\cli\req_command.py", line 101, in wrapper
    return func(self, options, args)
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\commands\install.py", line 479, in run
    requirement_set = resolver.resolve(
        reqs, check_supported_wheels=not options.target_dir
    )
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 99, in resolve
    result = self._result = resolver.resolve(
                            ~~~~~~~~~~~~~~~~^
        collected.requirements, max_rounds=limit_how_complex_resolution_can_be
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 601, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 513, in resolve
    failure_criterion = self._attempt_to_pin_criterion(name)
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 220, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 211, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 150, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 194, in __bool__
    return bool(self._sequence)
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 165, in __bool__
    self._bool = any(self)
                 ~~~^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 149, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 39, in _iter_built
    candidate = func()
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: BaseCandidate | None = self._make_base_candidate_from_link(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        link, template, name, version
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ~~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<3 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 326, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        link=link,
        ^^^^^^^^^^
    ...<4 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 168, in __init__
    self.dist = self._prepare()
                ~~~~~~~~~~~~~^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 246, in _prepare
    dist = self._prepare_distribution()
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 337, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\operations\prepare.py", line 542, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\operations\prepare.py", line 661, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
        req,
    ...<3 lines>...
        self.check_build_deps,
    )
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\operations\prepare.py", line 77, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        build_env_installer, build_isolation, check_build_deps
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\distributions\sdist.py", line 55, in prepare_distribution_metadata
    self._install_build_reqs(build_env_installer)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\distributions\sdist.py", line 132, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\distributions\sdist.py", line 107, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_internal\utils\misc.py", line 700, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
    return self._call_hook(
           ~~~~~~~~~~~~~~~^
        "get_requires_for_build_wheel", {"config_settings": config_settings}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
    ...<4 lines>...
    )
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'

Requirement already satisfied: pandas in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.0)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.24.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------- ----------------- 4.7/8.3 MB 31.2 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 35.2 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.9.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
%pip install --upgrade optuna

Collecting optuna
  Using cached optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Using cached alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Using cached colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from optuna) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from optuna) (26.2)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.52-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting tqdm (from optuna)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Collecting PyYAML (from optuna)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.5.5-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: colorama in C:\Users\Vanesa\AppData\Roaming\Python\Python314\site-packages (from colorlog->optuna) (0.4.6)
Collecting MarkupSafe>=2.0 (from Mako->alembic>=1.5.0->optuna)
  Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
Downloading sqlalchemy-2.0.52-cp314-cp314-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 28.0 MB/s  0:00:00
Downloading greenlet-3.5.5-cp314-cp314-win_amd64.whl (327 kB)
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Downloading mako-1.4.1-py3-none-any.whl (80 kB)
Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, PyYAML, MarkupSafe, greenlet, colorlog, sqlalchemy, Mako, alembic, optuna

   ---------------------------------------- 0/9 [tqdm]
   ---------------------------------------- 0/9 [tqdm]
   ---------------------------------------- 0/9 [tqdm]
   ---------------------------------------- 0/9 [tqdm]
   ---------------------------------------- 0/9 [tqdm]
   ---- ----------------------------------- 1/9 [PyYAML]
   ---- ----------------------------------- 1/9 [PyYAML]
   ---- ----------------------------------- 1/9 [PyYAML]
   -------- ------------------------------- 2/9 [MarkupSafe]
   ------------- -------------------------- 3/9 [greenlet]
   ------------- -------------------------- 3/9 [greenlet]
   ------------- -------------------------- 3/9 [greenlet]
   ------------- -------------------------- 3/9 [greenlet]
   ------------- -------------------------- 3/9 [greenlet]
   ----------------- ---------------------- 4/9 [colorlog]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   ---------------------- ----------------- 5/9 [sqlalchemy]
   -------------------------- ------------- 6/9 [Mako]
   -------------------------- ------------- 6/9 [Mako]
   -------------------------- ------------- 6/9 [Mako]
   -------------------------- ------------- 6/9 [Mako]
   -------------------------- ------------- 6/9 [Mako]
   -------------------------- ------------- 6/9 [Mako]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ------------------------------- -------- 7/9 [alembic]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ----------------------------------- ---- 8/9 [optuna]
   ---------------------------------------- 9/9 [optuna]

Successfully installed Mako-1.4.1 MarkupSafe-3.0.3 PyYAML-6.0.3 alembic-1.19.1 colorlog-6.12.0 greenlet-3.5.5 optuna-4.9.0 sqlalchemy-2.0.52 tqdm-4.70.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script tqdm.exe is installed in 'c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mako-render.exe is installed in 'c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script alembic.exe is installed in 'c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script optuna.exe is installed in 'c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Ako nedostaje CatBoost, pokreni: %pip install catboost
import gc
import pandas as pd
import numpy as np
from catboost import CatBoostRegressor
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import optuna
MODEL_NAME = 'CatBoost'

RANDOM_STATE = 42
HORIZONT = 12
VALIDATION_FRACTION = 0.10
BUFFER_STUPNJEVI = 0.3
CSV_PATH = 'ERA5_SPOJENO_2015_2023.csv'
OUTPUT_RESULTS = f'{MODEL_NAME.lower()}_rezultati_po_targetu.csv'

LAT_PULA, LON_PULA = 44.8666, 13.8496
LAT_RIJEKA, LON_RIJEKA = 45.3271, 14.4422

TARGETS = ['t2m_c', 'wind_speed_ms', 'swh', 'mwp', 'mwd', 'sst_c', 'msl_hpa', 'tcc', 'cape', 'blh']
LAG_VARS = ['t2m_c', 'msl_hpa', 'wind_speed_ms', 'tcc', 'cape']

# Za prvi test ostavi None. Ako nedostaje RAM-a, stavi npr. 300_000.
MAX_TRAIN_ROWS = None

c:\Users\Vanesa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Učitavanje i provjera podataka

In [19]:
df = pd.read_csv(CSV_PATH)
df['valid_time'] = pd.to_datetime(df['valid_time'])
df = df.sort_values(['latitude', 'longitude', 'valid_time']).reset_index(drop=True)

print(f'Ukupno redaka: {len(df):,}')
print(f'Broj stupaca: {df.shape[1]}')
print(f'Broj lokacija: {df[["latitude", "longitude"]].drop_duplicates().shape[0]}')
print(f'Period: {df["valid_time"].min()} do {df["valid_time"].max()}')

duplicate_count = df.duplicated(['valid_time', 'latitude', 'longitude']).sum()
print(f'Duplikati po vremenu i lokaciji: {duplicate_count:,}')

Ukupno redaka: 3,367,224
Broj stupaca: 37
Broj lokacija: 42
Period: 2015-01-01 00:00:00 do 2023-12-31 23:00:00
Duplikati po vremenu i lokaciji: 53,928

## 3. Izdvajanje Pula/Rijeka i trening skupa

In [20]:
locations = df[['latitude', 'longitude']].drop_duplicates().copy()
locations['dist_pula'] = np.sqrt((locations['latitude'] - LAT_PULA)**2 + (locations['longitude'] - LON_PULA)**2)
locations['dist_rijeka'] = np.sqrt((locations['latitude'] - LAT_RIJEKA)**2 + (locations['longitude'] - LON_RIJEKA)**2)

pula_grid = locations.loc[locations['dist_pula'].idxmin(), ['latitude', 'longitude']]
rijeka_grid = locations.loc[locations['dist_rijeka'].idxmin(), ['latitude', 'longitude']]
lat_pula_grid, lon_pula_grid = pula_grid['latitude'], pula_grid['longitude']
lat_rijeka_grid, lon_rijeka_grid = rijeka_grid['latitude'], rijeka_grid['longitude']

df['dist_pula'] = np.sqrt((df['latitude'] - LAT_PULA)**2 + (df['longitude'] - LON_PULA)**2)
df['dist_rijeka'] = np.sqrt((df['latitude'] - LAT_RIJEKA)**2 + (df['longitude'] - LON_RIJEKA)**2)
je_pula = (df['latitude'] == lat_pula_grid) & (df['longitude'] == lon_pula_grid)
je_rijeka = (df['latitude'] == lat_rijeka_grid) & (df['longitude'] == lon_rijeka_grid)
blizu = (df['dist_pula'] < BUFFER_STUPNJEVI) | (df['dist_rijeka'] < BUFFER_STUPNJEVI)

df_pula = df.loc[je_pula].copy()
df_rijeka = df.loc[je_rijeka].copy()
df_train = df.loc[~je_pula & ~je_rijeka & ~blizu].copy()

if MAX_TRAIN_ROWS is not None and len(df_train) > MAX_TRAIN_ROWS:
    df_train = df_train.sort_values(['valid_time', 'latitude', 'longitude']).iloc[:MAX_TRAIN_ROWS].copy()

print(f'Pula: {len(df_pula):,}')
print(f'Rijeka: {len(df_rijeka):,}')
print(f'Trening: {len(df_train):,}')
del locations
gc.collect()

Pula: 80,172
Rijeka: 80,172
Trening: 2,725,848

264

## 4. Feature engineering

In [21]:
def add_features(data):
    data = data.sort_values(['latitude', 'longitude', 'valid_time']).copy()
    groups = data.groupby(['latitude', 'longitude'])

    for var in LAG_VARS:
        if var not in data.columns:
            continue
        data[f'{var}_lag3h'] = groups[var].shift(3)
        data[f'{var}_lag6h'] = groups[var].shift(6)
        data[f'{var}_trend3h'] = data[var] - data[f'{var}_lag3h']
        data[f'{var}_rolling6h_mean'] = groups[var].transform(lambda s: s.rolling(6, min_periods=1).mean())

    if 'wind_dir_deg' in data.columns:
        data['wind_dir_sin'] = np.sin(np.radians(data['wind_dir_deg']))
        data['wind_dir_cos'] = np.cos(np.radians(data['wind_dir_deg']))

    hour = data['valid_time'].dt.hour
    day = data['valid_time'].dt.dayofyear
    data['hour_sin'] = np.sin(2 * np.pi * hour / 24)
    data['hour_cos'] = np.cos(2 * np.pi * hour / 24)
    data['day_sin'] = np.sin(2 * np.pi * day / 365.25)
    data['day_cos'] = np.cos(2 * np.pi * day / 365.25)

    if {'t2m_c', 'd2m_c'}.issubset(data.columns):
        data['temp_dewpoint_diff'] = data['t2m_c'] - data['d2m_c']
    if 'msl_hpa' in data.columns:
        data['pressure_gradient'] = groups['msl_hpa'].diff()

    return data

df_train = add_features(df_train)
df_pula = add_features(df_pula)
df_rijeka = add_features(df_rijeka)
print(f'Broj stupaca nakon feature engineeringa: {df_train.shape[1]}')

Broj stupaca nakon feature engineeringa: 67

## 5. Kreiranje budućih targeta

In [22]:
def add_future_targets(data):
    data = data.sort_values(['latitude', 'longitude', 'valid_time']).copy()
    groups = data.groupby(['latitude', 'longitude'])
    for target in TARGETS:
        if target in data.columns:
            data[f'{target}_future'] = groups[target].shift(-HORIZONT)
    return data

df_train = add_future_targets(df_train)
df_pula = add_future_targets(df_pula)
df_rijeka = add_future_targets(df_rijeka)

print('Targeti s dovoljnim podacima:')
for target in TARGETS:
    col = f'{target}_future'
    if col in df_train.columns:
        print(f'{target}: {df_train[col].notna().sum():,}')

Targeti s dovoljnim podacima:
t2m_c: 2,681,784
wind_speed_ms: 2,681,784
swh: 631,008
mwp: 631,008
mwd: 631,008
sst_c: 1,340,892
msl_hpa: 2,681,784
tcc: 2,681,784
cape: 2,681,784
blh: 2,681,784

## 6. Memorijski štedljiva priprema featurea

In [ ]:
DROP_COLUMNS = ['valid_time', 'latitude', 'longitude', 'dist_pula', 'dist_rijeka', 'hour', 'day']

def prepare_X(data, feature_names=None, medians=None):
    drop_cols = [c for c in DROP_COLUMNS if c in data.columns]
    drop_cols += [c for c in data.columns if c.endswith('_future')]

    numeric_cols = data.select_dtypes(include=[np.number]).columns
    selected_cols = [c for c in numeric_cols if c not in drop_cols]

    if feature_names is not None:
        selected_cols = [c for c in feature_names if c in data.columns]

    X = data.loc[:, selected_cols].copy()
    X = X.replace([np.inf, -np.inf], np.nan)

    if medians is None:
        medians = X.median()

    X = X.fillna(medians)

    if feature_names is not None:
        X = X.reindex(columns=feature_names, fill_value=0)

    # float32 zauzima približno pola memorije float64 podataka
    X = X.astype(np.float32)
    medians = medians.astype(np.float32)

    return X, medians

def make_model(name):
    if name == 'CatBoost':
        return CatBoostRegressor(
            iterations=300, depth=7, learning_rate=0.05,
            loss_function='MAE', random_seed=RANDOM_STATE,
            verbose=False, thread_count=2
        )

    raise ValueError('MODEL_NAME mora biti CatBoost')

## 7. Trening jednog targeta

In [24]:
def train_one_target(model_name, target, train_data, test_dict):
    target_col = f'{target}_future'

    if target_col not in train_data.columns:
        print(f'{target}: target ne postoji')
        return None

    valid_idx = train_data[target_col].notna()
    n_valid = int(valid_idx.sum())

    if n_valid < 1000:
        print(f'{target}: preskačem, samo {n_valid} valjanih redaka')
        return None

    # Ne kopiramo cijeli df_train, nego samo retke potrebne za ovaj target
    target_data = train_data.loc[valid_idx]
    y = target_data[target_col].astype(np.float32)
    X, medians = prepare_X(target_data)

    feature_names = X.columns.tolist()
    cutoff = int(len(X) * (1 - VALIDATION_FRACTION))

    X_fit = X.iloc[:cutoff]
    X_val = X.iloc[cutoff:]
    y_fit = y.iloc[:cutoff]
    y_val = y.iloc[cutoff:]

    print(f'{MODEL_NAME}/{target}: treniranje na {len(X_fit):,} redaka i {len(feature_names)} featurea')

    model = make_model(model_name)
    model.fit(X_fit, y_fit)
    pred_val = model.predict(X_val)

    result = {
        'model': model_name,
        'target': target,
        'horizon_hours': HORIZONT,
        'MAE_val': mean_absolute_error(y_val, pred_val),
        'RMSE_val': np.sqrt(mean_squared_error(y_val, pred_val)),
        'R2_val': r2_score(y_val, pred_val),
        'n_train': len(X_fit),
        'n_validation': len(X_val),
        'n_features': len(feature_names)
    }

    for location, test_data in test_dict.items():
        test_valid_idx = test_data[target_col].notna()
        n_test = int(test_valid_idx.sum())

        if n_test < 10:
            result[f'MAE_{location}'] = np.nan
            result[f'RMSE_{location}'] = np.nan
            result[f'R2_{location}'] = np.nan
            continue

        test_subset = test_data.loc[test_valid_idx]
        X_test, _ = prepare_X(test_subset, feature_names, medians)
        y_test = test_subset[target_col].astype(np.float32)
        pred_test = model.predict(X_test)

        result[f'MAE_{location}'] = mean_absolute_error(y_test, pred_test)
        result[f'RMSE_{location}'] = np.sqrt(mean_squared_error(y_test, pred_test))
        result[f'R2_{location}'] = r2_score(y_test, pred_test)

    print(f"{target}: MAE={result['MAE_val']:.3f}, R2={result['R2_val']:.3f}")

    gc.collect()
    return result

## 8. Pokretanje odabranog modela za sve targete

In [ ]:
if MODEL_NAME not in ['CatBoost']:
    raise ValueError('MODEL_NAME mora biti CatBoost')

test_dict = {'pula': df_pula, 'rijeka': df_rijeka}
results = []

for target in TARGETS:
    result = train_one_target(
        MODEL_NAME,
        target,
        df_train,
        test_dict
    )

    if result is not None:
        results.append(result)

results_df = pd.DataFrame(results)
results_df.to_csv(OUTPUT_RESULTS, index=False)

print('\n=== REZULTATI ===')
display(results_df)

print(f'Spremljeno u: {OUTPUT_RESULTS}')

RandomForest/t2m_c: treniranje na 2,413,605 redaka i 62 featurea
t2m_c: MAE=0.999, R2=0.974
RandomForest/wind_speed_ms: treniranje na 2,413,605 redaka i 62 featurea
wind_speed_ms: MAE=0.665, R2=0.540
RandomForest/swh: treniranje na 567,907 redaka i 62 featurea
swh: MAE=0.120, R2=0.661
RandomForest/mwp: treniranje na 567,907 redaka i 62 featurea
mwp: MAE=0.269, R2=0.810
RandomForest/mwd: treniranje na 567,907 redaka i 62 featurea
mwd: MAE=43.421, R2=0.332
RandomForest/sst_c: treniranje na 1,206,802 redaka i 62 featurea
sst_c: MAE=0.126, R2=0.999
RandomForest/msl_hpa: treniranje na 2,413,605 redaka i 62 featurea
msl_hpa: MAE=1.189, R2=0.957
RandomForest/tcc: treniranje na 2,413,605 redaka i 62 featurea
tcc: MAE=0.172, R2=0.678
RandomForest/cape: treniranje na 2,413,605 redaka i 62 featurea
cape: MAE=78.327, R2=0.713
RandomForest/blh: treniranje na 2,413,605 redaka i 62 featurea
blh: MAE=144.046, R2=0.814

=== REZULTATI ===

,model,target,horizon_hours,MAE_val,RMSE_val,R2_val,n_train,n_validation,n_features,MAE_pula,RMSE_pula,R2_pula,MAE_rijeka,RMSE_rijeka,R2_rijeka
0,RandomForest,t2m_c,12,0.998663,1.341453,0.974353,2413605,268179,62,0.466650,0.627260,0.990149,0.849347,1.114311,0.978808
1,RandomForest,wind_speed_ms,12,0.665340,0.850296,0.539879,2413605,268179,62,1.127176,1.496375,0.742523,0.771656,1.020622,0.625006
2,RandomForest,swh,12,0.120302,0.181808,0.660666,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
3,RandomForest,mwp,12,0.269356,0.354197,0.809982,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
4,RandomForest,mwd,12,43.420765,66.580013,0.331745,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
5,RandomForest,sst_c,12,0.125769,0.226992,0.998559,1206802,134090,62,0.087358,0.153376,0.999177,NaN,NaN,NaN
6,RandomForest,msl_hpa,12,1.189250,1.622875,0.957399,2413605,268179,62,0.600658,0.828401,0.988319,0.782442,1.076291,0.979740
7,RandomForest,tcc,12,0.171990,0.215026,0.677509,2413605,268179,62,0.132879,0.166871,0.813768,0.139656,0.176668,0.783026
8,RandomForest,cape,12,78.326796,202.594287,0.712946,2413605,268179,62,110.042749,258.328017,0.866398,71.377291,171.309032,0.751572
9,RandomForest,blh,12,144.045793,207.013064,0.814352,2413605,268179,62,98.020165,139.828429,0.828847,123.880445,177.571886,0.824285

Spremljeno u: randomforest_rezultati_po_targetu.csv

## 9. optuna

In [ ]:
OPTUNA_MAX_ROWS = None
CATBOOST_THREADS = 2
OPTUNA_TRIALS = 20

In [16]:
def prepare_optuna_data(target):
    target_col = f'{target}_future'

    valid_idx = df_train[target_col].notna()
    data = df_train.loc[valid_idx]

    if (
        OPTUNA_MAX_ROWS is not None
        and len(data) > OPTUNA_MAX_ROWS
    ):
        data = (
            data
            .sort_values(
                ['valid_time', 'latitude', 'longitude']
            )
            .iloc[:OPTUNA_MAX_ROWS]
        )

    y = data[target_col].astype(np.float32)
    X, medians = prepare_X(data)

    cutoff = int(
        len(X) * (1 - VALIDATION_FRACTION)
    )

    X_fit = X.iloc[:cutoff]
    X_val = X.iloc[cutoff:]

    y_fit = y.iloc[:cutoff]
    y_val = y.iloc[cutoff:]

    return X_fit, X_val, y_fit, y_val

In [17]:
def objective_catboost(trial, target):
    X_fit, X_val, y_fit, y_val = (
        prepare_optuna_data(target)
    )

    params = {
        'loss_function': 'MAE',
        'eval_metric': 'MAE',
        'random_seed': RANDOM_STATE,
        'thread_count': CATBOOST_THREADS,
        'verbose': False,

        'iterations': trial.suggest_int(
            'iterations', 200, 800
        ),

        'depth': trial.suggest_int(
            'depth', 4, 10
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.01,
            0.15,
            log=True
        ),

        'l2_leaf_reg': trial.suggest_float(
            'l2_leaf_reg',
            1.0,
            20.0,
            log=True
        ),

        'random_strength': trial.suggest_float(
            'random_strength',
            0.0,
            5.0
        ),

        'bagging_temperature': trial.suggest_float(
            'bagging_temperature',
            0.0,
            5.0
        ),

        'border_count': trial.suggest_int(
            'border_count',
            32,
            255
        )
    }

    model = CatBoostRegressor(**params)

    model.fit(
        X_fit,
        y_fit,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=False
    )

    pred = model.predict(X_val)

    score = mean_absolute_error(
        y_val,
        pred
    )

    del (
        X_fit,
        X_val,
        y_fit,
        y_val,
        model,
        pred
    )

    gc.collect()

    return score

## pokretanje optune

In [25]:
optuna_results = []
studies = {}

for target in TARGETS:
    target_col = f'{target}_future'

    if target_col not in df_train.columns:
        print(
            f'{target}: target ne postoji, preskačem.'
        )
        continue

    valid_count = int(
        df_train[target_col].notna().sum()
    )

    if valid_count < 1000:
        print(
            f'{target}: premalo podataka '
            f'({valid_count}), preskačem.'
        )
        continue

    print(
        f'\n===== OPTUNA CATBOOST: {target} ====='
    )

    study = optuna.create_study(
        direction='minimize',
        study_name=f'catboost_{target}',
        sampler=optuna.samplers.TPESampler(
            seed=RANDOM_STATE
        ),
        pruner=optuna.pruners.MedianPruner(
            n_startup_trials=2,
            n_warmup_steps=10
        )
    )

    study.optimize(
        lambda trial, current_target=target:
            objective_catboost(
                trial,
                current_target
            ),
        n_trials=OPTUNA_TRIALS,
        show_progress_bar=True
    )

    studies[target] = study

    row = {
        'model': 'CatBoost',
        'target': target,
        'best_MAE_optuna': study.best_value,
        'n_trials': len(study.trials),
        **study.best_params
    }

    optuna_results.append(row)

    print(
        f'Najbolji MAE za {target}: '
        f'{study.best_value:.4f}'
    )

    print(
        'Najbolji parametri:',
        study.best_params
    )

[I 2026-08-19 22:03:26,216] A new study created in memory with name: catboost_t2m_c

===== OPTUNA CATBOOST: t2m_c =====

Best trial: 0. Best value: 1.38922:   5%|▌         | 1/20 [17:03<5:23:58, 1023.09s/it]

[I 2026-08-19 22:20:29,405] Trial 0 finished with value: 1.3892190283507562 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  10%|█         | 2/20 [26:54<3:50:45, 769.21s/it]

[I 2026-08-19 22:30:20,909] Trial 1 finished with value: 1.4138326031185777 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  15%|█▌        | 3/20 [29:59<2:22:21, 502.46s/it]

[I 2026-08-19 22:33:25,932] Trial 2 finished with value: 2.1854887405366505 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  20%|██        | 4/20 [33:12<1:41:26, 380.41s/it]

[I 2026-08-19 22:36:39,229] Trial 3 finished with value: 2.02164285124745 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  25%|██▌       | 5/20 [38:07<1:27:20, 349.35s/it]

[I 2026-08-19 22:41:33,515] Trial 4 finished with value: 1.8075183398091104 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  30%|███       | 6/20 [45:36<1:29:26, 383.35s/it]

[I 2026-08-19 22:49:02,860] Trial 5 finished with value: 1.9523682640994164 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  35%|███▌      | 7/20 [55:52<1:39:32, 459.41s/it]

[I 2026-08-19 22:59:18,867] Trial 6 finished with value: 1.9209201775871807 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  40%|████      | 8/20 [1:12:44<2:07:02, 635.20s/it]

[I 2026-08-19 23:16:10,463] Trial 7 finished with value: 1.4396613918085424 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  45%|████▌     | 9/20 [1:15:30<1:29:34, 488.57s/it]

[I 2026-08-19 23:18:56,605] Trial 8 finished with value: 2.989076435646036 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 0. Best value: 1.38922:  50%|█████     | 10/20 [1:19:38<1:09:02, 414.29s/it]

[I 2026-08-19 23:23:04,568] Trial 9 finished with value: 1.8309293190650264 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 1.3892190283507562.

Best trial: 10. Best value: 1.36511:  55%|█████▌    | 11/20 [1:26:37<1:02:21, 415.68s/it]

[I 2026-08-19 23:30:03,394] Trial 10 finished with value: 1.3651104014020974 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 10 with value: 1.3651104014020974.

Best trial: 10. Best value: 1.36511:  60%|██████    | 12/20 [1:33:18<54:51, 411.49s/it]

[I 2026-08-19 23:36:45,296] Trial 11 finished with value: 1.3662739722906616 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 10 with value: 1.3651104014020974.

Best trial: 12. Best value: 1.33702:  65%|██████▌   | 13/20 [1:41:00<49:45, 426.55s/it]

[I 2026-08-19 23:44:26,515] Trial 12 finished with value: 1.3370210481723934 and parameters: {'iterations': 561, 'depth': 8, 'learning_rate': 0.14806829550654302, 'l2_leaf_reg': 19.940224979684842, 'random_strength': 0.021839605740445828, 'bagging_temperature': 2.5675169732221743, 'border_count': 42}. Best is trial 12 with value: 1.3370210481723934.

Best trial: 13. Best value: 1.33538:  70%|███████   | 14/20 [1:49:23<44:57, 449.59s/it]

[I 2026-08-19 23:52:49,331] Trial 13 finished with value: 1.3353761115696765 and parameters: {'iterations': 614, 'depth': 8, 'learning_rate': 0.13374547345150395, 'l2_leaf_reg': 12.906748623204937, 'random_strength': 1.161099984015153, 'bagging_temperature': 3.2592176991084347, 'border_count': 82}. Best is trial 13 with value: 1.3353761115696765.

Best trial: 13. Best value: 1.33538:  75%|███████▌  | 15/20 [1:56:37<37:04, 444.93s/it]

[I 2026-08-20 00:00:03,469] Trial 14 finished with value: 1.426832034801688 and parameters: {'iterations': 591, 'depth': 7, 'learning_rate': 0.1059747491980272, 'l2_leaf_reg': 11.52621757883041, 'random_strength': 1.123366282341044, 'bagging_temperature': 3.5732654327986357, 'border_count': 84}. Best is trial 13 with value: 1.3353761115696765.

Best trial: 15. Best value: 1.26297:  80%|████████  | 16/20 [2:08:41<35:16, 529.05s/it]

[I 2026-08-20 00:12:07,876] Trial 15 finished with value: 1.2629654937509605 and parameters: {'iterations': 798, 'depth': 9, 'learning_rate': 0.1062956360115325, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 0.9796449427592271, 'bagging_temperature': 1.9047138450049952, 'border_count': 89}. Best is trial 15 with value: 1.2629654937509605.

Best trial: 15. Best value: 1.26297:  85%|████████▌ | 17/20 [2:20:37<29:15, 585.11s/it]

[I 2026-08-20 00:24:03,369] Trial 16 finished with value: 1.2891338826717271 and parameters: {'iterations': 788, 'depth': 9, 'learning_rate': 0.09224657392762665, 'l2_leaf_reg': 10.759710880968507, 'random_strength': 2.909645001646248, 'bagging_temperature': 1.965900045018, 'border_count': 108}. Best is trial 15 with value: 1.2629654937509605.

Best trial: 15. Best value: 1.26297:  90%|█████████ | 18/20 [2:32:35<20:50, 625.28s/it]

[I 2026-08-20 00:36:02,161] Trial 17 finished with value: 1.4297496133454486 and parameters: {'iterations': 784, 'depth': 9, 'learning_rate': 0.040794449153959626, 'l2_leaf_reg': 9.776042572157433, 'random_strength': 2.9686510888910043, 'bagging_temperature': 1.9762597378926958, 'border_count': 113}. Best is trial 15 with value: 1.2629654937509605.

Best trial: 15. Best value: 1.26297:  95%|█████████▌| 19/20 [2:45:10<11:04, 664.18s/it]

[I 2026-08-20 00:48:36,937] Trial 18 finished with value: 1.2769841910934807 and parameters: {'iterations': 795, 'depth': 9, 'learning_rate': 0.09679628265674893, 'l2_leaf_reg': 9.485711912820392, 'random_strength': 2.9865818561954645, 'bagging_temperature': 1.932578151830753, 'border_count': 112}. Best is trial 15 with value: 1.2629654937509605.

Best trial: 15. Best value: 1.26297: 100%|██████████| 20/20 [2:56:03<00:00, 528.16s/it]
[I 2026-08-20 00:59:29,616] A new study created in memory with name: catboost_wind_speed_ms

[I 2026-08-20 00:59:29,593] Trial 19 finished with value: 1.390661894487577 and parameters: {'iterations': 693, 'depth': 9, 'learning_rate': 0.05783455186304768, 'l2_leaf_reg': 3.9375118893860654, 'random_strength': 3.132394567758081, 'bagging_temperature': 1.6374529382141045, 'border_count': 182}. Best is trial 15 with value: 1.2629654937509605.
Najbolji MAE za t2m_c: 1.2630
Najbolji parametri: {'iterations': 798, 'depth': 9, 'learning_rate': 0.1062956360115325, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 0.9796449427592271, 'bagging_temperature': 1.9047138450049952, 'border_count': 89}

===== OPTUNA CATBOOST: wind_speed_ms =====

Best trial: 0. Best value: 0.68357:   5%|▌         | 1/20 [16:44<5:18:13, 1004.90s/it]

[I 2026-08-20 01:16:14,516] Trial 0 finished with value: 0.6835699329596251 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  10%|█         | 2/20 [26:26<3:46:42, 755.68s/it]

[I 2026-08-20 01:25:55,735] Trial 1 finished with value: 0.7037947222854958 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  15%|█▌        | 3/20 [29:40<2:21:29, 499.38s/it]

[I 2026-08-20 01:29:10,129] Trial 2 finished with value: 0.8287556302573061 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  20%|██        | 4/20 [32:59<1:41:34, 380.91s/it]

[I 2026-08-20 01:32:29,427] Trial 3 finished with value: 0.8142058643371991 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  25%|██▌       | 5/20 [37:51<1:27:12, 348.85s/it]

[I 2026-08-20 01:37:21,419] Trial 4 finished with value: 0.7987280567529965 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  30%|███       | 6/20 [45:35<1:30:30, 387.90s/it]

[I 2026-08-20 01:45:05,123] Trial 5 finished with value: 0.8070784061117728 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  35%|███▌      | 7/20 [55:53<1:40:20, 463.10s/it]

[I 2026-08-20 01:55:23,035] Trial 6 finished with value: 0.7917880437677404 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  40%|████      | 8/20 [1:12:40<2:07:16, 636.34s/it]

[I 2026-08-20 02:12:10,317] Trial 7 finished with value: 0.706981748730444 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  45%|████▌     | 9/20 [1:15:21<1:29:25, 487.81s/it]

[I 2026-08-20 02:14:51,531] Trial 8 finished with value: 0.8694576238143644 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  50%|█████     | 10/20 [1:19:34<1:09:10, 415.05s/it]

[I 2026-08-20 02:19:03,654] Trial 9 finished with value: 0.8006337174825646 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  55%|█████▌    | 11/20 [1:26:29<1:02:16, 415.16s/it]

[I 2026-08-20 02:25:59,074] Trial 10 finished with value: 0.6874620585996631 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  60%|██████    | 12/20 [1:33:09<54:44, 410.61s/it]

[I 2026-08-20 02:32:39,271] Trial 11 finished with value: 0.6847393693144621 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 0. Best value: 0.68357:  65%|██████▌   | 13/20 [1:39:14<46:17, 396.78s/it]

[I 2026-08-20 02:38:44,245] Trial 12 finished with value: 0.6891759889197401 and parameters: {'iterations': 448, 'depth': 8, 'learning_rate': 0.1479499391780178, 'l2_leaf_reg': 10.14619476031968, 'random_strength': 0.9205526856763969, 'bagging_temperature': 1.9379710203198046, 'border_count': 43}. Best is trial 0 with value: 0.6835699329596251.

Best trial: 13. Best value: 0.667716:  70%|███████   | 14/20 [1:48:22<44:15, 442.52s/it]

[I 2026-08-20 02:47:52,442] Trial 13 finished with value: 0.6677163627806593 and parameters: {'iterations': 608, 'depth': 9, 'learning_rate': 0.10186022221074563, 'l2_leaf_reg': 19.228151286480458, 'random_strength': 0.9620327283354857, 'bagging_temperature': 0.09882497202737206, 'border_count': 82}. Best is trial 13 with value: 0.6677163627806593.

Best trial: 13. Best value: 0.667716:  75%|███████▌  | 15/20 [1:57:17<39:11, 470.35s/it]

[I 2026-08-20 02:56:47,290] Trial 14 finished with value: 0.6762322207046542 and parameters: {'iterations': 591, 'depth': 9, 'learning_rate': 0.08965903968031579, 'l2_leaf_reg': 11.000665601179929, 'random_strength': 1.123366282341044, 'bagging_temperature': 0.16166169030530553, 'border_count': 84}. Best is trial 13 with value: 0.6677163627806593.

Best trial: 15. Best value: 0.66469:  80%|████████  | 16/20 [2:06:39<33:11, 497.98s/it]

[I 2026-08-20 03:06:09,443] Trial 15 finished with value: 0.6646901274351046 and parameters: {'iterations': 625, 'depth': 9, 'learning_rate': 0.10151391122373392, 'l2_leaf_reg': 11.358307619279357, 'random_strength': 1.1826866168418348, 'bagging_temperature': 0.15352309006153603, 'border_count': 96}. Best is trial 15 with value: 0.6646901274351046.

Best trial: 16. Best value: 0.662476:  85%|████████▌ | 17/20 [2:16:32<26:18, 526.33s/it]

[I 2026-08-20 03:16:01,705] Trial 16 finished with value: 0.6624758142508327 and parameters: {'iterations': 653, 'depth': 9, 'learning_rate': 0.10339034896178922, 'l2_leaf_reg': 11.495870380984927, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.009194510493302915, 'border_count': 108}. Best is trial 16 with value: 0.6624758142508327.

Best trial: 16. Best value: 0.662476:  90%|█████████ | 18/20 [2:28:18<19:20, 580.41s/it]

[I 2026-08-20 03:27:47,992] Trial 17 finished with value: 0.694518093680311 and parameters: {'iterations': 763, 'depth': 9, 'learning_rate': 0.04976101132363162, 'l2_leaf_reg': 11.586121212633548, 'random_strength': 2.997509191284597, 'bagging_temperature': 0.023700598265448125, 'border_count': 116}. Best is trial 16 with value: 0.6624758142508327.

Best trial: 16. Best value: 0.662476:  95%|█████████▌| 19/20 [2:36:17<09:09, 549.96s/it]

[I 2026-08-20 03:35:47,023] Trial 18 finished with value: 0.7060844532612429 and parameters: {'iterations': 664, 'depth': 7, 'learning_rate': 0.10427336638663956, 'l2_leaf_reg': 13.135005936265685, 'random_strength': 2.9138716554456425, 'bagging_temperature': 1.2854764348675227, 'border_count': 112}. Best is trial 16 with value: 0.6624758142508327.

Best trial: 16. Best value: 0.662476: 100%|██████████| 20/20 [2:48:46<00:00, 506.33s/it]
[I 2026-08-20 03:48:16,222] A new study created in memory with name: catboost_swh

[I 2026-08-20 03:48:16,205] Trial 19 finished with value: 0.7111690627733583 and parameters: {'iterations': 785, 'depth': 9, 'learning_rate': 0.037843711931659606, 'l2_leaf_reg': 8.416254361541025, 'random_strength': 3.132394567758081, 'bagging_temperature': 1.8867207567360107, 'border_count': 178}. Best is trial 16 with value: 0.6624758142508327.
Najbolji MAE za wind_speed_ms: 0.6625
Najbolji parametri: {'iterations': 653, 'depth': 9, 'learning_rate': 0.10339034896178922, 'l2_leaf_reg': 11.495870380984927, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.009194510493302915, 'border_count': 108}

===== OPTUNA CATBOOST: swh =====

Best trial: 0. Best value: 0.104752:   5%|▌         | 1/20 [03:59<1:15:57, 239.86s/it]

[I 2026-08-20 03:52:16,084] Trial 0 finished with value: 0.10475223023193424 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  10%|█         | 2/20 [06:26<55:32, 185.15s/it]

[I 2026-08-20 03:54:42,942] Trial 1 finished with value: 0.10629397658453046 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  15%|█▌        | 3/20 [07:11<34:20, 121.18s/it]

[I 2026-08-20 03:55:27,989] Trial 2 finished with value: 0.12006131645565572 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  20%|██        | 4/20 [07:59<24:32, 92.03s/it]

[I 2026-08-20 03:56:15,345] Trial 3 finished with value: 0.11905618837044184 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  25%|██▌       | 5/20 [09:09<21:01, 84.09s/it]

[I 2026-08-20 03:57:25,344] Trial 4 finished with value: 0.11570750572241602 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  30%|███       | 6/20 [11:00<21:46, 93.35s/it]

[I 2026-08-20 03:59:16,676] Trial 5 finished with value: 0.1178275591346829 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  35%|███▌      | 7/20 [14:23<28:01, 129.37s/it]

[I 2026-08-20 04:02:40,192] Trial 6 finished with value: 0.1168774264310155 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  40%|████      | 8/20 [21:09<43:27, 217.32s/it]

[I 2026-08-20 04:09:25,822] Trial 7 finished with value: 0.1070669841381983 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  45%|████▌     | 9/20 [21:48<29:35, 161.45s/it]

[I 2026-08-20 04:10:04,421] Trial 8 finished with value: 0.12369002235342029 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  50%|█████     | 10/20 [22:48<21:41, 130.18s/it]

[I 2026-08-20 04:11:04,584] Trial 9 finished with value: 0.11659282707479497 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  55%|█████▌    | 11/20 [24:27<18:07, 120.82s/it]

[I 2026-08-20 04:12:44,200] Trial 10 finished with value: 0.10548324754950415 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  60%|██████    | 12/20 [26:03<15:05, 113.16s/it]

[I 2026-08-20 04:14:19,820] Trial 11 finished with value: 0.10496148475359789 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 0. Best value: 0.104752:  65%|██████▌   | 13/20 [27:30<12:17, 105.33s/it]

[I 2026-08-20 04:15:47,141] Trial 12 finished with value: 0.10516389947000554 and parameters: {'iterations': 448, 'depth': 8, 'learning_rate': 0.1479499391780178, 'l2_leaf_reg': 10.14619476031968, 'random_strength': 0.9205526856763969, 'bagging_temperature': 1.9379710203198046, 'border_count': 43}. Best is trial 0 with value: 0.10475223023193424.

Best trial: 13. Best value: 0.102265:  70%|███████   | 14/20 [29:52<11:37, 116.30s/it]

[I 2026-08-20 04:18:08,783] Trial 13 finished with value: 0.10226493525211493 and parameters: {'iterations': 608, 'depth': 9, 'learning_rate': 0.10186022221074563, 'l2_leaf_reg': 19.228151286480458, 'random_strength': 0.9620327283354857, 'bagging_temperature': 0.09882497202737206, 'border_count': 82}. Best is trial 13 with value: 0.10226493525211493.

Best trial: 13. Best value: 0.102265:  75%|███████▌  | 15/20 [32:11<10:15, 123.01s/it]

[I 2026-08-20 04:20:27,335] Trial 14 finished with value: 0.10319753022070384 and parameters: {'iterations': 591, 'depth': 9, 'learning_rate': 0.08965903968031579, 'l2_leaf_reg': 11.000665601179929, 'random_strength': 1.123366282341044, 'bagging_temperature': 0.16166169030530553, 'border_count': 84}. Best is trial 13 with value: 0.10226493525211493.

Best trial: 15. Best value: 0.101437:  80%|████████  | 16/20 [34:40<08:43, 130.89s/it]

[I 2026-08-20 04:22:56,523] Trial 15 finished with value: 0.10143691247679902 and parameters: {'iterations': 625, 'depth': 9, 'learning_rate': 0.10151391122373392, 'l2_leaf_reg': 11.358307619279357, 'random_strength': 1.1826866168418348, 'bagging_temperature': 0.15352309006153603, 'border_count': 96}. Best is trial 15 with value: 0.10143691247679902.

Best trial: 15. Best value: 0.101437:  85%|████████▌ | 17/20 [37:18<06:57, 139.12s/it]

[I 2026-08-20 04:25:34,776] Trial 16 finished with value: 0.10229947029433754 and parameters: {'iterations': 653, 'depth': 9, 'learning_rate': 0.10339034896178922, 'l2_leaf_reg': 11.495870380984927, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.009194510493302915, 'border_count': 108}. Best is trial 15 with value: 0.10143691247679902.

Best trial: 15. Best value: 0.101437:  90%|█████████ | 18/20 [40:25<05:06, 153.35s/it]

[I 2026-08-20 04:28:41,245] Trial 17 finished with value: 0.10505819612389769 and parameters: {'iterations': 754, 'depth': 9, 'learning_rate': 0.04987906352494948, 'l2_leaf_reg': 13.315664963764366, 'random_strength': 2.912554411220168, 'bagging_temperature': 1.2557234573468157, 'border_count': 108}. Best is trial 15 with value: 0.10143691247679902.

Best trial: 15. Best value: 0.101437:  95%|█████████▌| 19/20 [42:40<02:28, 148.08s/it]

[I 2026-08-20 04:30:57,074] Trial 18 finished with value: 0.10529157465003726 and parameters: {'iterations': 785, 'depth': 7, 'learning_rate': 0.10441181305472144, 'l2_leaf_reg': 8.767603174484424, 'random_strength': 1.368906366082553, 'bagging_temperature': 0.6037910826765898, 'border_count': 78}. Best is trial 15 with value: 0.10143691247679902.

Best trial: 15. Best value: 0.101437: 100%|██████████| 20/20 [45:16<00:00, 135.82s/it]
[I 2026-08-20 04:33:32,620] A new study created in memory with name: catboost_mwp

[I 2026-08-20 04:33:32,610] Trial 19 finished with value: 0.1082518511434929 and parameters: {'iterations': 623, 'depth': 9, 'learning_rate': 0.037843711931659606, 'l2_leaf_reg': 14.486022833429184, 'random_strength': 2.7029681440684916, 'bagging_temperature': 1.8867207567360107, 'border_count': 120}. Best is trial 15 with value: 0.10143691247679902.
Najbolji MAE za swh: 0.1014
Najbolji parametri: {'iterations': 625, 'depth': 9, 'learning_rate': 0.10151391122373392, 'l2_leaf_reg': 11.358307619279357, 'random_strength': 1.1826866168418348, 'bagging_temperature': 0.15352309006153603, 'border_count': 96}

===== OPTUNA CATBOOST: mwp =====

Best trial: 0. Best value: 0.250085:   5%|▌         | 1/20 [03:58<1:15:29, 238.41s/it]

[I 2026-08-20 04:37:31,028] Trial 0 finished with value: 0.2500849298545642 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  10%|█         | 2/20 [06:23<55:04, 183.57s/it]

[I 2026-08-20 04:39:56,212] Trial 1 finished with value: 0.25387309712830725 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  15%|█▌        | 3/20 [07:08<34:01, 120.07s/it]

[I 2026-08-20 04:40:40,718] Trial 2 finished with value: 0.287515180167141 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  20%|██        | 4/20 [07:55<24:20, 91.26s/it]

[I 2026-08-20 04:41:27,806] Trial 3 finished with value: 0.284506337086214 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  25%|██▌       | 5/20 [09:03<20:44, 82.99s/it]

[I 2026-08-20 04:42:36,143] Trial 4 finished with value: 0.2764824973026879 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  30%|███       | 6/20 [10:52<21:25, 91.83s/it]

[I 2026-08-20 04:44:25,132] Trial 5 finished with value: 0.282333356448965 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  35%|███▌      | 7/20 [14:18<27:59, 129.17s/it]

[I 2026-08-20 04:47:51,169] Trial 6 finished with value: 0.2800988938806136 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  40%|████      | 8/20 [21:04<43:25, 217.15s/it]

[I 2026-08-20 04:54:36,692] Trial 7 finished with value: 0.2564128687342197 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  45%|████▌     | 9/20 [21:43<29:36, 161.48s/it]

[I 2026-08-20 04:55:15,770] Trial 8 finished with value: 0.30306342112081686 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 0. Best value: 0.250085:  50%|█████     | 10/20 [22:42<21:39, 129.92s/it]

[I 2026-08-20 04:56:15,026] Trial 9 finished with value: 0.2785304399225432 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 0.2500849298545642.

Best trial: 10. Best value: 0.249978:  55%|█████▌    | 11/20 [24:21<18:04, 120.53s/it]

[I 2026-08-20 04:57:54,263] Trial 10 finished with value: 0.24997756496538026 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 10 with value: 0.24997756496538026.

Best trial: 10. Best value: 0.249978:  60%|██████    | 12/20 [25:57<15:04, 113.00s/it]

[I 2026-08-20 04:59:30,042] Trial 11 finished with value: 0.25097846797363904 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 10 with value: 0.24997756496538026.

Best trial: 12. Best value: 0.248177:  65%|██████▌   | 13/20 [27:47<13:04, 112.10s/it]

[I 2026-08-20 05:01:20,066] Trial 12 finished with value: 0.24817691987558488 and parameters: {'iterations': 574, 'depth': 8, 'learning_rate': 0.14788557091109908, 'l2_leaf_reg': 10.48947540877023, 'random_strength': 0.9205526856763969, 'bagging_temperature': 3.6317336069528454, 'border_count': 43}. Best is trial 12 with value: 0.24817691987558488.

Best trial: 13. Best value: 0.247257:  70%|███████   | 14/20 [29:49<11:30, 115.07s/it]

[I 2026-08-20 05:03:22,007] Trial 13 finished with value: 0.24725695769292655 and parameters: {'iterations': 614, 'depth': 8, 'learning_rate': 0.1337251463851132, 'l2_leaf_reg': 11.621220660700262, 'random_strength': 1.161099984015153, 'bagging_temperature': 3.602497192429867, 'border_count': 82}. Best is trial 13 with value: 0.24725695769292655.

Best trial: 13. Best value: 0.247257:  75%|███████▌  | 15/20 [31:31<09:16, 111.23s/it]

[I 2026-08-20 05:05:04,342] Trial 14 finished with value: 0.2542484935929341 and parameters: {'iterations': 591, 'depth': 7, 'learning_rate': 0.1059747491980272, 'l2_leaf_reg': 10.929717419536411, 'random_strength': 1.15476894640308, 'bagging_temperature': 3.5883387030832017, 'border_count': 84}. Best is trial 13 with value: 0.24725695769292655.

Best trial: 15. Best value: 0.240499:  80%|████████  | 16/20 [34:40<08:58, 134.53s/it]

[I 2026-08-20 05:08:12,954] Trial 15 finished with value: 0.24049905870350835 and parameters: {'iterations': 798, 'depth': 9, 'learning_rate': 0.10625536384372183, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 2.556036556756151, 'bagging_temperature': 3.637362117931279, 'border_count': 89}. Best is trial 15 with value: 0.24049905870350835.

Best trial: 15. Best value: 0.240499:  85%|████████▌ | 17/20 [37:49<07:33, 151.08s/it]

[I 2026-08-20 05:11:22,530] Trial 16 finished with value: 0.24251296203719763 and parameters: {'iterations': 788, 'depth': 9, 'learning_rate': 0.09224657392762665, 'l2_leaf_reg': 11.442127199644112, 'random_strength': 2.9479925092287966, 'bagging_temperature': 4.846349260243589, 'border_count': 108}. Best is trial 15 with value: 0.24049905870350835.

Best trial: 15. Best value: 0.240499:  90%|█████████ | 18/20 [41:00<05:25, 162.96s/it]

[I 2026-08-20 05:14:33,149] Trial 17 finished with value: 0.25437938264428245 and parameters: {'iterations': 784, 'depth': 9, 'learning_rate': 0.040794449153959626, 'l2_leaf_reg': 12.32420118578788, 'random_strength': 2.976256970648016, 'bagging_temperature': 4.844754433652488, 'border_count': 113}. Best is trial 15 with value: 0.24049905870350835.

Best trial: 15. Best value: 0.240499:  95%|█████████▌| 19/20 [44:13<02:52, 172.08s/it]

[I 2026-08-20 05:17:46,478] Trial 18 finished with value: 0.24126089288306973 and parameters: {'iterations': 795, 'depth': 9, 'learning_rate': 0.09678047453145969, 'l2_leaf_reg': 8.356957146362218, 'random_strength': 3.2132564781157607, 'bagging_temperature': 4.279165841065752, 'border_count': 112}. Best is trial 15 with value: 0.24049905870350835.

Best trial: 15. Best value: 0.240499: 100%|██████████| 20/20 [47:20<00:00, 142.02s/it]
[I 2026-08-20 05:20:53,013] A new study created in memory with name: catboost_mwd

[I 2026-08-20 05:20:53,003] Trial 19 finished with value: 0.2505820507456931 and parameters: {'iterations': 693, 'depth': 9, 'learning_rate': 0.05782821853242786, 'l2_leaf_reg': 3.7551677370559537, 'random_strength': 2.8674998506912877, 'bagging_temperature': 4.3385705985573155, 'border_count': 182}. Best is trial 15 with value: 0.24049905870350835.
Najbolji MAE za mwp: 0.2405
Najbolji parametri: {'iterations': 798, 'depth': 9, 'learning_rate': 0.10625536384372183, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 2.556036556756151, 'bagging_temperature': 3.637362117931279, 'border_count': 89}

===== OPTUNA CATBOOST: mwd =====

Best trial: 0. Best value: 42.6329:   5%|▌         | 1/20 [03:58<1:15:37, 238.80s/it]

[I 2026-08-20 05:24:51,814] Trial 0 finished with value: 42.632882673398775 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  10%|█         | 2/20 [06:23<55:03, 183.55s/it]

[I 2026-08-20 05:27:16,690] Trial 1 finished with value: 43.47361592141049 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  15%|█▌        | 3/20 [07:09<34:13, 120.80s/it]

[I 2026-08-20 05:28:02,810] Trial 2 finished with value: 48.21266348490504 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  20%|██        | 4/20 [07:58<24:37, 92.34s/it]

[I 2026-08-20 05:28:51,519] Trial 3 finished with value: 47.618469639618304 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  25%|██▌       | 5/20 [09:07<21:01, 84.09s/it]

[I 2026-08-20 05:30:00,977] Trial 4 finished with value: 47.42380895502925 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  30%|███       | 6/20 [11:00<21:54, 93.89s/it]

[I 2026-08-20 05:31:53,904] Trial 5 finished with value: 47.26571432112248 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  35%|███▌      | 7/20 [14:26<28:16, 130.50s/it]

[I 2026-08-20 05:35:19,765] Trial 6 finished with value: 45.48131264782255 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  40%|████      | 8/20 [21:15<43:47, 218.94s/it]

[I 2026-08-20 05:42:08,076] Trial 7 finished with value: 43.449786392742084 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  45%|████▌     | 9/20 [21:56<29:59, 163.55s/it]

[I 2026-08-20 05:42:49,832] Trial 8 finished with value: 49.0533385552218 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  50%|█████     | 10/20 [22:58<21:59, 131.97s/it]

[I 2026-08-20 05:43:51,086] Trial 9 finished with value: 47.215797384898636 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  55%|█████▌    | 11/20 [24:36<18:15, 121.76s/it]

[I 2026-08-20 05:45:29,708] Trial 10 finished with value: 43.09647774280881 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  60%|██████    | 12/20 [26:12<15:11, 113.97s/it]

[I 2026-08-20 05:47:05,839] Trial 11 finished with value: 42.929020030560324 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 0 with value: 42.632882673398775.

Best trial: 0. Best value: 42.6329:  65%|██████▌   | 13/20 [27:39<12:20, 105.81s/it]

[I 2026-08-20 05:48:32,868] Trial 12 finished with value: 42.9579699948267 and parameters: {'iterations': 448, 'depth': 8, 'learning_rate': 0.1479499391780178, 'l2_leaf_reg': 10.14619476031968, 'random_strength': 0.9205526856763969, 'bagging_temperature': 1.9379710203198046, 'border_count': 43}. Best is trial 0 with value: 42.632882673398775.

Best trial: 13. Best value: 42.3563:  70%|███████   | 14/20 [30:02<11:40, 116.82s/it]

[I 2026-08-20 05:50:55,146] Trial 13 finished with value: 42.35634756031345 and parameters: {'iterations': 608, 'depth': 9, 'learning_rate': 0.10186022221074563, 'l2_leaf_reg': 19.228151286480458, 'random_strength': 0.9620327283354857, 'bagging_temperature': 0.09882497202737206, 'border_count': 82}. Best is trial 13 with value: 42.35634756031345.

Best trial: 13. Best value: 42.3563:  75%|███████▌  | 15/20 [32:22<10:20, 124.04s/it]

[I 2026-08-20 05:53:15,904] Trial 14 finished with value: 42.498293492200425 and parameters: {'iterations': 591, 'depth': 9, 'learning_rate': 0.08965903968031579, 'l2_leaf_reg': 11.000665601179929, 'random_strength': 1.123366282341044, 'bagging_temperature': 0.16166169030530553, 'border_count': 84}. Best is trial 13 with value: 42.35634756031345.

Best trial: 15. Best value: 42.2693:  80%|████████  | 16/20 [34:53<08:47, 131.98s/it]

[I 2026-08-20 05:55:46,326] Trial 15 finished with value: 42.26930441476814 and parameters: {'iterations': 625, 'depth': 9, 'learning_rate': 0.10151391122373392, 'l2_leaf_reg': 11.358307619279357, 'random_strength': 1.1826866168418348, 'bagging_temperature': 0.15352309006153603, 'border_count': 96}. Best is trial 15 with value: 42.26930441476814.

Best trial: 15. Best value: 42.2693:  85%|████████▌ | 17/20 [37:31<06:59, 139.97s/it]

[I 2026-08-20 05:58:24,888] Trial 16 finished with value: 42.35513076566589 and parameters: {'iterations': 653, 'depth': 9, 'learning_rate': 0.10339034896178922, 'l2_leaf_reg': 11.495870380984927, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.009194510493302915, 'border_count': 108}. Best is trial 15 with value: 42.26930441476814.

Best trial: 15. Best value: 42.2693:  90%|█████████ | 18/20 [40:47<05:13, 156.73s/it]

[I 2026-08-20 06:01:40,614] Trial 17 finished with value: 42.87880361709068 and parameters: {'iterations': 763, 'depth': 9, 'learning_rate': 0.04976101132363162, 'l2_leaf_reg': 11.586121212633548, 'random_strength': 2.997509191284597, 'bagging_temperature': 0.023700598265448125, 'border_count': 116}. Best is trial 15 with value: 42.26930441476814.

Best trial: 15. Best value: 42.2693:  95%|█████████▌| 19/20 [42:45<02:25, 145.21s/it]

[I 2026-08-20 06:03:38,982] Trial 18 finished with value: 43.66882396550492 and parameters: {'iterations': 664, 'depth': 7, 'learning_rate': 0.10427336638663956, 'l2_leaf_reg': 13.135005936265685, 'random_strength': 2.9138716554456425, 'bagging_temperature': 1.2854764348675227, 'border_count': 112}. Best is trial 15 with value: 42.26930441476814.

Best trial: 15. Best value: 42.2693: 100%|██████████| 20/20 [46:19<00:00, 138.97s/it]
[I 2026-08-20 06:07:12,394] A new study created in memory with name: catboost_sst_c

[I 2026-08-20 06:07:12,383] Trial 19 finished with value: 43.52947413884607 and parameters: {'iterations': 785, 'depth': 9, 'learning_rate': 0.037843711931659606, 'l2_leaf_reg': 8.416254361541025, 'random_strength': 3.132394567758081, 'bagging_temperature': 1.8867207567360107, 'border_count': 178}. Best is trial 15 with value: 42.26930441476814.
Najbolji MAE za mwd: 42.2693
Najbolji parametri: {'iterations': 625, 'depth': 9, 'learning_rate': 0.10151391122373392, 'l2_leaf_reg': 11.358307619279357, 'random_strength': 1.1826866168418348, 'bagging_temperature': 0.15352309006153603, 'border_count': 96}

===== OPTUNA CATBOOST: sst_c =====

Best trial: 0. Best value: 0.261487:   5%|▌         | 1/20 [08:15<2:37:03, 495.99s/it]

[I 2026-08-20 06:15:28,379] Trial 0 finished with value: 0.2614866258411156 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 0.2614866258411156.

Best trial: 1. Best value: 0.205679:  10%|█         | 2/20 [13:15<1:54:11, 380.62s/it]

[I 2026-08-20 06:20:28,248] Trial 1 finished with value: 0.2056792735597987 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 1 with value: 0.2056792735597987.

Best trial: 1. Best value: 0.205679:  15%|█▌        | 3/20 [14:42<1:09:49, 246.43s/it]

[I 2026-08-20 06:21:54,981] Trial 2 finished with value: 0.3190254740232891 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 1 with value: 0.2056792735597987.

Best trial: 1. Best value: 0.205679:  20%|██        | 4/20 [16:15<49:34, 185.92s/it]

[I 2026-08-20 06:23:28,134] Trial 3 finished with value: 0.2921682232564674 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 1 with value: 0.2056792735597987.

Best trial: 4. Best value: 0.181916:  25%|██▌       | 5/20 [18:40<42:45, 171.02s/it]

[I 2026-08-20 06:25:52,729] Trial 4 finished with value: 0.18191625084314694 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 4. Best value: 0.181916:  30%|███       | 6/20 [22:14<43:18, 185.63s/it]

[I 2026-08-20 06:29:26,735] Trial 5 finished with value: 0.25237304234030417 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 4. Best value: 0.181916:  35%|███▌      | 7/20 [27:49<50:47, 234.44s/it]

[I 2026-08-20 06:35:01,671] Trial 6 finished with value: 0.45311524360135885 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 4. Best value: 0.181916:  40%|████      | 8/20 [37:52<1:10:21, 351.82s/it]

[I 2026-08-20 06:45:04,827] Trial 7 finished with value: 0.18468163311088542 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 4. Best value: 0.181916:  45%|████▌     | 9/20 [39:17<49:13, 268.51s/it]

[I 2026-08-20 06:46:30,142] Trial 8 finished with value: 0.8449886068173469 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 4. Best value: 0.181916:  50%|█████     | 10/20 [41:22<37:19, 224.00s/it]

[I 2026-08-20 06:48:34,468] Trial 9 finished with value: 0.2116598082686562 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 4. Best value: 0.181916:  55%|█████▌    | 11/20 [45:14<34:00, 226.69s/it]

[I 2026-08-20 06:52:27,249] Trial 10 finished with value: 0.1993674315264628 and parameters: {'iterations': 574, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10534330917911544, 'bagging_temperature': 4.538323976412588, 'border_count': 89}. Best is trial 4 with value: 0.18191625084314694.

Best trial: 11. Best value: 0.167228:  60%|██████    | 12/20 [49:21<31:00, 232.61s/it]

[I 2026-08-20 06:56:33,400] Trial 11 finished with value: 0.16722827515483318 and parameters: {'iterations': 551, 'depth': 8, 'learning_rate': 0.10162761137090683, 'l2_leaf_reg': 19.390050981512594, 'random_strength': 3.231726141495259, 'bagging_temperature': 3.322165096958587, 'border_count': 254}. Best is trial 11 with value: 0.16722827515483318.

Best trial: 12. Best value: 0.164748:  65%|██████▌   | 13/20 [53:35<27:55, 239.30s/it]

[I 2026-08-20 07:00:48,092] Trial 12 finished with value: 0.16474764946295337 and parameters: {'iterations': 573, 'depth': 8, 'learning_rate': 0.14679944986694218, 'l2_leaf_reg': 2.2116137079374356, 'random_strength': 3.1193460515400453, 'bagging_temperature': 3.6425849053007076, 'border_count': 204}. Best is trial 12 with value: 0.16474764946295337.

Best trial: 13. Best value: 0.164107:  70%|███████   | 14/20 [57:52<24:27, 244.62s/it]

[I 2026-08-20 07:05:05,020] Trial 13 finished with value: 0.16410703780268407 and parameters: {'iterations': 585, 'depth': 8, 'learning_rate': 0.13360303267425996, 'l2_leaf_reg': 10.099416769827782, 'random_strength': 2.8145159437092273, 'bagging_temperature': 3.52412006645383, 'border_count': 191}. Best is trial 13 with value: 0.16410703780268407.

Best trial: 13. Best value: 0.164107:  75%|███████▌  | 15/20 [1:02:50<21:43, 260.63s/it]

[I 2026-08-20 07:10:02,749] Trial 14 finished with value: 0.16649535066213414 and parameters: {'iterations': 781, 'depth': 7, 'learning_rate': 0.14974124121928395, 'l2_leaf_reg': 10.120411805935376, 'random_strength': 2.954038992607804, 'bagging_temperature': 3.758458171235827, 'border_count': 195}. Best is trial 13 with value: 0.16410703780268407.

Best trial: 13. Best value: 0.164107:  80%|████████  | 16/20 [1:08:20<18:46, 281.62s/it]

[I 2026-08-20 07:15:33,126] Trial 15 finished with value: 0.16882210932352204 and parameters: {'iterations': 632, 'depth': 9, 'learning_rate': 0.10779460845128598, 'l2_leaf_reg': 3.089271615558442, 'random_strength': 2.931791201073976, 'bagging_temperature': 2.127757495179842, 'border_count': 190}. Best is trial 13 with value: 0.16410703780268407.

Best trial: 13. Best value: 0.164107:  85%|████████▌ | 17/20 [1:11:22<12:34, 251.45s/it]

[I 2026-08-20 07:18:34,409] Trial 16 finished with value: 0.19679327166939084 and parameters: {'iterations': 476, 'depth': 7, 'learning_rate': 0.11603526949233527, 'l2_leaf_reg': 11.97367589696364, 'random_strength': 3.524125221205038, 'bagging_temperature': 3.646889037586642, 'border_count': 118}. Best is trial 13 with value: 0.16410703780268407.

Best trial: 13. Best value: 0.164107:  90%|█████████ | 18/20 [1:15:42<08:28, 254.25s/it]

[I 2026-08-20 07:22:55,174] Trial 17 finished with value: 0.17145723064743676 and parameters: {'iterations': 495, 'depth': 9, 'learning_rate': 0.08905675325717259, 'l2_leaf_reg': 2.10647498710426, 'random_strength': 2.619431324467989, 'bagging_temperature': 2.3214321646459246, 'border_count': 209}. Best is trial 13 with value: 0.16410703780268407.

Best trial: 13. Best value: 0.164107:  95%|█████████▌| 19/20 [1:19:57<04:14, 254.32s/it]

[I 2026-08-20 07:27:09,652] Trial 18 finished with value: 0.17335169751341584 and parameters: {'iterations': 652, 'depth': 7, 'learning_rate': 0.05497281078266749, 'l2_leaf_reg': 1.1101621075073542, 'random_strength': 1.5485038985835824, 'bagging_temperature': 4.155551653405512, 'border_count': 181}. Best is trial 13 with value: 0.16410703780268407.

Best trial: 19. Best value: 0.160267: 100%|██████████| 20/20 [1:25:18<00:00, 255.94s/it]
[I 2026-08-20 07:32:31,163] A new study created in memory with name: catboost_msl_hpa

[I 2026-08-20 07:32:31,151] Trial 19 finished with value: 0.16026734157521907 and parameters: {'iterations': 610, 'depth': 9, 'learning_rate': 0.1397521505461672, 'l2_leaf_reg': 3.857508827545883, 'random_strength': 3.594856612442334, 'bagging_temperature': 4.984536926450357, 'border_count': 222}. Best is trial 19 with value: 0.16026734157521907.
Najbolji MAE za sst_c: 0.1603
Najbolji parametri: {'iterations': 610, 'depth': 9, 'learning_rate': 0.1397521505461672, 'l2_leaf_reg': 3.857508827545883, 'random_strength': 3.594856612442334, 'bagging_temperature': 4.984536926450357, 'border_count': 222}

===== OPTUNA CATBOOST: msl_hpa =====

Best trial: 0. Best value: 1.46625:   5%|▌         | 1/20 [16:35<5:15:07, 995.14s/it]

[I 2026-08-20 07:49:06,302] Trial 0 finished with value: 1.466245312018207 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  10%|█         | 2/20 [26:14<3:45:14, 750.80s/it]

[I 2026-08-20 07:58:46,057] Trial 1 finished with value: 1.5185097452461742 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  15%|█▌        | 3/20 [29:18<2:19:18, 491.66s/it]

[I 2026-08-20 08:01:49,345] Trial 2 finished with value: 1.9575360730975546 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  20%|██        | 4/20 [32:26<1:39:11, 371.96s/it]

[I 2026-08-20 08:04:57,815] Trial 3 finished with value: 1.9147652121913175 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  25%|██▌       | 5/20 [37:17<1:25:38, 342.55s/it]

[I 2026-08-20 08:09:48,201] Trial 4 finished with value: 1.7901336322353305 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  30%|███       | 6/20 [44:40<1:27:58, 377.01s/it]

[I 2026-08-20 08:17:12,103] Trial 5 finished with value: 1.8832881447174898 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  35%|███▌      | 7/20 [54:44<1:37:44, 451.13s/it]

[I 2026-08-20 08:27:15,830] Trial 6 finished with value: 1.9007862632738286 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  40%|████      | 8/20 [1:11:19<2:04:51, 624.29s/it]

[I 2026-08-20 08:43:50,904] Trial 7 finished with value: 1.5301447706789688 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  45%|████▌     | 9/20 [1:13:55<1:27:36, 477.83s/it]

[I 2026-08-20 08:46:26,688] Trial 8 finished with value: 2.284832869061969 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 1.466245312018207.

Best trial: 0. Best value: 1.46625:  50%|█████     | 10/20 [1:17:58<1:07:32, 405.25s/it]

[I 2026-08-20 08:50:29,426] Trial 9 finished with value: 1.810701196130063 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 1.466245312018207.

Best trial: 10. Best value: 1.46428:  55%|█████▌    | 11/20 [1:24:48<1:01:00, 406.72s/it]

[I 2026-08-20 08:57:19,463] Trial 10 finished with value: 1.4642796604494213 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 10 with value: 1.4642796604494213.

Best trial: 11. Best value: 1.44798:  60%|██████    | 12/20 [1:31:31<54:05, 405.65s/it]

[I 2026-08-20 09:04:02,685] Trial 11 finished with value: 1.4479779998763154 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 11 with value: 1.4479779998763154.

Best trial: 12. Best value: 1.42308:  65%|██████▌   | 13/20 [1:38:57<48:44, 417.83s/it]

[I 2026-08-20 09:11:28,526] Trial 12 finished with value: 1.4230809867566558 and parameters: {'iterations': 561, 'depth': 8, 'learning_rate': 0.14806829550654302, 'l2_leaf_reg': 19.940224979684842, 'random_strength': 0.021839605740445828, 'bagging_temperature': 2.5675169732221743, 'border_count': 42}. Best is trial 12 with value: 1.4230809867566558.

Best trial: 13. Best value: 1.40703:  70%|███████   | 14/20 [1:47:13<44:09, 441.58s/it]

[I 2026-08-20 09:19:44,988] Trial 13 finished with value: 1.4070282479614142 and parameters: {'iterations': 614, 'depth': 8, 'learning_rate': 0.13374547345150395, 'l2_leaf_reg': 19.506872259628537, 'random_strength': 1.1297302842162695, 'bagging_temperature': 2.1011856638676134, 'border_count': 82}. Best is trial 13 with value: 1.4070282479614142.

Best trial: 13. Best value: 1.40703:  75%|███████▌  | 15/20 [1:54:24<36:30, 438.15s/it]

[I 2026-08-20 09:26:55,189] Trial 14 finished with value: 1.5354731487948121 and parameters: {'iterations': 591, 'depth': 7, 'learning_rate': 0.1059747491980272, 'l2_leaf_reg': 11.75453580623124, 'random_strength': 1.123366282341044, 'bagging_temperature': 3.377513444172112, 'border_count': 84}. Best is trial 13 with value: 1.4070282479614142.

Best trial: 15. Best value: 1.29655:  80%|████████  | 16/20 [2:06:17<34:44, 521.06s/it]

[I 2026-08-20 09:38:48,794] Trial 15 finished with value: 1.2965528831984074 and parameters: {'iterations': 798, 'depth': 9, 'learning_rate': 0.1062956360115325, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 0.9796449427592271, 'bagging_temperature': 1.9245060195465353, 'border_count': 89}. Best is trial 15 with value: 1.2965528831984074.

Best trial: 15. Best value: 1.29655:  85%|████████▌ | 17/20 [2:18:11<28:56, 578.98s/it]

[I 2026-08-20 09:50:42,480] Trial 16 finished with value: 1.3375331444422782 and parameters: {'iterations': 788, 'depth': 9, 'learning_rate': 0.09224657392762665, 'l2_leaf_reg': 11.202829251175123, 'random_strength': 2.8978302473303232, 'bagging_temperature': 1.9581008433319194, 'border_count': 108}. Best is trial 15 with value: 1.2965528831984074.

Best trial: 15. Best value: 1.29655:  90%|█████████ | 18/20 [2:30:08<20:41, 620.51s/it]

[I 2026-08-20 10:02:39,665] Trial 17 finished with value: 1.5244366234883946 and parameters: {'iterations': 784, 'depth': 9, 'learning_rate': 0.040794449153959626, 'l2_leaf_reg': 10.871084492969754, 'random_strength': 2.961145211860833, 'bagging_temperature': 1.8172576110886662, 'border_count': 113}. Best is trial 15 with value: 1.2965528831984074.

Best trial: 15. Best value: 1.29655:  95%|█████████▌| 19/20 [2:42:08<10:50, 650.48s/it]

[I 2026-08-20 10:14:39,974] Trial 18 finished with value: 1.3261824789125407 and parameters: {'iterations': 795, 'depth': 9, 'learning_rate': 0.09679628265674893, 'l2_leaf_reg': 10.4496792834541, 'random_strength': 2.9763909607377075, 'bagging_temperature': 3.535972392831755, 'border_count': 112}. Best is trial 15 with value: 1.2965528831984074.

Best trial: 15. Best value: 1.29655: 100%|██████████| 20/20 [2:52:52<00:00, 518.62s/it]
[I 2026-08-20 10:25:23,539] A new study created in memory with name: catboost_tcc

[I 2026-08-20 10:25:23,523] Trial 19 finished with value: 1.4714140746263837 and parameters: {'iterations': 693, 'depth': 9, 'learning_rate': 0.05783455186304768, 'l2_leaf_reg': 9.20192600368145, 'random_strength': 3.132394567758081, 'bagging_temperature': 3.9244582911455534, 'border_count': 182}. Best is trial 15 with value: 1.2965528831984074.
Najbolji MAE za msl_hpa: 1.2966
Najbolji parametri: {'iterations': 798, 'depth': 9, 'learning_rate': 0.1062956360115325, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 0.9796449427592271, 'bagging_temperature': 1.9245060195465353, 'border_count': 89}

===== OPTUNA CATBOOST: tcc =====

Best trial: 0. Best value: 0.191333:   5%|▌         | 1/20 [16:25<5:12:11, 985.87s/it]

[I 2026-08-20 10:41:49,409] Trial 0 finished with value: 0.1913332675315859 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  10%|█         | 2/20 [26:14<3:45:42, 752.39s/it]

[I 2026-08-20 10:51:38,359] Trial 1 finished with value: 0.19932663722302785 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  15%|█▌        | 3/20 [29:23<2:20:12, 494.82s/it]

[I 2026-08-20 10:54:46,682] Trial 2 finished with value: 0.23313830755559947 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  20%|██        | 4/20 [32:41<1:40:43, 377.70s/it]

[I 2026-08-20 10:58:04,836] Trial 3 finished with value: 0.23067544617368768 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  25%|██▌       | 5/20 [37:27<1:26:11, 344.76s/it]

[I 2026-08-20 11:02:51,189] Trial 4 finished with value: 0.226348275378435 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  30%|███       | 6/20 [44:56<1:28:39, 379.98s/it]

[I 2026-08-20 11:10:19,544] Trial 5 finished with value: 0.22934585095323448 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  35%|███▌      | 7/20 [55:10<1:38:58, 456.80s/it]

[I 2026-08-20 11:20:34,487] Trial 6 finished with value: 0.22405144679816155 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  40%|████      | 8/20 [1:11:51<2:05:58, 629.84s/it]

[I 2026-08-20 11:37:14,847] Trial 7 finished with value: 0.1987949682917984 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  45%|████▌     | 9/20 [1:14:39<1:29:00, 485.52s/it]

[I 2026-08-20 11:40:03,042] Trial 8 finished with value: 0.24031413971980845 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  50%|█████     | 10/20 [1:18:45<1:08:35, 411.56s/it]

[I 2026-08-20 11:44:08,991] Trial 9 finished with value: 0.22705421191454606 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  55%|█████▌    | 11/20 [1:25:37<1:01:45, 411.76s/it]

[I 2026-08-20 11:51:01,185] Trial 10 finished with value: 0.19355274895474905 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  60%|██████    | 12/20 [1:32:15<54:21, 407.64s/it]

[I 2026-08-20 11:57:39,402] Trial 11 finished with value: 0.1930186625290498 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 0. Best value: 0.191333:  65%|██████▌   | 13/20 [1:38:17<45:55, 393.60s/it]

[I 2026-08-20 12:03:40,687] Trial 12 finished with value: 0.19542901548826938 and parameters: {'iterations': 448, 'depth': 8, 'learning_rate': 0.1479499391780178, 'l2_leaf_reg': 10.14619476031968, 'random_strength': 0.9205526856763969, 'bagging_temperature': 1.9379710203198046, 'border_count': 43}. Best is trial 0 with value: 0.1913332675315859.

Best trial: 13. Best value: 0.186363:  70%|███████   | 14/20 [1:47:24<43:59, 439.89s/it]

[I 2026-08-20 12:12:47,548] Trial 13 finished with value: 0.18636262564899084 and parameters: {'iterations': 608, 'depth': 9, 'learning_rate': 0.10186022221074563, 'l2_leaf_reg': 19.228151286480458, 'random_strength': 0.9620327283354857, 'bagging_temperature': 0.09882497202737206, 'border_count': 82}. Best is trial 13 with value: 0.18636262564899084.

Best trial: 13. Best value: 0.186363:  75%|███████▌  | 15/20 [1:56:16<38:58, 467.71s/it]

[I 2026-08-20 12:21:39,721] Trial 14 finished with value: 0.18932938509774744 and parameters: {'iterations': 591, 'depth': 9, 'learning_rate': 0.08965903968031579, 'l2_leaf_reg': 11.000665601179929, 'random_strength': 1.123366282341044, 'bagging_temperature': 0.16166169030530553, 'border_count': 84}. Best is trial 13 with value: 0.18636262564899084.

Best trial: 15. Best value: 0.186226:  80%|████████  | 16/20 [2:05:40<33:06, 496.69s/it]

[I 2026-08-20 12:31:03,734] Trial 15 finished with value: 0.18622587418503547 and parameters: {'iterations': 625, 'depth': 9, 'learning_rate': 0.10151391122373392, 'l2_leaf_reg': 11.358307619279357, 'random_strength': 1.1826866168418348, 'bagging_temperature': 0.15352309006153603, 'border_count': 96}. Best is trial 15 with value: 0.18622587418503547.

Best trial: 16. Best value: 0.183878:  85%|████████▌ | 17/20 [2:15:44<26:27, 529.15s/it]

[I 2026-08-20 12:41:08,371] Trial 16 finished with value: 0.18387837777969737 and parameters: {'iterations': 653, 'depth': 9, 'learning_rate': 0.10339034896178922, 'l2_leaf_reg': 11.495870380984927, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.009194510493302915, 'border_count': 108}. Best is trial 16 with value: 0.18387837777969737.

Best trial: 16. Best value: 0.183878:  90%|█████████ | 18/20 [2:27:22<19:19, 579.77s/it]

[I 2026-08-20 12:52:45,958] Trial 17 finished with value: 0.1951271450754277 and parameters: {'iterations': 763, 'depth': 9, 'learning_rate': 0.04976101132363162, 'l2_leaf_reg': 11.586121212633548, 'random_strength': 2.997509191284597, 'bagging_temperature': 0.023700598265448125, 'border_count': 116}. Best is trial 16 with value: 0.18387837777969737.

Best trial: 16. Best value: 0.183878:  95%|█████████▌| 19/20 [2:35:25<09:10, 550.78s/it]

[I 2026-08-20 13:00:49,203] Trial 18 finished with value: 0.20166147544764684 and parameters: {'iterations': 664, 'depth': 7, 'learning_rate': 0.10427336638663956, 'l2_leaf_reg': 13.135005936265685, 'random_strength': 2.9138716554456425, 'bagging_temperature': 1.2854764348675227, 'border_count': 112}. Best is trial 16 with value: 0.18387837777969737.

Best trial: 16. Best value: 0.183878: 100%|██████████| 20/20 [2:47:42<00:00, 503.14s/it]
[I 2026-08-20 13:13:06,383] A new study created in memory with name: catboost_cape

[I 2026-08-20 13:13:06,366] Trial 19 finished with value: 0.201561235871433 and parameters: {'iterations': 785, 'depth': 9, 'learning_rate': 0.037843711931659606, 'l2_leaf_reg': 8.416254361541025, 'random_strength': 3.132394567758081, 'bagging_temperature': 1.8867207567360107, 'border_count': 178}. Best is trial 16 with value: 0.18387837777969737.
Najbolji MAE za tcc: 0.1839
Najbolji parametri: {'iterations': 653, 'depth': 9, 'learning_rate': 0.10339034896178922, 'l2_leaf_reg': 11.495870380984927, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.009194510493302915, 'border_count': 108}

===== OPTUNA CATBOOST: cape =====

Best trial: 0. Best value: 87.8906:   5%|▌         | 1/20 [16:36<5:15:29, 996.31s/it]

[I 2026-08-20 13:29:42,693] Trial 0 finished with value: 87.89059187703725 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  10%|█         | 2/20 [26:56<3:52:32, 775.15s/it]

[I 2026-08-20 13:40:03,029] Trial 1 finished with value: 89.54981632096238 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  15%|█▌        | 3/20 [30:37<2:27:57, 522.20s/it]

[I 2026-08-20 13:43:44,214] Trial 2 finished with value: 101.07404824243613 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  20%|██        | 4/20 [34:25<1:48:16, 406.02s/it]

[I 2026-08-20 13:47:32,136] Trial 3 finished with value: 99.9049598958898 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  25%|██▌       | 5/20 [36:16<1:14:54, 299.66s/it]

[I 2026-08-20 13:49:23,220] Trial 4 finished with value: 101.75223846730071 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  30%|███       | 6/20 [45:15<1:28:52, 380.92s/it]

[I 2026-08-20 13:58:21,885] Trial 5 finished with value: 99.72521424153797 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  35%|███▌      | 7/20 [56:18<1:42:32, 473.26s/it]

[I 2026-08-20 14:09:25,252] Trial 6 finished with value: 96.66804733418162 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  40%|████      | 8/20 [1:13:15<2:09:15, 646.32s/it]

[I 2026-08-20 14:26:22,119] Trial 7 finished with value: 89.64314506337206 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  45%|████▌     | 9/20 [1:16:22<1:32:08, 502.61s/it]

[I 2026-08-20 14:29:28,721] Trial 8 finished with value: 101.32931053345905 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  50%|█████     | 10/20 [1:21:04<1:12:25, 434.51s/it]

[I 2026-08-20 14:34:10,753] Trial 9 finished with value: 98.89738546435012 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  55%|█████▌    | 11/20 [1:28:23<1:05:23, 435.93s/it]

[I 2026-08-20 14:41:29,912] Trial 10 finished with value: 87.90355481924372 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 0 with value: 87.89059187703725.

Best trial: 0. Best value: 87.8906:  60%|██████    | 12/20 [1:32:19<49:59, 374.97s/it]

[I 2026-08-20 14:45:25,445] Trial 11 finished with value: 97.73244052014066 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 0 with value: 87.89059187703725.

Best trial: 12. Best value: 86.628:  65%|██████▌   | 13/20 [1:40:21<47:32, 407.44s/it]

[I 2026-08-20 14:53:27,612] Trial 12 finished with value: 86.62804874257654 and parameters: {'iterations': 574, 'depth': 8, 'learning_rate': 0.14788557091109908, 'l2_leaf_reg': 10.48947540877023, 'random_strength': 0.9205526856763969, 'bagging_temperature': 3.6317336069528454, 'border_count': 43}. Best is trial 12 with value: 86.62804874257654.

Best trial: 13. Best value: 84.4886:  70%|███████   | 14/20 [1:50:17<46:26, 464.49s/it]

[I 2026-08-20 15:03:23,919] Trial 13 finished with value: 84.48862209145567 and parameters: {'iterations': 614, 'depth': 9, 'learning_rate': 0.10202622710139575, 'l2_leaf_reg': 9.902153978789478, 'random_strength': 0.9645031021160144, 'bagging_temperature': 3.709534768848698, 'border_count': 82}. Best is trial 13 with value: 84.48862209145567.

Best trial: 13. Best value: 84.4886:  75%|███████▌  | 15/20 [1:59:49<41:24, 496.96s/it]

[I 2026-08-20 15:12:56,118] Trial 14 finished with value: 85.6215120866852 and parameters: {'iterations': 591, 'depth': 9, 'learning_rate': 0.1059747491980272, 'l2_leaf_reg': 10.929717419536411, 'random_strength': 1.1919549144267383, 'bagging_temperature': 3.5883387030832017, 'border_count': 84}. Best is trial 13 with value: 84.48862209145567.

Best trial: 15. Best value: 83.6535:  80%|████████  | 16/20 [2:12:40<38:37, 579.32s/it]

[I 2026-08-20 15:25:46,703] Trial 15 finished with value: 83.65353198068327 and parameters: {'iterations': 798, 'depth': 9, 'learning_rate': 0.09908558865322166, 'l2_leaf_reg': 11.147576110906208, 'random_strength': 1.1841228456621833, 'bagging_temperature': 3.627725258791, 'border_count': 96}. Best is trial 15 with value: 83.65353198068327.

Best trial: 15. Best value: 83.6535:  85%|████████▌ | 17/20 [2:25:21<31:42, 634.00s/it]

[I 2026-08-20 15:38:27,885] Trial 16 finished with value: 83.78574422190947 and parameters: {'iterations': 788, 'depth': 9, 'learning_rate': 0.09224657392762665, 'l2_leaf_reg': 11.386244424662829, 'random_strength': 2.8978302473303232, 'bagging_temperature': 4.846349260243589, 'border_count': 108}. Best is trial 15 with value: 83.65353198068327.

Best trial: 15. Best value: 83.6535:  90%|█████████ | 18/20 [2:38:21<22:35, 677.83s/it]

[I 2026-08-20 15:51:27,738] Trial 17 finished with value: 87.9645435721537 and parameters: {'iterations': 784, 'depth': 9, 'learning_rate': 0.04892358725548343, 'l2_leaf_reg': 13.076189648682561, 'random_strength': 2.997509191284597, 'bagging_temperature': 4.843310544157647, 'border_count': 116}. Best is trial 15 with value: 83.65353198068327.

Best trial: 15. Best value: 83.6535:  95%|█████████▌| 19/20 [2:49:02<11:06, 666.77s/it]

[I 2026-08-20 16:02:08,733] Trial 18 finished with value: 93.44095099356838 and parameters: {'iterations': 795, 'depth': 7, 'learning_rate': 0.03647259601158662, 'l2_leaf_reg': 4.692115969815976, 'random_strength': 2.9134414148622776, 'bagging_temperature': 4.274442800872379, 'border_count': 112}. Best is trial 15 with value: 83.65353198068327.

Best trial: 15. Best value: 83.6535: 100%|██████████| 20/20 [3:00:37<00:00, 541.88s/it]
[I 2026-08-20 16:13:43,945] A new study created in memory with name: catboost_blh

[I 2026-08-20 16:13:43,931] Trial 19 finished with value: 84.90849345245687 and parameters: {'iterations': 690, 'depth': 9, 'learning_rate': 0.09368551717617225, 'l2_leaf_reg': 7.836720132882362, 'random_strength': 3.132394567758081, 'bagging_temperature': 4.995118789649482, 'border_count': 178}. Best is trial 15 with value: 83.65353198068327.
Najbolji MAE za cape: 83.6535
Najbolji parametri: {'iterations': 798, 'depth': 9, 'learning_rate': 0.09908558865322166, 'l2_leaf_reg': 11.147576110906208, 'random_strength': 1.1841228456621833, 'bagging_temperature': 3.627725258791, 'border_count': 96}

===== OPTUNA CATBOOST: blh =====

Best trial: 0. Best value: 165.019:   5%|▌         | 1/20 [16:30<5:13:32, 990.14s/it]

[I 2026-08-20 16:30:14,086] Trial 0 finished with value: 165.01859758606483 and parameters: {'iterations': 425, 'depth': 10, 'learning_rate': 0.07259248719561363, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.7800932022121826, 'bagging_temperature': 0.7799726016810132, 'border_count': 45}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  10%|█         | 2/20 [26:13<3:45:17, 750.99s/it]

[I 2026-08-20 16:39:57,664] Trial 1 finished with value: 169.8564242257291 and parameters: {'iterations': 720, 'depth': 8, 'learning_rate': 0.06803900745073706, 'l2_leaf_reg': 1.0636066512540283, 'random_strength': 4.8495492608099715, 'bagging_temperature': 4.162213204002109, 'border_count': 79}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  15%|█▌        | 3/20 [29:27<2:20:44, 496.76s/it]

[I 2026-08-20 16:43:11,903] Trial 2 finished with value: 215.5897877355423 and parameters: {'iterations': 309, 'depth': 5, 'learning_rate': 0.02279379523765072, 'l2_leaf_reg': 4.816414530907083, 'random_strength': 2.1597250932105787, 'bagging_temperature': 1.4561457009902097, 'border_count': 169}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  20%|██        | 4/20 [32:46<1:41:07, 379.22s/it]

[I 2026-08-20 16:46:30,923] Trial 3 finished with value: 207.34493677874377 and parameters: {'iterations': 283, 'depth': 6, 'learning_rate': 0.026969628335735185, 'l2_leaf_reg': 3.920673972242136, 'random_strength': 3.925879806965068, 'bagging_temperature': 0.9983689107917987, 'border_count': 147}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  25%|██▌       | 5/20 [37:45<1:27:33, 350.24s/it]

[I 2026-08-20 16:51:29,789] Trial 4 finished with value: 201.3073222465452 and parameters: {'iterations': 556, 'depth': 4, 'learning_rate': 0.05182367293641893, 'l2_leaf_reg': 1.6666983286066417, 'random_strength': 0.3252579649263976, 'bagging_temperature': 4.7444276862666666, 'border_count': 248}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  30%|███       | 6/20 [45:30<1:30:49, 389.25s/it]

[I 2026-08-20 16:59:14,773] Trial 5 finished with value: 203.44798824707146 and parameters: {'iterations': 685, 'depth': 6, 'learning_rate': 0.01302780710309028, 'l2_leaf_reg': 7.766184280392884, 'random_strength': 2.2007624686980067, 'bagging_temperature': 0.6101911742238941, 'border_count': 142}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  35%|███▌      | 7/20 [55:51<1:40:44, 464.98s/it]

[I 2026-08-20 17:09:35,654] Trial 6 finished with value: 196.61594416473255 and parameters: {'iterations': 220, 'depth': 10, 'learning_rate': 0.020153425505297702, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 1.5585553804470549, 'bagging_temperature': 2.600340105889054, 'border_count': 154}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  40%|████      | 8/20 [1:12:54<2:08:30, 642.54s/it]

[I 2026-08-20 17:26:38,376] Trial 7 finished with value: 171.00914844470554 and parameters: {'iterations': 311, 'depth': 10, 'learning_rate': 0.08158812228791566, 'l2_leaf_reg': 16.684619386293466, 'random_strength': 4.474136752138244, 'bagging_temperature': 2.9894998940554256, 'border_count': 238}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  45%|████▌     | 9/20 [1:15:40<1:30:30, 493.68s/it]

[I 2026-08-20 17:29:24,757] Trial 8 finished with value: 245.62583757425003 and parameters: {'iterations': 253, 'depth': 5, 'learning_rate': 0.011302939920362371, 'l2_leaf_reg': 2.6501137707458966, 'random_strength': 1.9433864484474102, 'bagging_temperature': 1.3567451588694794, 'border_count': 217}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  50%|█████     | 10/20 [1:19:58<1:10:09, 420.98s/it]

[I 2026-08-20 17:33:42,926] Trial 9 finished with value: 201.22440801255138 and parameters: {'iterations': 414, 'depth': 5, 'learning_rate': 0.043477055106943, 'l2_leaf_reg': 1.5252697030515172, 'random_strength': 4.010984903770199, 'bagging_temperature': 0.3727532183988541, 'border_count': 253}. Best is trial 0 with value: 165.01859758606483.

Best trial: 0. Best value: 165.019:  55%|█████▌    | 11/20 [1:26:55<1:02:57, 419.74s/it]

[I 2026-08-20 17:40:39,873] Trial 10 finished with value: 165.231452322866 and parameters: {'iterations': 508, 'depth': 8, 'learning_rate': 0.13812240169527848, 'l2_leaf_reg': 16.328176997790177, 'random_strength': 0.10825072815466619, 'bagging_temperature': 2.7047195408777394, 'border_count': 35}. Best is trial 0 with value: 165.01859758606483.

Best trial: 11. Best value: 164.752:  60%|██████    | 12/20 [1:33:39<55:18, 414.78s/it]

[I 2026-08-20 17:47:23,286] Trial 11 finished with value: 164.75218518921915 and parameters: {'iterations': 492, 'depth': 8, 'learning_rate': 0.1490143436468726, 'l2_leaf_reg': 19.62814923202026, 'random_strength': 0.04020610389289636, 'bagging_temperature': 2.3117229321082267, 'border_count': 38}. Best is trial 11 with value: 164.75218518921915.

Best trial: 11. Best value: 164.752:  65%|██████▌   | 13/20 [1:39:42<46:33, 399.02s/it]

[I 2026-08-20 17:53:26,066] Trial 12 finished with value: 166.40332108389123 and parameters: {'iterations': 448, 'depth': 8, 'learning_rate': 0.1479499391780178, 'l2_leaf_reg': 10.14619476031968, 'random_strength': 0.9205526856763969, 'bagging_temperature': 1.9379710203198046, 'border_count': 43}. Best is trial 11 with value: 164.75218518921915.

Best trial: 13. Best value: 160.374:  70%|███████   | 14/20 [1:49:02<44:45, 447.63s/it]

[I 2026-08-20 18:02:46,009] Trial 13 finished with value: 160.37382344782785 and parameters: {'iterations': 608, 'depth': 9, 'learning_rate': 0.10186022221074563, 'l2_leaf_reg': 19.228151286480458, 'random_strength': 0.9620327283354857, 'bagging_temperature': 0.09882497202737206, 'border_count': 82}. Best is trial 13 with value: 160.37382344782785.

Best trial: 13. Best value: 160.374:  75%|███████▌  | 15/20 [1:57:55<39:27, 473.44s/it]

[I 2026-08-20 18:11:39,282] Trial 14 finished with value: 160.82602925468186 and parameters: {'iterations': 591, 'depth': 9, 'learning_rate': 0.1059747491980272, 'l2_leaf_reg': 19.148419680711537, 'random_strength': 1.1905139977437826, 'bagging_temperature': 3.5196547975775747, 'border_count': 84}. Best is trial 13 with value: 160.37382344782785.

Best trial: 13. Best value: 160.374:  80%|████████  | 16/20 [2:07:25<33:29, 502.42s/it]

[I 2026-08-20 18:21:08,978] Trial 15 finished with value: 160.62411012715805 and parameters: {'iterations': 625, 'depth': 9, 'learning_rate': 0.09908558865322166, 'l2_leaf_reg': 11.254291229660394, 'random_strength': 1.1826866168418348, 'bagging_temperature': 3.3746491352347054, 'border_count': 96}. Best is trial 13 with value: 160.37382344782785.

Best trial: 13. Best value: 160.374:  85%|████████▌ | 17/20 [2:17:24<26:34, 531.59s/it]

[I 2026-08-20 18:31:08,403] Trial 16 finished with value: 161.06736392243474 and parameters: {'iterations': 653, 'depth': 9, 'learning_rate': 0.09224657392762665, 'l2_leaf_reg': 11.3252418316757, 'random_strength': 2.8978302473303232, 'bagging_temperature': 0.020113408260667695, 'border_count': 108}. Best is trial 13 with value: 160.37382344782785.

Best trial: 13. Best value: 160.374:  90%|█████████ | 18/20 [2:28:53<19:17, 578.98s/it]

[I 2026-08-20 18:42:37,720] Trial 17 finished with value: 168.1396170893137 and parameters: {'iterations': 754, 'depth': 9, 'learning_rate': 0.04987906352494948, 'l2_leaf_reg': 11.89094754861287, 'random_strength': 2.912554411220168, 'bagging_temperature': 3.529694011819126, 'border_count': 108}. Best is trial 13 with value: 160.37382344782785.

Best trial: 13. Best value: 160.374:  95%|█████████▌| 19/20 [2:38:34<09:39, 579.44s/it]

[I 2026-08-20 18:52:18,211] Trial 18 finished with value: 181.90049996400145 and parameters: {'iterations': 785, 'depth': 7, 'learning_rate': 0.03647259601158662, 'l2_leaf_reg': 13.135005936265685, 'random_strength': 1.5485038985835824, 'bagging_temperature': 4.771934306012034, 'border_count': 78}. Best is trial 13 with value: 160.37382344782785.

Best trial: 13. Best value: 160.374: 100%|██████████| 20/20 [2:48:14<00:00, 504.72s/it]

[I 2026-08-20 19:01:58,279] Trial 19 finished with value: 161.51812811743042 and parameters: {'iterations': 623, 'depth': 9, 'learning_rate': 0.09685089405201269, 'l2_leaf_reg': 8.303151209589027, 'random_strength': 2.7029681440684916, 'bagging_temperature': 1.8867207567360107, 'border_count': 120}. Best is trial 13 with value: 160.37382344782785.
Najbolji MAE za blh: 160.3738
Najbolji parametri: {'iterations': 608, 'depth': 9, 'learning_rate': 0.10186022221074563, 'l2_leaf_reg': 19.228151286480458, 'random_strength': 0.9620327283354857, 'bagging_temperature': 0.09882497202737206, 'border_count': 82}

In [26]:
optuna_df = pd.DataFrame(
    optuna_results
)

optuna_df.to_csv(
    'catboost_optuna_svi_targeti.csv',
    index=False
)

print(
    'Spremljeno u: '
    'catboost_optuna_svi_targeti.csv'
)

display(optuna_df)

Spremljeno u: catboost_optuna_svi_targeti.csv

,model,target,best_MAE_optuna,n_trials,iterations,depth,learning_rate,l2_leaf_reg,random_strength,bagging_temperature,border_count
0,CatBoost,t2m_c,1.262965,20,798,9,0.106296,11.254291,0.979645,1.904714,89
1,CatBoost,wind_speed_ms,0.662476,20,653,9,0.103390,11.495870,2.897830,0.009195,108
2,CatBoost,swh,0.101437,20,625,9,0.101514,11.358308,1.182687,0.153523,96
3,CatBoost,mwp,0.240499,20,798,9,0.106255,11.254291,2.556037,3.637362,89
4,CatBoost,mwd,42.269304,20,625,9,0.101514,11.358308,1.182687,0.153523,96
5,CatBoost,sst_c,0.160267,20,610,9,0.139752,3.857509,3.594857,4.984537,222
6,CatBoost,msl_hpa,1.296553,20,798,9,0.106296,11.254291,0.979645,1.924506,89
7,CatBoost,tcc,0.183878,20,653,9,0.103390,11.495870,2.897830,0.009195,108
8,CatBoost,cape,83.653532,20,798,9,0.099086,11.147576,1.184123,3.627725,96
9,CatBoost,blh,160.373823,20,608,9,0.101860,19.228151,0.962033,0.098825,82