# Meteo prognoza — LightGBM 

Ova bilježnica koristi isti memorijski štedljiv pipeline kao prethodna verzija, ali omogućuje treniranje  modela `LightGBM`

## 1. Importi i konfiguracija

In [1]:
!pip install lightgbm
!pip install optuna optuna-integration

Requirement already satisfied: lightgbm in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (4.7.0)
Requirement already satisfied: narwhals>=1.15 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (2.24.0)
Requirement already satisfied: numpy>=1.21.3 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (2.2.6)
Requirement already satisfied: scipy in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (1.16.3)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: optuna in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (4.9.0)
Requirement already satisfied: optuna-integration in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\korisnik\appdata\roaming\python\python313\site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: colorama in c:\users\korisnik\appdata\roaming\python\python313\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Ako nedostaju paketi, pokreni: %pip install lightgbm xgboost
import gc
import pandas as pd
import numpy as np
import lightgbm as lgb
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import optuna
from optuna.pruners import MedianPruner
from optuna_integration.lightgbm import LightGBMPruningCallback

MODEL_NAME = 'LightGBM'

RANDOM_STATE = 42
HORIZONT = 12
VALIDATION_FRACTION = 0.10
BUFFER_STUPNJEVI = 0.3
CSV_PATH = 'ERA5_SPOJENO_2015_2023.csv'
OUTPUT_RESULTS = f'{MODEL_NAME.lower()}_rezultati_po_targetu.csv'

LAT_PULA, LON_PULA = 44.8666, 13.8496
LAT_RIJEKA, LON_RIJEKA = 45.3271, 14.4422

TARGETS = ['t2m_c', 'wind_speed_ms', 'swh', 'mwp', 'mwd', 'sst_c', 'msl_hpa', 'tcc', 'cape', 'blh']
LAG_VARS = ['t2m_c', 'msl_hpa', 'wind_speed_ms', 'tcc', 'cape']

# Ako nedostaje RAM-a, postavi npr. 300_000.
MAX_TRAIN_ROWS = None

## 2. Učitavanje podataka

In [5]:
df = pd.read_csv(CSV_PATH)
df['valid_time'] = pd.to_datetime(df['valid_time'])
df = df.sort_values(['latitude', 'longitude', 'valid_time']).reset_index(drop=True)

print(f'Ukupno redaka: {len(df):,}')
print(f'Broj stupaca: {df.shape[1]}')
print(f'Broj lokacija: {df[["latitude", "longitude"]].drop_duplicates().shape[0]}')
print(f'Period: {df["valid_time"].min()} do {df["valid_time"].max()}')
print('Duplikati:', df.duplicated(['valid_time', 'latitude', 'longitude']).sum())

Ukupno redaka: 3,367,224
Broj stupaca: 37
Broj lokacija: 42
Period: 2015-01-01 00:00:00 do 2023-12-31 23:00:00
Duplikati: 53928

## 3. Izdvajanje lokacija

In [6]:
locations = df[['latitude', 'longitude']].drop_duplicates().copy()
locations['dist_pula'] = np.sqrt((locations['latitude'] - LAT_PULA)**2 + (locations['longitude'] - LON_PULA)**2)
locations['dist_rijeka'] = np.sqrt((locations['latitude'] - LAT_RIJEKA)**2 + (locations['longitude'] - LON_RIJEKA)**2)
pula_grid = locations.loc[locations['dist_pula'].idxmin(), ['latitude', 'longitude']]
rijeka_grid = locations.loc[locations['dist_rijeka'].idxmin(), ['latitude', 'longitude']]
lat_pula_grid, lon_pula_grid = pula_grid['latitude'], pula_grid['longitude']
lat_rijeka_grid, lon_rijeka_grid = rijeka_grid['latitude'], rijeka_grid['longitude']

df['dist_pula'] = np.sqrt((df['latitude'] - LAT_PULA)**2 + (df['longitude'] - LON_PULA)**2)
df['dist_rijeka'] = np.sqrt((df['latitude'] - LAT_RIJEKA)**2 + (df['longitude'] - LON_RIJEKA)**2)
je_pula = (df['latitude'] == lat_pula_grid) & (df['longitude'] == lon_pula_grid)
je_rijeka = (df['latitude'] == lat_rijeka_grid) & (df['longitude'] == lon_rijeka_grid)
blizu = (df['dist_pula'] < BUFFER_STUPNJEVI) | (df['dist_rijeka'] < BUFFER_STUPNJEVI)

df_pula = df.loc[je_pula].copy()
df_rijeka = df.loc[je_rijeka].copy()
df_train = df.loc[~je_pula & ~je_rijeka & ~blizu].copy()

if MAX_TRAIN_ROWS is not None and len(df_train) > MAX_TRAIN_ROWS:
    df_train = df_train.sort_values(['valid_time', 'latitude', 'longitude']).iloc[:MAX_TRAIN_ROWS].copy()

print(f'Pula: {len(df_pula):,}')
print(f'Rijeka: {len(df_rijeka):,}')
print(f'Trening: {len(df_train):,}')
del locations
gc.collect()

Pula: 80,172
Rijeka: 80,172
Trening: 2,725,848

2132

## 4. Feature engineering

In [7]:
def add_features(data):
    data = data.sort_values(['latitude', 'longitude', 'valid_time']).copy()
    groups = data.groupby(['latitude', 'longitude'])

    for var in LAG_VARS:
        if var not in data.columns:
            continue
        data[f'{var}_lag3h'] = groups[var].shift(3)
        data[f'{var}_lag6h'] = groups[var].shift(6)
        data[f'{var}_trend3h'] = data[var] - data[f'{var}_lag3h']
        data[f'{var}_rolling6h_mean'] = groups[var].transform(lambda s: s.rolling(6, min_periods=1).mean())

    if 'wind_dir_deg' in data.columns:
        data['wind_dir_sin'] = np.sin(np.radians(data['wind_dir_deg']))
        data['wind_dir_cos'] = np.cos(np.radians(data['wind_dir_deg']))

    hour = data['valid_time'].dt.hour
    day = data['valid_time'].dt.dayofyear
    data['hour_sin'] = np.sin(2 * np.pi * hour / 24)
    data['hour_cos'] = np.cos(2 * np.pi * hour / 24)
    data['day_sin'] = np.sin(2 * np.pi * day / 365.25)
    data['day_cos'] = np.cos(2 * np.pi * day / 365.25)

    if {'t2m_c', 'd2m_c'}.issubset(data.columns):
        data['temp_dewpoint_diff'] = data['t2m_c'] - data['d2m_c']
    if 'msl_hpa' in data.columns:
        data['pressure_gradient'] = groups['msl_hpa'].diff()
    return data

df_train = add_features(df_train)
df_pula = add_features(df_pula)
df_rijeka = add_features(df_rijeka)
print('Broj stupaca nakon feature engineeringa:', df_train.shape[1])

Broj stupaca nakon feature engineeringa: 67

## 5. Future targeti

In [8]:
def add_future_targets(data):
    data = data.sort_values(['latitude', 'longitude', 'valid_time']).copy()
    groups = data.groupby(['latitude', 'longitude'])
    for target in TARGETS:
        if target in data.columns:
            data[f'{target}_future'] = groups[target].shift(-HORIZONT)
    return data

df_train = add_future_targets(df_train)
df_pula = add_future_targets(df_pula)
df_rijeka = add_future_targets(df_rijeka)
for target in TARGETS:
    col = f'{target}_future'
    if col in df_train.columns:
        print(f'{target}: {df_train[col].notna().sum():,} valjanih targeta')

t2m_c: 2,681,784 valjanih targeta
wind_speed_ms: 2,681,784 valjanih targeta
swh: 631,008 valjanih targeta
mwp: 631,008 valjanih targeta
mwd: 631,008 valjanih targeta
sst_c: 1,340,892 valjanih targeta
msl_hpa: 2,681,784 valjanih targeta
tcc: 2,681,784 valjanih targeta
cape: 2,681,784 valjanih targeta
blh: 2,681,784 valjanih targeta

## 6. Priprema featurea i model

In [ ]:
DROP_COLUMNS = ['valid_time', 'latitude', 'longitude', 'dist_pula', 'dist_rijeka', 'hour', 'day']

def prepare_X(data, feature_names=None, medians=None):
    drop_cols = [c for c in DROP_COLUMNS if c in data.columns]
    drop_cols += [c for c in data.columns if c.endswith('_future')]
    numeric_cols = data.select_dtypes(include=[np.number]).columns
    selected_cols = [c for c in numeric_cols if c not in drop_cols]

    if feature_names is not None:
        selected_cols = [c for c in feature_names if c in data.columns]

    X = data.loc[:, selected_cols].copy()
    X = X.replace([np.inf, -np.inf], np.nan)
    if medians is None:
        medians = X.median()
    X = X.fillna(medians)

    if feature_names is not None:
        X = X.reindex(columns=feature_names, fill_value=0)

    X = X.astype(np.float32)
    medians = medians.astype(np.float32)
    return X, medians

def make_model(name):
    if name == 'LightGBM':
        return lgb.LGBMRegressor(
            n_estimators=500, learning_rate=0.05, max_depth=10,
            num_leaves=31, min_child_samples=20,
            reg_alpha=0.5, reg_lambda=1.0,
            random_state=RANDOM_STATE, n_jobs=2, verbosity=-1
        )

  

    raise ValueError('MODEL_NAME mora biti LightGBM ')

## 7. Trening jednog targeta

In [10]:
def train_one_target(model_name, target, train_data, test_dict):
    target_col = f'{target}_future'
    if target_col not in train_data.columns:
        print(f'{target}: target ne postoji')
        return None

    valid_idx = train_data[target_col].notna()
    n_valid = int(valid_idx.sum())
    if n_valid < 1000:
        print(f'{target}: preskačem, samo {n_valid} valjanih redaka')
        return None

    target_data = train_data.loc[valid_idx]
    y = target_data[target_col].astype(np.float32)
    X, medians = prepare_X(target_data)
    feature_names = X.columns.tolist()

    cutoff = int(len(X) * (1 - VALIDATION_FRACTION))
    X_fit, X_val = X.iloc[:cutoff], X.iloc[cutoff:]
    y_fit, y_val = y.iloc[:cutoff], y.iloc[cutoff:]

    print(f'{MODEL_NAME}/{target}: treniranje na {len(X_fit):,} redaka i {len(feature_names)} featurea')
    model = make_model(model_name)
    model.fit(X_fit, y_fit)
    pred_val = model.predict(X_val)

    result = {
        'model': model_name,
        'target': target,
        'horizon_hours': HORIZONT,
        'MAE_val': mean_absolute_error(y_val, pred_val),
        'RMSE_val': np.sqrt(mean_squared_error(y_val, pred_val)),
        'R2_val': r2_score(y_val, pred_val),
        'n_train': len(X_fit),
        'n_validation': len(X_val),
        'n_features': len(feature_names)
    }

    for location, test_data in test_dict.items():
        test_valid_idx = test_data[target_col].notna()
        if test_valid_idx.sum() < 10:
            result[f'MAE_{location}'] = np.nan
            result[f'RMSE_{location}'] = np.nan
            result[f'R2_{location}'] = np.nan
            continue

        test_subset = test_data.loc[test_valid_idx]
        X_test, _ = prepare_X(test_subset, feature_names, medians)
        y_test = test_subset[target_col].astype(np.float32)
        pred_test = model.predict(X_test)
        result[f'MAE_{location}'] = mean_absolute_error(y_test, pred_test)
        result[f'RMSE_{location}'] = np.sqrt(mean_squared_error(y_test, pred_test))
        result[f'R2_{location}'] = r2_score(y_test, pred_test)

    print(f"{target}: MAE={result['MAE_val']:.3f}, RMSE={result['RMSE_val']:.3f}, R2={result['R2_val']:.3f}")
    del target_data, X, X_fit, X_val, y, y_fit, y_val, pred_val, model
    if 'X_test' in locals():
        del X_test
    if 'y_test' in locals():
        del y_test
    if 'pred_test' in locals():
        del pred_test
    gc.collect()
    return result

## 8. Pokretanje odabranog modela

In [ ]:
if MODEL_NAME not in ['LightGBM']:
    raise ValueError('MODEL_NAME mora biti LightGBM ')

test_dict = {'pula': df_pula, 'rijeka': df_rijeka}
results = []

for target in TARGETS:
    result = train_one_target(MODEL_NAME, target, df_train, test_dict)
    if result is not None:
        results.append(result)

results_df = pd.DataFrame(results)
results_df.to_csv(OUTPUT_RESULTS, index=False)
print('\n=== REZULTATI ===')
display(results_df)
print(f'Spremljeno u: {OUTPUT_RESULTS}')

LightGBM/t2m_c: treniranje na 2,413,605 redaka i 62 featurea
t2m_c: MAE=1.405, RMSE=1.847, R2=0.951
LightGBM/wind_speed_ms: treniranje na 2,413,605 redaka i 62 featurea
wind_speed_ms: MAE=0.781, RMSE=0.996, R2=0.369
LightGBM/swh: treniranje na 567,907 redaka i 62 featurea
swh: MAE=0.118, RMSE=0.176, R2=0.681
LightGBM/mwp: treniranje na 567,907 redaka i 62 featurea
mwp: MAE=0.270, RMSE=0.355, R2=0.809
LightGBM/mwd: treniranje na 567,907 redaka i 62 featurea
mwd: MAE=44.415, RMSE=66.726, R2=0.329
LightGBM/sst_c: treniranje na 1,206,802 redaka i 62 featurea
sst_c: MAE=0.148, RMSE=0.264, R2=0.998
LightGBM/msl_hpa: treniranje na 2,413,605 redaka i 62 featurea
msl_hpa: MAE=1.585, RMSE=2.121, R2=0.927
LightGBM/tcc: treniranje na 2,413,605 redaka i 62 featurea
tcc: MAE=0.221, RMSE=0.273, R2=0.481
LightGBM/cape: treniranje na 2,413,605 redaka i 62 featurea
cape: MAE=96.973, RMSE=239.954, R2=0.597
LightGBM/blh: treniranje na 2,413,605 redaka i 62 featurea
blh: MAE=180.918, RMSE=255.667, R2=0.717

=== REZULTATI ===

,model,target,horizon_hours,MAE_val,RMSE_val,R2_val,n_train,n_validation,n_features,MAE_pula,RMSE_pula,R2_pula,MAE_rijeka,RMSE_rijeka,R2_rijeka
0,LightGBM,t2m_c,12,1.404994,1.847128,0.951372,2413605,268179,62,0.671788,0.903237,0.979575,1.040475,1.371684,0.967888
1,LightGBM,wind_speed_ms,12,0.780925,0.995601,0.369184,2413605,268179,62,1.481767,1.937002,0.568562,0.843112,1.108732,0.557465
2,LightGBM,swh,12,0.118167,0.176226,0.681185,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
3,LightGBM,mwp,12,0.270052,0.354822,0.809310,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
4,LightGBM,mwd,12,44.415030,66.726267,0.328806,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
5,LightGBM,sst_c,12,0.148391,0.264187,0.998048,1206802,134090,62,0.091082,0.150091,0.999211,NaN,NaN,NaN
6,LightGBM,msl_hpa,12,1.585445,2.121256,0.927215,2413605,268179,62,1.281886,1.719182,0.949690,1.316545,1.755338,0.946111
7,LightGBM,tcc,12,0.221071,0.272692,0.481340,2413605,268179,62,0.229531,0.278715,0.480468,0.203898,0.253253,0.554137
8,LightGBM,cape,12,96.972651,239.954453,0.597314,2413605,268179,62,147.086739,312.642504,0.804312,92.019671,204.062621,0.647494
9,LightGBM,blh,12,180.917539,255.667144,0.716832,2413605,268179,62,141.328375,197.221083,0.659514,159.183420,224.493577,0.719154

Spremljeno u: lightgbm_rezultati_po_targetu.csv

## 9. optuna za jedan target

In [15]:
# ============================================================
# OPTUNA LIGHTGBM ZA SVE TARGETE
# ============================================================

OPTUNA_TRIALS = 20
OPTUNA_MAX_ROWS = None

def objective_lightgbm(trial, target):
    target_col = f'{target}_future'

    valid_idx = df_train[target_col].notna()
    data = df_train.loc[valid_idx]

    if OPTUNA_MAX_ROWS is not None:
        data = (
            data
            .sort_values(['valid_time', 'latitude', 'longitude'])
            .iloc[:OPTUNA_MAX_ROWS]
        )

    y = data[target_col].astype(np.float32)
    X, medians = prepare_X(data)

    cutoff = int(len(X) * 0.90)

    X_fit = X.iloc[:cutoff]
    X_val = X.iloc[cutoff:]
    y_fit = y.iloc[:cutoff]
    y_val = y.iloc[cutoff:]

    params = {
        'objective': 'regression',
        'metric': 'l1',
        'verbosity': -1,
        'random_state': RANDOM_STATE,
        'n_jobs': 2,

        'n_estimators': trial.suggest_int(
            'n_estimators', 200, 800
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate', 0.01, 0.15, log=True
        ),

        'num_leaves': trial.suggest_int(
            'num_leaves', 15, 127
        ),

        'max_depth': trial.suggest_int(
            'max_depth', 4, 14
        ),

        'min_child_samples': trial.suggest_int(
            'min_child_samples', 10, 100
        ),

        'subsample': trial.suggest_float(
            'subsample', 0.7, 1.0
        ),

        'colsample_bytree': trial.suggest_float(
            'colsample_bytree', 0.6, 1.0
        ),

        'reg_alpha': trial.suggest_float(
            'reg_alpha', 1e-8, 10.0, log=True
        ),

        'reg_lambda': trial.suggest_float(
            'reg_lambda', 1e-8, 10.0, log=True
        )
    }

    model = lgb.LGBMRegressor(**params)

    model.fit(
        X_fit,
        y_fit,
        eval_set=[(X_val, y_val)],
        eval_names=['valid_0'],
        callbacks=[
            lgb.early_stopping(
                stopping_rounds=50,
                verbose=False
            )
        ]
    )

    pred = model.predict(X_val)

    return mean_absolute_error(y_val, pred)

## pokretanje OPtune

In [16]:
# ============================================================
# POKRETANJE OPTUNE ZA SVE TARGETE
# ============================================================

optuna_rezultati = []
optuna_studies = {}

for target in TARGETS:
    print(f'\n===== OPTUNA: {target} =====')

    target_col = f'{target}_future'

    if target_col not in df_train.columns:
        print(f'{target}: target ne postoji, preskačem.')
        continue

    broj_validnih = df_train[target_col].notna().sum()

    if broj_validnih < 1000:
        print(
            f'{target}: premalo validnih podataka '
            f'({broj_validnih}), preskačem.'
        )
        continue

    study = optuna.create_study(
        direction='minimize',
        study_name=f'lightgbm_{target}',
        sampler=optuna.samplers.TPESampler(
            seed=RANDOM_STATE
        ),
        pruner=optuna.pruners.MedianPruner(
            n_startup_trials=5,
            n_warmup_steps=50
        )
    )

    study.optimize(
        lambda trial, current_target=target:
            objective_lightgbm(
                trial,
                current_target
            ),
        n_trials=OPTUNA_TRIALS,
        show_progress_bar=True
    )

    optuna_studies[target] = study

    najbolji_red = {
        'model': 'LightGBM',
        'target': target,
        'best_MAE': study.best_value,
        'n_trials': len(study.trials),
        **study.best_params
    }

    optuna_rezultati.append(najbolji_red)

    print(f'Najbolji MAE za {target}: {study.best_value:.4f}')
    print('Najbolji parametri:')
    print(study.best_params)

optuna_df = pd.DataFrame(optuna_rezultati)

optuna_df.to_csv(
    'optuna_lightgbm_svi_targeti.csv',
    index=False
)

print('\n=== OPTUNA REZULTATI ZA SVE TARGETE ===')
display(optuna_df)

print(
    '\nSpremljeno u: '
    'optuna_lightgbm_svi_targeti.csv'
)

[I 2026-08-19 21:05:32,181] A new study created in memory with name: lightgbm_t2m_c

===== OPTUNA: t2m_c =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:07:10,199] Trial 0 finished with value: 1.1399912519195448 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:11:21,753] Trial 1 finished with value: 1.4089662002186265 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:13:09,596] Trial 2 finished with value: 1.6186106025934293 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:15:16,441] Trial 3 finished with value: 1.4753982994650772 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:17:26,431] Trial 4 finished with value: 1.5311676005681354 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:21:01,768] Trial 5 finished with value: 1.3641696235905578 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:22:42,788] Trial 6 finished with value: 1.3442061623944872 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:24:39,198] Trial 7 finished with value: 1.6454769393934647 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:25:51,607] Trial 8 finished with value: 1.297762006949687 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:28:16,637] Trial 9 finished with value: 1.5517673524748354 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:30:44,438] Trial 10 finished with value: 1.2560086636747905 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:33:13,099] Trial 11 finished with value: 1.2307487210833443 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 1.1399912519195448.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:35:53,227] Trial 12 finished with value: 0.993750571181731 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:37:19,238] Trial 13 finished with value: 1.1452806083281897 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:39:56,483] Trial 14 finished with value: 1.0629387905726138 and parameters: {'n_estimators': 711, 'learning_rate': 0.10215516856364636, 'num_leaves': 109, 'max_depth': 11, 'min_child_samples': 100, 'subsample': 0.9445565374939666, 'colsample_bytree': 0.6808861803604528, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 2.5683275964108445e-05}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:42:36,800] Trial 15 finished with value: 1.0894511865427163 and parameters: {'n_estimators': 697, 'learning_rate': 0.08416783653137591, 'num_leaves': 106, 'max_depth': 12, 'min_child_samples': 96, 'subsample': 0.9380628585461992, 'colsample_bytree': 0.6845622378341825, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.2568042951080617e-05}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:46:03,747] Trial 16 finished with value: 1.2276660151688448 and parameters: {'n_estimators': 714, 'learning_rate': 0.039238293392292053, 'num_leaves': 113, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.9922101841078388, 'colsample_bytree': 0.7981593912973999, 'reg_alpha': 7.105458045938447e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:48:45,069] Trial 17 finished with value: 1.068004535966423 and parameters: {'n_estimators': 689, 'learning_rate': 0.09477718906891063, 'num_leaves': 109, 'max_depth': 12, 'min_child_samples': 88, 'subsample': 0.9387632330805946, 'colsample_bytree': 0.7113349365124932, 'reg_alpha': 0.0001657244190408193, 'reg_lambda': 8.882909064595106}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:51:50,199] Trial 18 finished with value: 1.035145006288937 and parameters: {'n_estimators': 742, 'learning_rate': 0.09835650654737227, 'num_leaves': 117, 'max_depth': 11, 'min_child_samples': 64, 'subsample': 0.8768734020039683, 'colsample_bytree': 0.8255898796085731, 'reg_alpha': 0.0062133129207280185, 'reg_lambda': 3.9233028601151885e-05}. Best is trial 12 with value: 0.993750571181731.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-19 21:54:59,023] A new study created in memory with name: lightgbm_wind_speed_ms

[I 2026-08-19 21:54:58,979] Trial 19 finished with value: 1.122791932279846 and parameters: {'n_estimators': 644, 'learning_rate': 0.06847287200689472, 'num_leaves': 121, 'max_depth': 9, 'min_child_samples': 64, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.8414683816291955, 'reg_alpha': 4.39912663270636e-06, 'reg_lambda': 0.02203830005166243}. Best is trial 12 with value: 0.993750571181731.
Najbolji MAE za t2m_c: 0.9938
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: wind_speed_ms =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:56:26,490] Trial 0 finished with value: 0.6987475435243881 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 21:59:59,517] Trial 1 finished with value: 0.7841497033669308 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:01:41,404] Trial 2 finished with value: 0.8242009839958285 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:03:32,049] Trial 3 finished with value: 0.8009104929753909 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:05:28,183] Trial 4 finished with value: 0.8136982931559108 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:08:31,338] Trial 5 finished with value: 0.7682213199333451 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:10:04,743] Trial 6 finished with value: 0.7541961420392062 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:11:53,237] Trial 7 finished with value: 0.8280218281180732 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:12:54,516] Trial 8 finished with value: 0.7470086926972905 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:15:04,451] Trial 9 finished with value: 0.8155588329516151 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:17:10,753] Trial 10 finished with value: 0.7348808565685112 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:19:18,522] Trial 11 finished with value: 0.7313268528281721 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 0.6987475435243881.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:21:41,050] Trial 12 finished with value: 0.6427352730866435 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:22:56,168] Trial 13 finished with value: 0.6932687112858855 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:23:55,339] Trial 14 finished with value: 0.7179433732612185 and parameters: {'n_estimators': 207, 'learning_rate': 0.13656063274976926, 'num_leaves': 127, 'max_depth': 11, 'min_child_samples': 56, 'subsample': 0.9936603420214545, 'colsample_bytree': 0.7002689872358562, 'reg_alpha': 0.0021061642705217896, 'reg_lambda': 0.02209753057171327}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:26:29,376] Trial 15 finished with value: 0.6800102130914722 and parameters: {'n_estimators': 693, 'learning_rate': 0.08416783653137591, 'num_leaves': 111, 'max_depth': 8, 'min_child_samples': 68, 'subsample': 0.9482895045354818, 'colsample_bytree': 0.6885106382275731, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.7729517753223987e-05}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:29:17,599] Trial 16 finished with value: 0.6742945494746694 and parameters: {'n_estimators': 714, 'learning_rate': 0.08763209561372623, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 70, 'subsample': 0.9447662143465629, 'colsample_bytree': 0.8041052156838847, 'reg_alpha': 5.1368867132154845e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:32:26,199] Trial 17 finished with value: 0.7126726514549674 and parameters: {'n_estimators': 706, 'learning_rate': 0.04435227280022695, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.931597543322844, 'colsample_bytree': 0.8460638946012234, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 2.2130642335816287e-08}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:34:21,866] Trial 18 finished with value: 0.7796105391940102 and parameters: {'n_estimators': 702, 'learning_rate': 0.09022688728529243, 'num_leaves': 108, 'max_depth': 4, 'min_child_samples': 46, 'subsample': 0.8968131503264609, 'colsample_bytree': 0.8158521383556735, 'reg_alpha': 5.0560307719444744e-05, 'reg_lambda': 1.866525267041869e-08}. Best is trial 12 with value: 0.6427352730866435.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-19 22:37:50,582] A new study created in memory with name: lightgbm_swh

[I 2026-08-19 22:37:50,546] Trial 19 finished with value: 0.7175148220090805 and parameters: {'n_estimators': 738, 'learning_rate': 0.03765110464989317, 'num_leaves': 114, 'max_depth': 12, 'min_child_samples': 97, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.9113240518308489, 'reg_alpha': 8.435923682268883e-08, 'reg_lambda': 7.976989870150589e-06}. Best is trial 12 with value: 0.6427352730866435.
Najbolji MAE za wind_speed_ms: 0.6427
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: swh =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:38:13,837] Trial 0 finished with value: 0.10410454306769296 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:39:05,987] Trial 1 finished with value: 0.11919188576896596 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:39:30,675] Trial 2 finished with value: 0.1265558368501973 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:39:58,492] Trial 3 finished with value: 0.12222056806605916 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:40:26,700] Trial 4 finished with value: 0.12488916757186792 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:41:14,167] Trial 5 finished with value: 0.1159732815783704 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:41:37,324] Trial 6 finished with value: 0.11391950769125567 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:42:04,254] Trial 7 finished with value: 0.12741149467415736 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:42:19,883] Trial 8 finished with value: 0.11225168385741119 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:42:51,522] Trial 9 finished with value: 0.12517978135397184 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:43:23,080] Trial 10 finished with value: 0.10861286796926145 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:43:55,347] Trial 11 finished with value: 0.10728644765110242 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 0.10410454306769296.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:44:35,575] Trial 12 finished with value: 0.09829579337434986 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:44:55,288] Trial 13 finished with value: 0.10430198379479783 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:45:33,607] Trial 14 finished with value: 0.10027144821265553 and parameters: {'n_estimators': 711, 'learning_rate': 0.10215516856364636, 'num_leaves': 109, 'max_depth': 11, 'min_child_samples': 100, 'subsample': 0.9445565374939666, 'colsample_bytree': 0.6808861803604528, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 2.5683275964108445e-05}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:46:11,448] Trial 15 finished with value: 0.10108345903688523 and parameters: {'n_estimators': 697, 'learning_rate': 0.08416783653137591, 'num_leaves': 106, 'max_depth': 12, 'min_child_samples': 96, 'subsample': 0.9380628585461992, 'colsample_bytree': 0.6845622378341825, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.2568042951080617e-05}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:46:59,514] Trial 16 finished with value: 0.10808675330450788 and parameters: {'n_estimators': 714, 'learning_rate': 0.039238293392292053, 'num_leaves': 113, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.9922101841078388, 'colsample_bytree': 0.7981593912973999, 'reg_alpha': 7.105458045938447e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:47:38,075] Trial 17 finished with value: 0.10036815516110287 and parameters: {'n_estimators': 689, 'learning_rate': 0.09477718906891063, 'num_leaves': 109, 'max_depth': 12, 'min_child_samples': 88, 'subsample': 0.9387632330805946, 'colsample_bytree': 0.7113349365124932, 'reg_alpha': 0.0001657244190408193, 'reg_lambda': 8.882909064595106}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:48:24,846] Trial 18 finished with value: 0.09853445110592474 and parameters: {'n_estimators': 742, 'learning_rate': 0.09835650654737227, 'num_leaves': 117, 'max_depth': 11, 'min_child_samples': 64, 'subsample': 0.8768734020039683, 'colsample_bytree': 0.8255898796085731, 'reg_alpha': 0.0062133129207280185, 'reg_lambda': 3.9233028601151885e-05}. Best is trial 12 with value: 0.09829579337434986.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-19 22:49:10,182] A new study created in memory with name: lightgbm_mwp

[I 2026-08-19 22:49:10,167] Trial 19 finished with value: 0.10312618620390508 and parameters: {'n_estimators': 644, 'learning_rate': 0.06847287200689472, 'num_leaves': 121, 'max_depth': 9, 'min_child_samples': 64, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.8414683816291955, 'reg_alpha': 4.39912663270636e-06, 'reg_lambda': 0.02203830005166243}. Best is trial 12 with value: 0.09829579337434986.
Najbolji MAE za swh: 0.0983
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: mwp =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:49:34,049] Trial 0 finished with value: 0.24360103453423101 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:50:33,945] Trial 1 finished with value: 0.27012412307189515 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:51:00,126] Trial 2 finished with value: 0.2846964432386736 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:51:29,419] Trial 3 finished with value: 0.27648351734995213 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:52:01,150] Trial 4 finished with value: 0.28097856246934705 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:52:52,795] Trial 5 finished with value: 0.2653152758607572 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:53:16,101] Trial 6 finished with value: 0.26213584157278474 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:53:40,756] Trial 7 finished with value: 0.2855785240493344 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:53:58,075] Trial 8 finished with value: 0.258405884503822 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:54:32,141] Trial 9 finished with value: 0.2818217865576959 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:55:05,482] Trial 10 finished with value: 0.2522300714585716 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:55:39,094] Trial 11 finished with value: 0.25145888213185796 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 0.24360103453423101.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:56:19,633] Trial 12 finished with value: 0.23349238875615577 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:56:40,012] Trial 13 finished with value: 0.24541830918403681 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:57:19,091] Trial 14 finished with value: 0.23811476030758374 and parameters: {'n_estimators': 711, 'learning_rate': 0.10215516856364636, 'num_leaves': 109, 'max_depth': 11, 'min_child_samples': 100, 'subsample': 0.9445565374939666, 'colsample_bytree': 0.6808861803604528, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 2.5683275964108445e-05}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:57:58,058] Trial 15 finished with value: 0.23846314160035034 and parameters: {'n_estimators': 697, 'learning_rate': 0.08416783653137591, 'num_leaves': 106, 'max_depth': 12, 'min_child_samples': 96, 'subsample': 0.9380628585461992, 'colsample_bytree': 0.6845622378341825, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.2568042951080617e-05}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:58:49,069] Trial 16 finished with value: 0.25239865536912937 and parameters: {'n_estimators': 714, 'learning_rate': 0.039238293392292053, 'num_leaves': 113, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.9922101841078388, 'colsample_bytree': 0.7981593912973999, 'reg_alpha': 7.105458045938447e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 22:59:28,485] Trial 17 finished with value: 0.2380625198154172 and parameters: {'n_estimators': 689, 'learning_rate': 0.09477718906891063, 'num_leaves': 109, 'max_depth': 12, 'min_child_samples': 88, 'subsample': 0.9387632330805946, 'colsample_bytree': 0.7113349365124932, 'reg_alpha': 0.0001657244190408193, 'reg_lambda': 8.882909064595106}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:00:09,485] Trial 18 finished with value: 0.24033677454529018 and parameters: {'n_estimators': 638, 'learning_rate': 0.07564045864972031, 'num_leaves': 117, 'max_depth': 12, 'min_child_samples': 74, 'subsample': 0.8905272356386674, 'colsample_bytree': 0.7381792150637859, 'reg_alpha': 4.081195983788296e-05, 'reg_lambda': 6.895812742171656}. Best is trial 12 with value: 0.23349238875615577.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-19 23:01:00,556] A new study created in memory with name: lightgbm_mwd

[I 2026-08-19 23:01:00,545] Trial 19 finished with value: 0.25247213808193586 and parameters: {'n_estimators': 679, 'learning_rate': 0.03765110464989317, 'num_leaves': 100, 'max_depth': 9, 'min_child_samples': 89, 'subsample': 0.8541643472609534, 'colsample_bytree': 0.8328883712470154, 'reg_alpha': 1.540681918021692e-07, 'reg_lambda': 0.028589805776360853}. Best is trial 12 with value: 0.23349238875615577.
Najbolji MAE za mwp: 0.2335
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: mwd =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:01:21,565] Trial 0 finished with value: 42.669340201913215 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:02:18,587] Trial 1 finished with value: 43.902795424521045 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:02:47,902] Trial 2 finished with value: 45.90007566751125 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:03:16,410] Trial 3 finished with value: 44.997331114446055 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:03:48,395] Trial 4 finished with value: 45.20597544967091 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:04:37,254] Trial 5 finished with value: 43.63100922910631 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:05:00,377] Trial 6 finished with value: 43.97263385726697 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:05:29,031] Trial 7 finished with value: 46.11568791680197 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:05:44,508] Trial 8 finished with value: 43.161778011788606 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:06:16,499] Trial 9 finished with value: 45.51585262640737 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:06:47,133] Trial 10 finished with value: 43.056881801352944 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:07:18,042] Trial 11 finished with value: 42.81705198207057 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 42.669340201913215.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:07:53,994] Trial 12 finished with value: 42.35042760551654 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 42.35042760551654.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:08:12,995] Trial 13 finished with value: 42.74878960026521 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 42.35042760551654.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:08:48,322] Trial 14 finished with value: 42.12935315806614 and parameters: {'n_estimators': 711, 'learning_rate': 0.10215516856364636, 'num_leaves': 109, 'max_depth': 11, 'min_child_samples': 100, 'subsample': 0.9445565374939666, 'colsample_bytree': 0.6808861803604528, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 2.5683275964108445e-05}. Best is trial 14 with value: 42.12935315806614.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:09:23,647] Trial 15 finished with value: 41.99044976629906 and parameters: {'n_estimators': 697, 'learning_rate': 0.08416783653137591, 'num_leaves': 106, 'max_depth': 12, 'min_child_samples': 96, 'subsample': 0.9380628585461992, 'colsample_bytree': 0.6845622378341825, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.2568042951080617e-05}. Best is trial 15 with value: 41.99044976629906.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:10:09,362] Trial 16 finished with value: 42.15663109773104 and parameters: {'n_estimators': 695, 'learning_rate': 0.04106935533060614, 'num_leaves': 109, 'max_depth': 12, 'min_child_samples': 98, 'subsample': 0.9311014109805634, 'colsample_bytree': 0.8010118500627189, 'reg_alpha': 0.02316062671984357, 'reg_lambda': 1.314053143275926e-08}. Best is trial 15 with value: 41.99044976629906.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:10:47,525] Trial 17 finished with value: 42.02258627527285 and parameters: {'n_estimators': 682, 'learning_rate': 0.08598109957016284, 'num_leaves': 107, 'max_depth': 9, 'min_child_samples': 97, 'subsample': 0.9994098262766559, 'colsample_bytree': 0.7113349365124932, 'reg_alpha': 1.4110197474030326e-05, 'reg_lambda': 1.959434655228417e-05}. Best is trial 15 with value: 41.99044976629906.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:11:27,850] Trial 18 finished with value: 42.21381978444396 and parameters: {'n_estimators': 674, 'learning_rate': 0.07769430220596708, 'num_leaves': 107, 'max_depth': 8, 'min_child_samples': 86, 'subsample': 0.9935199751279746, 'colsample_bytree': 0.7381792150637859, 'reg_alpha': 3.309996479076232e-05, 'reg_lambda': 1.2759467603525661e-05}. Best is trial 15 with value: 41.99044976629906.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-19 23:12:06,579] A new study created in memory with name: lightgbm_sst_c

[I 2026-08-19 23:12:06,558] Trial 19 finished with value: 43.114818007926345 and parameters: {'n_estimators': 664, 'learning_rate': 0.045388381995090335, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 74, 'subsample': 0.8952762302156516, 'colsample_bytree': 0.8328883712470154, 'reg_alpha': 4.054977373717874e-08, 'reg_lambda': 2.455918006464903e-08}. Best is trial 15 with value: 41.99044976629906.
Najbolji MAE za mwd: 41.9904
Najbolji parametri:
{'n_estimators': 697, 'learning_rate': 0.08416783653137591, 'num_leaves': 106, 'max_depth': 12, 'min_child_samples': 96, 'subsample': 0.9380628585461992, 'colsample_bytree': 0.6845622378341825, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.2568042951080617e-05}

===== OPTUNA: sst_c =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:12:56,664] Trial 0 finished with value: 0.16189276815011525 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.16189276815011525.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:14:59,757] Trial 1 finished with value: 0.20559394437930031 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.16189276815011525.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:15:58,265] Trial 2 finished with value: 0.1916056419191256 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.16189276815011525.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:16:50,901] Trial 3 finished with value: 0.15419013116654126 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:17:55,956] Trial 4 finished with value: 0.27782735244780443 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:19:28,683] Trial 5 finished with value: 0.15885131146439596 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:20:21,380] Trial 6 finished with value: 0.16083834541778025 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:21:16,070] Trial 7 finished with value: 0.16186103462469803 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:21:50,759] Trial 8 finished with value: 0.16762480629935878 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:23:05,138] Trial 9 finished with value: 0.17823714148463465 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 3 with value: 0.15419013116654126.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:24:34,358] Trial 10 finished with value: 0.1409755261623142 and parameters: {'n_estimators': 774, 'learning_rate': 0.056105998777192946, 'num_leaves': 48, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8927062497533367, 'colsample_bytree': 0.9844101161191828, 'reg_alpha': 0.0025347992375043043, 'reg_lambda': 0.0241914427714187}. Best is trial 10 with value: 0.1409755261623142.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:25:51,974] Trial 11 finished with value: 0.14059240271186463 and parameters: {'n_estimators': 798, 'learning_rate': 0.05755120913768578, 'num_leaves': 46, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8845640839188065, 'colsample_bytree': 0.9867645281621887, 'reg_alpha': 0.0014860335400091176, 'reg_lambda': 0.017475324694510522}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:27:13,787] Trial 12 finished with value: 0.14972776326539275 and parameters: {'n_estimators': 781, 'learning_rate': 0.057489180054056295, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.897370228090215, 'colsample_bytree': 0.9087696049520284, 'reg_alpha': 0.0005253090902252391, 'reg_lambda': 0.008570258771204367}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:28:37,695] Trial 13 finished with value: 0.14858199551995907 and parameters: {'n_estimators': 798, 'learning_rate': 0.04959557861980787, 'num_leaves': 48, 'max_depth': 14, 'min_child_samples': 60, 'subsample': 0.9091638468596673, 'colsample_bytree': 0.9365203136172531, 'reg_alpha': 0.00226313919629691, 'reg_lambda': 9.23225891796307}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:29:58,155] Trial 14 finished with value: 0.1530443133778031 and parameters: {'n_estimators': 695, 'learning_rate': 0.0696636880992615, 'num_leaves': 55, 'max_depth': 12, 'min_child_samples': 58, 'subsample': 0.9626162449798543, 'colsample_bytree': 0.8522835584206043, 'reg_alpha': 0.0017908830770219431, 'reg_lambda': 2.354809522325329e-05}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:31:13,520] Trial 15 finished with value: 0.14799858923055628 and parameters: {'n_estimators': 704, 'learning_rate': 0.03372771532885688, 'num_leaves': 37, 'max_depth': 12, 'min_child_samples': 69, 'subsample': 0.8663991887625972, 'colsample_bytree': 0.9611984472418021, 'reg_alpha': 0.0002009475076168114, 'reg_lambda': 0.011451685238529786}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:32:51,680] Trial 16 finished with value: 0.15611195944102893 and parameters: {'n_estimators': 720, 'learning_rate': 0.037624133327330514, 'num_leaves': 62, 'max_depth': 14, 'min_child_samples': 50, 'subsample': 0.8548085916053562, 'colsample_bytree': 0.8699017348872609, 'reg_alpha': 0.015202258241339283, 'reg_lambda': 1.314053143275926e-08}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:34:02,084] Trial 17 finished with value: 0.14824924190084524 and parameters: {'n_estimators': 743, 'learning_rate': 0.07928610560321428, 'num_leaves': 37, 'max_depth': 11, 'min_child_samples': 72, 'subsample': 0.9387632330805946, 'colsample_bytree': 0.9391123028523524, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 0.04902924827899063}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:35:11,970] Trial 18 finished with value: 0.1468411621065788 and parameters: {'n_estimators': 660, 'learning_rate': 0.037910111303122954, 'num_leaves': 35, 'max_depth': 13, 'min_child_samples': 45, 'subsample': 0.8774553012987176, 'colsample_bytree': 0.9972353184760769, 'reg_alpha': 9.433067880400517e-05, 'reg_lambda': 0.0003375135773340992}. Best is trial 11 with value: 0.14059240271186463.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-19 23:36:33,532] A new study created in memory with name: lightgbm_msl_hpa

[I 2026-08-19 23:36:33,506] Trial 19 finished with value: 0.14717299643356552 and parameters: {'n_estimators': 799, 'learning_rate': 0.0932916452938654, 'num_leaves': 64, 'max_depth': 13, 'min_child_samples': 93, 'subsample': 0.8204282888802901, 'colsample_bytree': 0.8901692685329862, 'reg_alpha': 0.01167876484511318, 'reg_lambda': 5.181424858375195}. Best is trial 11 with value: 0.14059240271186463.
Najbolji MAE za sst_c: 0.1406
Najbolji parametri:
{'n_estimators': 798, 'learning_rate': 0.05755120913768578, 'num_leaves': 46, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8845640839188065, 'colsample_bytree': 0.9867645281621887, 'reg_alpha': 0.0014860335400091176, 'reg_lambda': 0.017475324694510522}

===== OPTUNA: msl_hpa =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:38:13,881] Trial 0 finished with value: 1.242077852663583 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:42:16,338] Trial 1 finished with value: 1.6426727948490947 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:44:04,273] Trial 2 finished with value: 1.7649254048960328 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:46:01,218] Trial 3 finished with value: 1.6525114500676819 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:48:11,538] Trial 4 finished with value: 1.7562862310587457 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:51:32,992] Trial 5 finished with value: 1.5522307018318826 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:53:09,786] Trial 6 finished with value: 1.486663865527153 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:55:05,199] Trial 7 finished with value: 1.7833712279309286 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:56:12,381] Trial 8 finished with value: 1.4541850238781826 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-19 23:58:29,600] Trial 9 finished with value: 1.7270260866516671 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:00:49,930] Trial 10 finished with value: 1.3878149925809764 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:03:11,019] Trial 11 finished with value: 1.3702458705123486 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 1.242077852663583.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:05:58,479] Trial 12 finished with value: 1.0185510652197356 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:07:21,262] Trial 13 finished with value: 1.2372460227179911 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:08:27,380] Trial 14 finished with value: 1.3214634065876494 and parameters: {'n_estimators': 207, 'learning_rate': 0.13656063274976926, 'num_leaves': 127, 'max_depth': 11, 'min_child_samples': 56, 'subsample': 0.9936603420214545, 'colsample_bytree': 0.7002689872358562, 'reg_alpha': 0.0021061642705217896, 'reg_lambda': 0.02209753057171327}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:11:18,160] Trial 15 finished with value: 1.2036551589652056 and parameters: {'n_estimators': 693, 'learning_rate': 0.08416783653137591, 'num_leaves': 111, 'max_depth': 8, 'min_child_samples': 68, 'subsample': 0.9482895045354818, 'colsample_bytree': 0.6885106382275731, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.7729517753223987e-05}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:14:24,538] Trial 16 finished with value: 1.1841827446751405 and parameters: {'n_estimators': 714, 'learning_rate': 0.08763209561372623, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 70, 'subsample': 0.9447662143465629, 'colsample_bytree': 0.8041052156838847, 'reg_alpha': 5.1368867132154845e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:17:48,500] Trial 17 finished with value: 1.3393426845517704 and parameters: {'n_estimators': 706, 'learning_rate': 0.04435227280022695, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.931597543322844, 'colsample_bytree': 0.8460638946012234, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 2.2130642335816287e-08}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:19:44,732] Trial 18 finished with value: 1.5939085529668549 and parameters: {'n_estimators': 702, 'learning_rate': 0.09022688728529243, 'num_leaves': 108, 'max_depth': 4, 'min_child_samples': 46, 'subsample': 0.8968131503264609, 'colsample_bytree': 0.8158521383556735, 'reg_alpha': 5.0560307719444744e-05, 'reg_lambda': 1.866525267041869e-08}. Best is trial 12 with value: 1.0185510652197356.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-20 00:23:39,406] A new study created in memory with name: lightgbm_tcc

[I 2026-08-20 00:23:39,362] Trial 19 finished with value: 1.3237932193560276 and parameters: {'n_estimators': 738, 'learning_rate': 0.03765110464989317, 'num_leaves': 114, 'max_depth': 12, 'min_child_samples': 97, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.9113240518308489, 'reg_alpha': 8.435923682268883e-08, 'reg_lambda': 7.976989870150589e-06}. Best is trial 12 with value: 1.0185510652197356.
Najbolji MAE za msl_hpa: 1.0186
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: tcc =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:25:03,276] Trial 0 finished with value: 0.18408345178704716 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:28:38,485] Trial 1 finished with value: 0.22287519515860377 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:30:19,103] Trial 2 finished with value: 0.23691400542175683 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:32:11,258] Trial 3 finished with value: 0.2270414835801264 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:34:10,357] Trial 4 finished with value: 0.23424177407558852 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:37:09,868] Trial 5 finished with value: 0.2171979603708898 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:38:41,824] Trial 6 finished with value: 0.21056441557915104 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:40:29,415] Trial 7 finished with value: 0.2380658273585813 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:41:28,768] Trial 8 finished with value: 0.20745949963035779 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:43:37,742] Trial 9 finished with value: 0.2333915915279805 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:45:43,028] Trial 10 finished with value: 0.20195216471615599 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:47:47,301] Trial 11 finished with value: 0.19973179091926466 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 0.18408345178704716.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:50:05,632] Trial 12 finished with value: 0.16301553119848958 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:51:16,220] Trial 13 finished with value: 0.18552485878717417 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:53:28,396] Trial 14 finished with value: 0.17405696602487442 and parameters: {'n_estimators': 711, 'learning_rate': 0.10215516856364636, 'num_leaves': 109, 'max_depth': 11, 'min_child_samples': 100, 'subsample': 0.9445565374939666, 'colsample_bytree': 0.6808861803604528, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 2.5683275964108445e-05}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:55:42,640] Trial 15 finished with value: 0.17879213377142175 and parameters: {'n_estimators': 697, 'learning_rate': 0.08416783653137591, 'num_leaves': 106, 'max_depth': 12, 'min_child_samples': 96, 'subsample': 0.9380628585461992, 'colsample_bytree': 0.6845622378341825, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.2568042951080617e-05}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 00:58:49,768] Trial 16 finished with value: 0.19758901487390268 and parameters: {'n_estimators': 714, 'learning_rate': 0.039238293392292053, 'num_leaves': 113, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.9922101841078388, 'colsample_bytree': 0.7981593912973999, 'reg_alpha': 7.105458045938447e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:01:05,409] Trial 17 finished with value: 0.1764787783943101 and parameters: {'n_estimators': 689, 'learning_rate': 0.09477718906891063, 'num_leaves': 109, 'max_depth': 12, 'min_child_samples': 88, 'subsample': 0.9387632330805946, 'colsample_bytree': 0.7113349365124932, 'reg_alpha': 0.0001657244190408193, 'reg_lambda': 8.882909064595106}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:03:43,966] Trial 18 finished with value: 0.17051216313512146 and parameters: {'n_estimators': 742, 'learning_rate': 0.09835650654737227, 'num_leaves': 117, 'max_depth': 11, 'min_child_samples': 64, 'subsample': 0.8768734020039683, 'colsample_bytree': 0.8255898796085731, 'reg_alpha': 0.0062133129207280185, 'reg_lambda': 3.9233028601151885e-05}. Best is trial 12 with value: 0.16301553119848958.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-20 01:06:22,781] A new study created in memory with name: lightgbm_cape

[I 2026-08-20 01:06:22,733] Trial 19 finished with value: 0.184232092791072 and parameters: {'n_estimators': 644, 'learning_rate': 0.06847287200689472, 'num_leaves': 121, 'max_depth': 9, 'min_child_samples': 64, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.8414683816291955, 'reg_alpha': 4.39912663270636e-06, 'reg_lambda': 0.02203830005166243}. Best is trial 12 with value: 0.16301553119848958.
Najbolji MAE za tcc: 0.1630
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: cape =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:07:30,137] Trial 0 finished with value: 82.66142181376082 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:09:57,814] Trial 1 finished with value: 97.01825663708493 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:11:43,470] Trial 2 finished with value: 103.46511212049246 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:13:18,854] Trial 3 finished with value: 99.96560779351516 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:14:41,553] Trial 4 finished with value: 101.92360999724362 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:16:46,445] Trial 5 finished with value: 94.92223638169153 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:18:03,880] Trial 6 finished with value: 93.516841947172 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:19:32,414] Trial 7 finished with value: 103.86604931168861 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:20:16,593] Trial 8 finished with value: 90.87103126791395 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:21:54,474] Trial 9 finished with value: 102.23223258783732 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:23:33,634] Trial 10 finished with value: 88.7330966355823 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:25:14,179] Trial 11 finished with value: 87.37496209138335 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 82.66142181376082.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:27:08,434] Trial 12 finished with value: 74.23426881677014 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:28:04,825] Trial 13 finished with value: 82.64687042932081 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:28:49,711] Trial 14 finished with value: 86.29969762727958 and parameters: {'n_estimators': 207, 'learning_rate': 0.13656063274976926, 'num_leaves': 127, 'max_depth': 11, 'min_child_samples': 56, 'subsample': 0.9936603420214545, 'colsample_bytree': 0.7002689872358562, 'reg_alpha': 0.0021061642705217896, 'reg_lambda': 0.02209753057171327}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:30:49,022] Trial 15 finished with value: 81.05172287156736 and parameters: {'n_estimators': 693, 'learning_rate': 0.08416783653137591, 'num_leaves': 111, 'max_depth': 8, 'min_child_samples': 68, 'subsample': 0.9482895045354818, 'colsample_bytree': 0.6885106382275731, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.7729517753223987e-05}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:33:02,081] Trial 16 finished with value: 80.12217995221484 and parameters: {'n_estimators': 714, 'learning_rate': 0.08763209561372623, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 70, 'subsample': 0.9447662143465629, 'colsample_bytree': 0.8041052156838847, 'reg_alpha': 5.1368867132154845e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:35:22,591] Trial 17 finished with value: 85.67973832652709 and parameters: {'n_estimators': 706, 'learning_rate': 0.04435227280022695, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.931597543322844, 'colsample_bytree': 0.8460638946012234, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 2.2130642335816287e-08}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:37:08,274] Trial 18 finished with value: 99.3524836291397 and parameters: {'n_estimators': 702, 'learning_rate': 0.09022688728529243, 'num_leaves': 108, 'max_depth': 4, 'min_child_samples': 46, 'subsample': 0.8968131503264609, 'colsample_bytree': 0.8158521383556735, 'reg_alpha': 5.0560307719444744e-05, 'reg_lambda': 1.866525267041869e-08}. Best is trial 12 with value: 74.23426881677014.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-08-20 01:39:38,325] A new study created in memory with name: lightgbm_blh

[I 2026-08-20 01:39:38,285] Trial 19 finished with value: 84.4521693852809 and parameters: {'n_estimators': 738, 'learning_rate': 0.03765110464989317, 'num_leaves': 114, 'max_depth': 12, 'min_child_samples': 97, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.9113240518308489, 'reg_alpha': 8.435923682268883e-08, 'reg_lambda': 7.976989870150589e-06}. Best is trial 12 with value: 74.23426881677014.
Najbolji MAE za cape: 74.2343
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

===== OPTUNA: blh =====

  0%|          | 0/20 [00:00<?, ?it/s]

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:41:06,020] Trial 0 finished with value: 154.18771004206513 and parameters: {'n_estimators': 425, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 24, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:44:45,711] Trial 1 finished with value: 181.4011886234395 and parameters: {'n_estimators': 625, 'learning_rate': 0.010573268083515799, 'num_leaves': 124, 'max_depth': 13, 'min_child_samples': 29, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:46:25,956] Trial 2 finished with value: 200.98721323847604 and parameters: {'n_estimators': 459, 'learning_rate': 0.022004527434741072, 'num_leaves': 84, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:48:21,788] Trial 3 finished with value: 187.22428229602673 and parameters: {'n_estimators': 509, 'learning_rate': 0.049743185797885274, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:50:17,714] Trial 4 finished with value: 193.75528612921306 and parameters: {'n_estimators': 383, 'learning_rate': 0.01302780710309028, 'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.848553073033381, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:53:27,283] Trial 5 finished with value: 175.7167263917295 and parameters: {'n_estimators': 598, 'learning_rate': 0.02325951592241212, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:55:02,665] Trial 6 finished with value: 174.6208533473513 and parameters: {'n_estimators': 559, 'learning_rate': 0.12139707695554378, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:56:51,017] Trial 7 finished with value: 203.15547803228696 and parameters: {'n_estimators': 414, 'learning_rate': 0.02139954903017622, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 82, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 01:57:54,094] Trial 8 finished with value: 168.64685834826497 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 80, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:00:06,868] Trial 9 finished with value: 194.44449026139233 and parameters: {'n_estimators': 574, 'learning_rate': 0.02450001073565503, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:02:20,014] Trial 10 finished with value: 164.97770926043893 and parameters: {'n_estimators': 771, 'learning_rate': 0.06154115750118984, 'num_leaves': 49, 'max_depth': 14, 'min_child_samples': 57, 'subsample': 0.8928551377022524, 'colsample_bytree': 0.6062379198633824, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:04:32,441] Trial 11 finished with value: 163.80139260136005 and parameters: {'n_estimators': 798, 'learning_rate': 0.0646965830137823, 'num_leaves': 51, 'max_depth': 14, 'min_child_samples': 58, 'subsample': 0.8876236216715458, 'colsample_bytree': 0.6044153008610612, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 0 with value: 154.18771004206513.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:06:54,327] Trial 12 finished with value: 138.86719809872017 and parameters: {'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:08:09,386] Trial 13 finished with value: 153.45357908594352 and parameters: {'n_estimators': 295, 'learning_rate': 0.1460125249622346, 'num_leaves': 126, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.9658644115630726, 'colsample_bytree': 0.6878439334412321, 'reg_alpha': 0.0028842060182957367, 'reg_lambda': 0.014775475739688114}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:09:10,485] Trial 14 finished with value: 159.5016707301081 and parameters: {'n_estimators': 207, 'learning_rate': 0.13656063274976926, 'num_leaves': 127, 'max_depth': 11, 'min_child_samples': 56, 'subsample': 0.9936603420214545, 'colsample_bytree': 0.7002689872358562, 'reg_alpha': 0.0021061642705217896, 'reg_lambda': 0.02209753057171327}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:11:46,259] Trial 15 finished with value: 150.88512291260895 and parameters: {'n_estimators': 693, 'learning_rate': 0.08416783653137591, 'num_leaves': 111, 'max_depth': 8, 'min_child_samples': 68, 'subsample': 0.9482895045354818, 'colsample_bytree': 0.6885106382275731, 'reg_alpha': 0.010836930382935862, 'reg_lambda': 2.7729517753223987e-05}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:14:38,016] Trial 16 finished with value: 149.57722229903536 and parameters: {'n_estimators': 714, 'learning_rate': 0.08763209561372623, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 70, 'subsample': 0.9447662143465629, 'colsample_bytree': 0.8041052156838847, 'reg_alpha': 5.1368867132154845e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:17:50,710] Trial 17 finished with value: 160.12446206099764 and parameters: {'n_estimators': 706, 'learning_rate': 0.04435227280022695, 'num_leaves': 109, 'max_depth': 8, 'min_child_samples': 72, 'subsample': 0.931597543322844, 'colsample_bytree': 0.8460638946012234, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 2.2130642335816287e-08}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:19:47,099] Trial 18 finished with value: 186.173034364777 and parameters: {'n_estimators': 702, 'learning_rate': 0.09022688728529243, 'num_leaves': 108, 'max_depth': 4, 'min_child_samples': 46, 'subsample': 0.8968131503264609, 'colsample_bytree': 0.8158521383556735, 'reg_alpha': 5.0560307719444744e-05, 'reg_lambda': 1.866525267041869e-08}. Best is trial 12 with value: 138.86719809872017.

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[I 2026-08-20 02:23:25,222] Trial 19 finished with value: 158.2037234068018 and parameters: {'n_estimators': 738, 'learning_rate': 0.03765110464989317, 'num_leaves': 114, 'max_depth': 12, 'min_child_samples': 97, 'subsample': 0.8591790707058076, 'colsample_bytree': 0.9113240518308489, 'reg_alpha': 8.435923682268883e-08, 'reg_lambda': 7.976989870150589e-06}. Best is trial 12 with value: 138.86719809872017.
Najbolji MAE za blh: 138.8672
Najbolji parametri:
{'n_estimators': 757, 'learning_rate': 0.1373669452343056, 'num_leaves': 123, 'max_depth': 11, 'min_child_samples': 52, 'subsample': 0.9615462369688978, 'colsample_bytree': 0.6828922252774745, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}

=== OPTUNA REZULTATI ZA SVE TARGETE ===

,model,target,best_MAE,n_trials,n_estimators,learning_rate,num_leaves,max_depth,min_child_samples,subsample,colsample_bytree,reg_alpha,reg_lambda
0,LightGBM,t2m_c,0.993751,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
1,LightGBM,wind_speed_ms,0.642735,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
2,LightGBM,swh,0.098296,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
3,LightGBM,mwp,0.233492,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
4,LightGBM,mwd,41.990450,20,697,0.084168,106,12,96,0.938063,0.684562,0.010837,0.000023
5,LightGBM,sst_c,0.140592,20,798,0.057551,46,14,58,0.884564,0.986765,0.001486,0.017475
6,LightGBM,msl_hpa,1.018551,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
7,LightGBM,tcc,0.163016,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
8,LightGBM,cape,74.234269,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036
9,LightGBM,blh,138.867198,20,757,0.137367,123,11,52,0.961546,0.682892,0.002078,0.008036

Spremljeno u: optuna_lightgbm_svi_targeti.csv