# Meteo prognoza — XGBoost

## 1. Importi i konfiguracija

In [14]:
!pip install xgboost
%pip install optuna

Requirement already satisfied: xgboost in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (3.3.0)
Requirement already satisfied: numpy in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (1.16.3)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: optuna in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\korisnik\appdata\roaming\python\python313\site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: colorama in c:\users\korisnik\appdata\roaming\python\python313\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\korisnik\appdata\local\programs\python\python313\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Ako nedostaju paketi, pokreni: %pip install lightgbm xgboost
import gc
import pandas as pd
import numpy as np
import lightgbm as lgb
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

MODEL_NAME = 'XGBoost'

RANDOM_STATE = 42
HORIZONT = 12
VALIDATION_FRACTION = 0.10
BUFFER_STUPNJEVI = 0.3
CSV_PATH = 'ERA5_SPOJENO_2015_2023.csv'
OUTPUT_RESULTS = f'{MODEL_NAME.lower()}_rezultati_po_targetu.csv'

LAT_PULA, LON_PULA = 44.8666, 13.8496
LAT_RIJEKA, LON_RIJEKA = 45.3271, 14.4422

TARGETS = ['t2m_c', 'wind_speed_ms', 'swh', 'mwp', 'mwd', 'sst_c', 'msl_hpa', 'tcc', 'cape', 'blh']
LAG_VARS = ['t2m_c', 'msl_hpa', 'wind_speed_ms', 'tcc', 'cape']

# Ako nedostaje RAM-a, postavi npr. 300_000.
MAX_TRAIN_ROWS = None

## 2. Učitavanje podataka

In [4]:
df = pd.read_csv(CSV_PATH)
df['valid_time'] = pd.to_datetime(df['valid_time'])
df = df.sort_values(['latitude', 'longitude', 'valid_time']).reset_index(drop=True)

print(f'Ukupno redaka: {len(df):,}')
print(f'Broj stupaca: {df.shape[1]}')
print(f'Broj lokacija: {df[["latitude", "longitude"]].drop_duplicates().shape[0]}')
print(f'Period: {df["valid_time"].min()} do {df["valid_time"].max()}')
print('Duplikati:', df.duplicated(['valid_time', 'latitude', 'longitude']).sum())

Ukupno redaka: 3,367,224
Broj stupaca: 37
Broj lokacija: 42
Period: 2015-01-01 00:00:00 do 2023-12-31 23:00:00
Duplikati: 53928

## 3. Izdvajanje lokacija

In [6]:
locations = df[['latitude', 'longitude']].drop_duplicates().copy()
locations['dist_pula'] = np.sqrt((locations['latitude'] - LAT_PULA)**2 + (locations['longitude'] - LON_PULA)**2)
locations['dist_rijeka'] = np.sqrt((locations['latitude'] - LAT_RIJEKA)**2 + (locations['longitude'] - LON_RIJEKA)**2)
pula_grid = locations.loc[locations['dist_pula'].idxmin(), ['latitude', 'longitude']]
rijeka_grid = locations.loc[locations['dist_rijeka'].idxmin(), ['latitude', 'longitude']]
lat_pula_grid, lon_pula_grid = pula_grid['latitude'], pula_grid['longitude']
lat_rijeka_grid, lon_rijeka_grid = rijeka_grid['latitude'], rijeka_grid['longitude']

df['dist_pula'] = np.sqrt((df['latitude'] - LAT_PULA)**2 + (df['longitude'] - LON_PULA)**2)
df['dist_rijeka'] = np.sqrt((df['latitude'] - LAT_RIJEKA)**2 + (df['longitude'] - LON_RIJEKA)**2)
je_pula = (df['latitude'] == lat_pula_grid) & (df['longitude'] == lon_pula_grid)
je_rijeka = (df['latitude'] == lat_rijeka_grid) & (df['longitude'] == lon_rijeka_grid)
blizu = (df['dist_pula'] < BUFFER_STUPNJEVI) | (df['dist_rijeka'] < BUFFER_STUPNJEVI)

df_pula = df.loc[je_pula].copy()
df_rijeka = df.loc[je_rijeka].copy()
df_train = df.loc[~je_pula & ~je_rijeka & ~blizu].copy()

if MAX_TRAIN_ROWS is not None and len(df_train) > MAX_TRAIN_ROWS:
    df_train = df_train.sort_values(['valid_time', 'latitude', 'longitude']).iloc[:MAX_TRAIN_ROWS].copy()

print(f'Pula: {len(df_pula):,}')
print(f'Rijeka: {len(df_rijeka):,}')
print(f'Trening: {len(df_train):,}')
del locations
gc.collect()

Pula: 80,172
Rijeka: 80,172
Trening: 2,725,848

0

## 4. Feature engineering

In [7]:
def add_features(data):
    data = data.sort_values(['latitude', 'longitude', 'valid_time']).copy()
    groups = data.groupby(['latitude', 'longitude'])

    for var in LAG_VARS:
        if var not in data.columns:
            continue
        data[f'{var}_lag3h'] = groups[var].shift(3)
        data[f'{var}_lag6h'] = groups[var].shift(6)
        data[f'{var}_trend3h'] = data[var] - data[f'{var}_lag3h']
        data[f'{var}_rolling6h_mean'] = groups[var].transform(lambda s: s.rolling(6, min_periods=1).mean())

    if 'wind_dir_deg' in data.columns:
        data['wind_dir_sin'] = np.sin(np.radians(data['wind_dir_deg']))
        data['wind_dir_cos'] = np.cos(np.radians(data['wind_dir_deg']))

    hour = data['valid_time'].dt.hour
    day = data['valid_time'].dt.dayofyear
    data['hour_sin'] = np.sin(2 * np.pi * hour / 24)
    data['hour_cos'] = np.cos(2 * np.pi * hour / 24)
    data['day_sin'] = np.sin(2 * np.pi * day / 365.25)
    data['day_cos'] = np.cos(2 * np.pi * day / 365.25)

    if {'t2m_c', 'd2m_c'}.issubset(data.columns):
        data['temp_dewpoint_diff'] = data['t2m_c'] - data['d2m_c']
    if 'msl_hpa' in data.columns:
        data['pressure_gradient'] = groups['msl_hpa'].diff()
    return data

df_train = add_features(df_train)
df_pula = add_features(df_pula)
df_rijeka = add_features(df_rijeka)
print('Broj stupaca nakon feature engineeringa:', df_train.shape[1])

Broj stupaca nakon feature engineeringa: 67

## 5. Future targeti

In [8]:
def add_future_targets(data):
    data = data.sort_values(['latitude', 'longitude', 'valid_time']).copy()
    groups = data.groupby(['latitude', 'longitude'])
    for target in TARGETS:
        if target in data.columns:
            data[f'{target}_future'] = groups[target].shift(-HORIZONT)
    return data

df_train = add_future_targets(df_train)
df_pula = add_future_targets(df_pula)
df_rijeka = add_future_targets(df_rijeka)
for target in TARGETS:
    col = f'{target}_future'
    if col in df_train.columns:
        print(f'{target}: {df_train[col].notna().sum():,} valjanih targeta')

t2m_c: 2,681,784 valjanih targeta
wind_speed_ms: 2,681,784 valjanih targeta
swh: 631,008 valjanih targeta
mwp: 631,008 valjanih targeta
mwd: 631,008 valjanih targeta
sst_c: 1,340,892 valjanih targeta
msl_hpa: 2,681,784 valjanih targeta
tcc: 2,681,784 valjanih targeta
cape: 2,681,784 valjanih targeta
blh: 2,681,784 valjanih targeta

## 6. Priprema featurea i model

In [9]:
DROP_COLUMNS = ['valid_time', 'latitude', 'longitude', 'dist_pula', 'dist_rijeka', 'hour', 'day']

def prepare_X(data, feature_names=None, medians=None):
    drop_cols = [c for c in DROP_COLUMNS if c in data.columns]
    drop_cols += [c for c in data.columns if c.endswith('_future')]
    numeric_cols = data.select_dtypes(include=[np.number]).columns
    selected_cols = [c for c in numeric_cols if c not in drop_cols]

    if feature_names is not None:
        selected_cols = [c for c in feature_names if c in data.columns]

    X = data.loc[:, selected_cols].copy()
    X = X.replace([np.inf, -np.inf], np.nan)
    if medians is None:
        medians = X.median()
    X = X.fillna(medians)

    if feature_names is not None:
        X = X.reindex(columns=feature_names, fill_value=0)

    X = X.astype(np.float32)
    medians = medians.astype(np.float32)
    return X, medians

def make_model(name):
    if name == 'LightGBM':
        return lgb.LGBMRegressor(
            n_estimators=500, learning_rate=0.05, max_depth=10,
            num_leaves=31, min_child_samples=20,
            reg_alpha=0.5, reg_lambda=1.0,
            random_state=RANDOM_STATE, n_jobs=2, verbosity=-1
        )

    if name == 'XGBoost':
        return xgb.XGBRegressor(
            n_estimators=500, learning_rate=0.05, max_depth=8,
            min_child_weight=3, subsample=0.85, colsample_bytree=0.9,
            reg_alpha=0.5, reg_lambda=1.0,
            objective='reg:squarederror', random_state=RANDOM_STATE,
            n_jobs=2, tree_method='hist'
        )

    raise ValueError('MODEL_NAME mora biti LightGBM ili XGBoost')

## 7. Trening jednog targeta

In [10]:
def train_one_target(model_name, target, train_data, test_dict):
    target_col = f'{target}_future'
    if target_col not in train_data.columns:
        print(f'{target}: target ne postoji')
        return None

    valid_idx = train_data[target_col].notna()
    n_valid = int(valid_idx.sum())
    if n_valid < 1000:
        print(f'{target}: preskačem, samo {n_valid} valjanih redaka')
        return None

    target_data = train_data.loc[valid_idx]
    y = target_data[target_col].astype(np.float32)
    X, medians = prepare_X(target_data)
    feature_names = X.columns.tolist()

    cutoff = int(len(X) * (1 - VALIDATION_FRACTION))
    X_fit, X_val = X.iloc[:cutoff], X.iloc[cutoff:]
    y_fit, y_val = y.iloc[:cutoff], y.iloc[cutoff:]

    print(f'{MODEL_NAME}/{target}: treniranje na {len(X_fit):,} redaka i {len(feature_names)} featurea')
    model = make_model(model_name)
    model.fit(X_fit, y_fit)
    pred_val = model.predict(X_val)

    result = {
        'model': model_name,
        'target': target,
        'horizon_hours': HORIZONT,
        'MAE_val': mean_absolute_error(y_val, pred_val),
        'RMSE_val': np.sqrt(mean_squared_error(y_val, pred_val)),
        'R2_val': r2_score(y_val, pred_val),
        'n_train': len(X_fit),
        'n_validation': len(X_val),
        'n_features': len(feature_names)
    }

    for location, test_data in test_dict.items():
        test_valid_idx = test_data[target_col].notna()
        if test_valid_idx.sum() < 10:
            result[f'MAE_{location}'] = np.nan
            result[f'RMSE_{location}'] = np.nan
            result[f'R2_{location}'] = np.nan
            continue

        test_subset = test_data.loc[test_valid_idx]
        X_test, _ = prepare_X(test_subset, feature_names, medians)
        y_test = test_subset[target_col].astype(np.float32)
        pred_test = model.predict(X_test)
        result[f'MAE_{location}'] = mean_absolute_error(y_test, pred_test)
        result[f'RMSE_{location}'] = np.sqrt(mean_squared_error(y_test, pred_test))
        result[f'R2_{location}'] = r2_score(y_test, pred_test)

    print(f"{target}: MAE={result['MAE_val']:.3f}, RMSE={result['RMSE_val']:.3f}, R2={result['R2_val']:.3f}")
    del target_data, X, X_fit, X_val, y, y_fit, y_val, pred_val, model
    if 'X_test' in locals():
        del X_test
    if 'y_test' in locals():
        del y_test
    if 'pred_test' in locals():
        del pred_test
    gc.collect()
    return result

## 8. Pokretanje odabranog modela

In [10]:
if MODEL_NAME not in ['LightGBM', 'XGBoost']:
    raise ValueError('MODEL_NAME mora biti LightGBM ili XGBoost')

test_dict = {'pula': df_pula, 'rijeka': df_rijeka}
results = []

for target in TARGETS:
    result = train_one_target(MODEL_NAME, target, df_train, test_dict)
    if result is not None:
        results.append(result)

results_df = pd.DataFrame(results)
results_df.to_csv(OUTPUT_RESULTS, index=False)
print('\n=== REZULTATI ===')
display(results_df)
print(f'Spremljeno u: {OUTPUT_RESULTS}')

XGBoost/t2m_c: treniranje na 2,413,605 redaka i 62 featurea
t2m_c: MAE=1.187, RMSE=1.567, R2=0.965
XGBoost/wind_speed_ms: treniranje na 2,413,605 redaka i 62 featurea
wind_speed_ms: MAE=0.700, RMSE=0.896, R2=0.489
XGBoost/swh: treniranje na 567,907 redaka i 62 featurea
swh: MAE=0.107, RMSE=0.160, R2=0.737
XGBoost/mwp: treniranje na 567,907 redaka i 62 featurea
mwp: MAE=0.249, RMSE=0.326, R2=0.839
XGBoost/mwd: treniranje na 567,907 redaka i 62 featurea
mwd: MAE=42.258, RMSE=65.155, R2=0.360
XGBoost/sst_c: treniranje na 1,206,802 redaka i 62 featurea
sst_c: MAE=0.149, RMSE=0.257, R2=0.998
XGBoost/msl_hpa: treniranje na 2,413,605 redaka i 62 featurea
msl_hpa: MAE=1.304, RMSE=1.737, R2=0.951
XGBoost/tcc: treniranje na 2,413,605 redaka i 62 featurea
tcc: MAE=0.191, RMSE=0.240, R2=0.597
XGBoost/cape: treniranje na 2,413,605 redaka i 62 featurea
cape: MAE=84.364, RMSE=208.923, R2=0.695
XGBoost/blh: treniranje na 2,413,605 redaka i 62 featurea
blh: MAE=157.420, RMSE=226.985, R2=0.777

=== REZULTATI ===

,model,target,horizon_hours,MAE_val,RMSE_val,R2_val,n_train,n_validation,n_features,MAE_pula,RMSE_pula,R2_pula,MAE_rijeka,RMSE_rijeka,R2_rijeka
0,XGBoost,t2m_c,12,1.187027,1.567361,0.964987,2413605,268179,62,0.535815,0.712913,0.987275,0.913477,1.195605,0.975603
1,XGBoost,wind_speed_ms,12,0.699967,0.896214,0.488842,2413605,268179,62,1.257135,1.643799,0.689290,0.745837,0.980964,0.653582
2,XGBoost,swh,12,0.106542,0.160039,0.737064,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
3,XGBoost,mwp,12,0.248681,0.325990,0.839041,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
4,XGBoost,mwd,12,42.257633,65.154867,0.360047,567907,63101,62,NaN,NaN,NaN,NaN,NaN,NaN
5,XGBoost,sst_c,12,0.148785,0.257010,0.998153,1206802,134090,62,0.080476,0.129849,0.999410,NaN,NaN,NaN
6,XGBoost,msl_hpa,12,1.303655,1.736569,0.951220,2413605,268179,62,0.937559,1.249137,0.973440,0.989978,1.311496,0.969918
7,XGBoost,tcc,12,0.190615,0.240316,0.597187,2413605,268179,62,0.183649,0.228146,0.651888,0.167465,0.212526,0.686012
8,XGBoost,cape,12,84.364494,208.922758,0.694732,2413605,268179,62,120.421532,261.137251,0.863477,77.541100,172.729750,0.747434
9,XGBoost,blh,12,157.420212,226.984787,0.776803,2413605,268179,62,117.658325,163.728959,0.765338,135.917328,194.550353,0.789077

Spremljeno u: xgboost_rezultati_po_targetu.csv

## 9. Optune
+12 sati

In [19]:
import gc
import optuna
import xgboost as xgb

from sklearn.metrics import mean_absolute_error

OPTUNA_TRIALS = 20
OPTUNA_MAX_ROWS = None
XGBOOST_THREADS = 4

In [20]:
def objective_xgboost(trial, target):
    target_col = f'{target}_future'

    valid_idx = df_train[target_col].notna()
    data = df_train.loc[valid_idx]

    if (
        OPTUNA_MAX_ROWS is not None
        and len(data) > OPTUNA_MAX_ROWS
    ):
        data = (
            data
            .sort_values(
                ['valid_time', 'latitude', 'longitude']
            )
            .iloc[:OPTUNA_MAX_ROWS]
        )

    y = data[target_col].astype(np.float32)
    X, _ = prepare_X(data)

    cutoff = int(len(X) * 0.90)

    X_fit = X.iloc[:cutoff]
    X_val = X.iloc[cutoff:]
    y_fit = y.iloc[:cutoff]
    y_val = y.iloc[cutoff:]

    params = {
        'objective': 'reg:squarederror',
        'eval_metric': 'mae',
        'tree_method': 'hist',
        'random_state': RANDOM_STATE,
        'n_jobs': XGBOOST_THREADS,

        'n_estimators': trial.suggest_int(
            'n_estimators',
            200,
            800
        ),

        'max_depth': trial.suggest_int(
            'max_depth',
            3,
            12
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.01,
            0.15,
            log=True
        ),

        'min_child_weight': trial.suggest_int(
            'min_child_weight',
            1,
            20
        ),

        'subsample': trial.suggest_float(
            'subsample',
            0.6,
            1.0
        ),

        'colsample_bytree': trial.suggest_float(
            'colsample_bytree',
            0.6,
            1.0
        ),

        'gamma': trial.suggest_float(
            'gamma',
            0.0,
            5.0
        ),

        'reg_alpha': trial.suggest_float(
            'reg_alpha',
            1e-8,
            10.0,
            log=True
        ),

        'reg_lambda': trial.suggest_float(
            'reg_lambda',
            1e-8,
            10.0,
            log=True
        )
    }

    model = xgb.XGBRegressor(**params)

    model.fit(
        X_fit,
        y_fit,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    pred = model.predict(X_val)

    score = mean_absolute_error(
        y_val,
        pred
    )

    del (
        data,
        X,
        X_fit,
        X_val,
        y,
        y_fit,
        y_val,
        model,
        pred
    )

    gc.collect()

    return score

In [21]:
optuna_results = []
studies_xgb = {}

for target in TARGETS:
    target_col = f'{target}_future'

    if target_col not in df_train.columns:
        print(
            f'{target}: target ne postoji, preskačem.'
        )
        continue

    valid_count = int(
        df_train[target_col].notna().sum()
    )

    if valid_count < 1000:
        print(
            f'{target}: premalo podataka '
            f'({valid_count}), preskačem.'
        )
        continue

    print(
        f'\n===== OPTUNA XGBOOST: {target} ====='
    )

    study = optuna.create_study(
        direction='minimize',
        study_name=f'xgboost_{target}',
        sampler=optuna.samplers.TPESampler(
            seed=RANDOM_STATE
        ),
        pruner=optuna.pruners.MedianPruner(
            n_startup_trials=2,
            n_warmup_steps=10
        )
    )

    study.optimize(
        lambda trial, current_target=target:
            objective_xgboost(
                trial,
                current_target
            ),
        n_trials=OPTUNA_TRIALS,
        show_progress_bar=True
    )

    studies_xgb[target] = study

    optuna_results.append({
        'model': 'XGBoost',
        'target': target,
        'best_MAE_optuna': study.best_value,
        'n_trials': len(study.trials),
        **study.best_params
    })

    print(
        f'Najbolji MAE za {target}: '
        f'{study.best_value:.4f}'
    )

    print(
        'Najbolji parametri:',
        study.best_params
    )

optuna_xgb_df = pd.DataFrame(
    optuna_results
)

optuna_xgb_df.to_csv(
    'xgboost_optuna_svi_targeti.csv',
    index=False
)

print('\n=== XGBOOST OPTUNA REZULTATI ===')
display(optuna_xgb_df)

print(
    '\nSpremljeno u: '
    'xgboost_optuna_svi_targeti.csv'
)

[I 2026-08-22 00:02:52,427] A new study created in memory with name: xgboost_t2m_c

===== OPTUNA XGBOOST: t2m_c =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 00:06:51,550] Trial 0 finished with value: 0.829261302947998 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:09:11,176] Trial 1 finished with value: 1.548059105873108 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:11:15,066] Trial 2 finished with value: 1.4729101657867432 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:14:35,525] Trial 3 finished with value: 1.3980516195297241 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:15:57,851] Trial 4 finished with value: 1.760181188583374 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:18:36,068] Trial 5 finished with value: 1.3742666244506836 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:25:06,149] Trial 6 finished with value: 1.0065226554870605 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:26:49,384] Trial 7 finished with value: 1.5134884119033813 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:28:39,273] Trial 8 finished with value: 1.023614525794983 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:31:30,821] Trial 9 finished with value: 1.5610220432281494 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:36:04,791] Trial 10 finished with value: 1.143650770187378 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:38:59,441] Trial 11 finished with value: 0.83260577917099 and parameters: {'n_estimators': 310, 'max_depth': 12, 'learning_rate': 0.12952647434903777, 'min_child_weight': 6, 'subsample': 0.6125516819803676, 'colsample_bytree': 0.7157343310557601, 'gamma': 1.4246658908701484, 'reg_alpha': 0.0005714450150649899, 'reg_lambda': 0.030416998358199502}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:41:20,692] Trial 12 finished with value: 0.8820174932479858 and parameters: {'n_estimators': 294, 'max_depth': 11, 'learning_rate': 0.13336934049356608, 'min_child_weight': 7, 'subsample': 0.7874820875551369, 'colsample_bytree': 0.7097939893129923, 'gamma': 1.237120888013009, 'reg_alpha': 0.0011215939299723714, 'reg_lambda': 0.008036141722925789}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:44:24,031] Trial 13 finished with value: 0.8467189073562622 and parameters: {'n_estimators': 317, 'max_depth': 12, 'learning_rate': 0.08842106485271407, 'min_child_weight': 12, 'subsample': 0.6010500137420378, 'colsample_bytree': 0.7987586652315627, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0018587284792303666, 'reg_lambda': 2.8826295578488085e-05}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:45:59,481] Trial 14 finished with value: 1.053467035293579 and parameters: {'n_estimators': 207, 'max_depth': 10, 'learning_rate': 0.09579135219572954, 'min_child_weight': 1, 'subsample': 0.7653656398770851, 'colsample_bytree': 0.679470827688202, 'gamma': 2.7939929152165717, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 0.020731066374983308}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:48:23,300] Trial 15 finished with value: 0.9666301608085632 and parameters: {'n_estimators': 357, 'max_depth': 10, 'learning_rate': 0.09709009425386972, 'min_child_weight': 7, 'subsample': 0.6035282881374231, 'colsample_bytree': 0.7762529447068269, 'gamma': 0.607931398480069, 'reg_alpha': 5.3230633483088404e-05, 'reg_lambda': 6.243069797304142}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:51:37,801] Trial 16 finished with value: 0.9895022511482239 and parameters: {'n_estimators': 287, 'max_depth': 12, 'learning_rate': 0.029205162116593908, 'min_child_weight': 9, 'subsample': 0.8517314664119261, 'colsample_bytree': 0.6826875535866854, 'gamma': 1.4823991842849025, 'reg_alpha': 1.7578071939504844e-08, 'reg_lambda': 1.314053143275926e-08}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:54:12,379] Trial 17 finished with value: 1.0421836376190186 and parameters: {'n_estimators': 472, 'max_depth': 8, 'learning_rate': 0.13937749501487037, 'min_child_weight': 15, 'subsample': 0.7178714526143911, 'colsample_bytree': 0.8571389722362222, 'gamma': 0.4105245223196716, 'reg_alpha': 0.023399150597452085, 'reg_lambda': 0.017876389200129985}. Best is trial 0 with value: 0.829261302947998.
[I 2026-08-22 00:59:17,365] Trial 18 finished with value: 0.809330403804779 and parameters: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.08847732101009222, 'min_child_weight': 5, 'subsample': 0.6390797754821066, 'colsample_bytree': 0.611988261776482, 'gamma': 1.3289134156775693, 'reg_alpha': 5.3651636151287245e-05, 'reg_lambda': 3.288497044437589e-05}. Best is trial 18 with value: 0.809330403804779.

[I 2026-08-22 01:03:46,150] A new study created in memory with name: xgboost_wind_speed_ms

[I 2026-08-22 01:03:46,088] Trial 19 finished with value: 0.8698877692222595 and parameters: {'n_estimators': 796, 'max_depth': 10, 'learning_rate': 0.07918955706490971, 'min_child_weight': 20, 'subsample': 0.7640881690357239, 'colsample_bytree': 0.6028550510494292, 'gamma': 2.491025122658857, 'reg_alpha': 2.996171735739825e-06, 'reg_lambda': 2.0335131341271068e-05}. Best is trial 18 with value: 0.809330403804779.
Najbolji MAE za t2m_c: 0.8093
Najbolji parametri: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.08847732101009222, 'min_child_weight': 5, 'subsample': 0.6390797754821066, 'colsample_bytree': 0.611988261776482, 'gamma': 1.3289134156775693, 'reg_alpha': 5.3651636151287245e-05, 'reg_lambda': 3.288497044437589e-05}

===== OPTUNA XGBOOST: wind_speed_ms =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 01:07:17,140] Trial 0 finished with value: 0.5567073225975037 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:09:25,956] Trial 1 finished with value: 0.8181208968162537 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:11:21,354] Trial 2 finished with value: 0.7895111441612244 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:14:25,695] Trial 3 finished with value: 0.783169686794281 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:15:51,384] Trial 4 finished with value: 0.8520338535308838 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:18:28,212] Trial 5 finished with value: 0.7600694298744202 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:24:23,739] Trial 6 finished with value: 0.6668263077735901 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:26:11,746] Trial 7 finished with value: 0.8043941259384155 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:27:55,756] Trial 8 finished with value: 0.6549277901649475 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:30:44,263] Trial 9 finished with value: 0.8155654072761536 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:35:11,846] Trial 10 finished with value: 0.6894689202308655 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:37:13,168] Trial 11 finished with value: 0.5926566123962402 and parameters: {'n_estimators': 203, 'max_depth': 12, 'learning_rate': 0.10542678149087867, 'min_child_weight': 14, 'subsample': 0.9893423339815978, 'colsample_bytree': 0.6945056225999373, 'gamma': 1.4745556332503273, 'reg_alpha': 1.8228271043666355e-08, 'reg_lambda': 9.665507853342099}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:38:56,267] Trial 12 finished with value: 0.6066334247589111 and parameters: {'n_estimators': 207, 'max_depth': 11, 'learning_rate': 0.12737604190876714, 'min_child_weight': 13, 'subsample': 0.9971317477907701, 'colsample_bytree': 0.7094975278484695, 'gamma': 1.237120888013009, 'reg_alpha': 0.0013416587554225506, 'reg_lambda': 0.010254357357008588}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:41:47,987] Trial 13 finished with value: 0.5686672925949097 and parameters: {'n_estimators': 309, 'max_depth': 12, 'learning_rate': 0.09628063571908314, 'min_child_weight': 20, 'subsample': 0.775110409899155, 'colsample_bytree': 0.7987586652315627, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0004699196295925314, 'reg_lambda': 9.66779358979949}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:44:01,600] Trial 14 finished with value: 0.6287495493888855 and parameters: {'n_estimators': 322, 'max_depth': 10, 'learning_rate': 0.0891988796993311, 'min_child_weight': 20, 'subsample': 0.8033823694924689, 'colsample_bytree': 0.7908165351556822, 'gamma': 0.8747179243142184, 'reg_alpha': 0.0019013872412140544, 'reg_lambda': 1.0374653956916587e-05}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:46:24,092] Trial 15 finished with value: 0.714257001876831 and parameters: {'n_estimators': 283, 'max_depth': 10, 'learning_rate': 0.02807215632195136, 'min_child_weight': 17, 'subsample': 0.7794192227560304, 'colsample_bytree': 0.9074355033641801, 'gamma': 0.4125844921414529, 'reg_alpha': 4.5012664001523424e-05, 'reg_lambda': 0.018867726849009354}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:49:33,250] Trial 16 finished with value: 0.5709983706474304 and parameters: {'n_estimators': 320, 'max_depth': 12, 'learning_rate': 0.08099809739025919, 'min_child_weight': 7, 'subsample': 0.6028057255364521, 'colsample_bytree': 0.8064114554738081, 'gamma': 2.382525301925182, 'reg_alpha': 0.02316062671984357, 'reg_lambda': 1.314053143275926e-08}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:51:50,189] Trial 17 finished with value: 0.7405019998550415 and parameters: {'n_estimators': 388, 'max_depth': 8, 'learning_rate': 0.031195021944056264, 'min_child_weight': 10, 'subsample': 0.7521865606498155, 'colsample_bytree': 0.9975779961884794, 'gamma': 0.7207316966706379, 'reg_alpha': 0.021771694669350503, 'reg_lambda': 8.911946129189984}. Best is trial 0 with value: 0.5567073225975037.
[I 2026-08-22 01:56:13,047] Trial 18 finished with value: 0.5469835996627808 and parameters: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.10796100656646772, 'min_child_weight': 1, 'subsample': 0.8505919001558102, 'colsample_bytree': 0.7613495462127717, 'gamma': 2.819873495107165, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 3.9233028601151885e-05}. Best is trial 18 with value: 0.5469835996627808.

[I 2026-08-22 02:03:08,278] A new study created in memory with name: xgboost_swh

[I 2026-08-22 02:03:08,245] Trial 19 finished with value: 0.584355354309082 and parameters: {'n_estimators': 796, 'max_depth': 10, 'learning_rate': 0.06193229498222443, 'min_child_weight': 1, 'subsample': 0.879713599128111, 'colsample_bytree': 0.6693761544549911, 'gamma': 3.1631519638115915, 'reg_alpha': 2.726680493037923e-05, 'reg_lambda': 2.347372757484223e-05}. Best is trial 18 with value: 0.5469835996627808.
Najbolji MAE za wind_speed_ms: 0.5470
Najbolji parametri: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.10796100656646772, 'min_child_weight': 1, 'subsample': 0.8505919001558102, 'colsample_bytree': 0.7613495462127717, 'gamma': 2.819873495107165, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 3.9233028601151885e-05}

===== OPTUNA XGBOOST: swh =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 02:03:43,897] Trial 0 finished with value: 0.10752235352993011 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:04:13,684] Trial 1 finished with value: 0.12580114603042603 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:04:39,127] Trial 2 finished with value: 0.12545323371887207 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:05:18,778] Trial 3 finished with value: 0.1255480945110321 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:05:39,911] Trial 4 finished with value: 0.13002128899097443 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:06:10,678] Trial 5 finished with value: 0.1254344880580902 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:07:09,625] Trial 6 finished with value: 0.11747490614652634 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:07:32,080] Trial 7 finished with value: 0.12777745723724365 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:07:49,926] Trial 8 finished with value: 0.11681978404521942 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:08:30,417] Trial 9 finished with value: 0.1259324848651886 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.10752235352993011.
[I 2026-08-22 02:09:47,113] Trial 10 finished with value: 0.10566835850477219 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 10 with value: 0.10566835850477219.
[I 2026-08-22 02:11:17,833] Trial 11 finished with value: 0.10162783414125443 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.024196351546920826, 'min_child_weight': 20, 'subsample': 0.8132534049828819, 'colsample_bytree': 0.8501648288953945, 'gamma': 0.055191260763265304, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:12:07,566] Trial 12 finished with value: 0.11397609859704971 and parameters: {'n_estimators': 781, 'max_depth': 9, 'learning_rate': 0.023213805338695312, 'min_child_weight': 20, 'subsample': 0.8255837328692512, 'colsample_bytree': 0.864051766083234, 'gamma': 1.0361528159684317, 'reg_alpha': 0.0020754746955332242, 'reg_lambda': 0.0047998091593526235}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:13:21,143] Trial 13 finished with value: 0.10453954339027405 and parameters: {'n_estimators': 798, 'max_depth': 9, 'learning_rate': 0.024326059172018105, 'min_child_weight': 20, 'subsample': 0.8080681369590864, 'colsample_bytree': 0.8819931368477596, 'gamma': 0.09895182931374312, 'reg_alpha': 0.0005159741212465761, 'reg_lambda': 3.367900636171438e-05}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:14:07,917] Trial 14 finished with value: 0.11280832439661026 and parameters: {'n_estimators': 695, 'max_depth': 10, 'learning_rate': 0.028066980977526187, 'min_child_weight': 17, 'subsample': 0.7955977689583446, 'colsample_bytree': 0.9301176317245845, 'gamma': 0.9752126721116727, 'reg_alpha': 0.0007268692929601876, 'reg_lambda': 1.5792316516215277e-05}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:15:02,303] Trial 15 finished with value: 0.11376374214887619 and parameters: {'n_estimators': 709, 'max_depth': 8, 'learning_rate': 0.017858009493631068, 'min_child_weight': 20, 'subsample': 0.7794192227560304, 'colsample_bytree': 0.8038561264448121, 'gamma': 0.6623362983487808, 'reg_alpha': 8.072907701290074e-05, 'reg_lambda': 2.5364131671778664e-05}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:15:42,114] Trial 16 finished with value: 0.11492322385311127 and parameters: {'n_estimators': 697, 'max_depth': 10, 'learning_rate': 0.03309010759962604, 'min_child_weight': 17, 'subsample': 0.8659132989410139, 'colsample_bytree': 0.9551097883344569, 'gamma': 1.5485038985835824, 'reg_alpha': 0.01680941779078386, 'reg_lambda': 1.314053143275926e-08}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:16:27,694] Trial 17 finished with value: 0.1199583113193512 and parameters: {'n_estimators': 794, 'max_depth': 8, 'learning_rate': 0.017616049678997204, 'min_child_weight': 15, 'subsample': 0.8758697700847069, 'colsample_bytree': 0.8160380080454375, 'gamma': 2.533881284358335, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 0.024211110495137914}. Best is trial 11 with value: 0.10162783414125443.
[I 2026-08-22 02:17:54,883] Trial 18 finished with value: 0.10530991107225418 and parameters: {'n_estimators': 725, 'max_depth': 10, 'learning_rate': 0.01739171613608345, 'min_child_weight': 18, 'subsample': 0.7517911482260485, 'colsample_bytree': 0.898455323922507, 'gamma': 0.018051077679181113, 'reg_alpha': 0.0050543255000474316, 'reg_lambda': 4.8307065066771676e-05}. Best is trial 11 with value: 0.10162783414125443.

[I 2026-08-22 02:18:21,387] A new study created in memory with name: xgboost_mwp

[I 2026-08-22 02:18:21,377] Trial 19 finished with value: 0.11915934830904007 and parameters: {'n_estimators': 646, 'max_depth': 7, 'learning_rate': 0.10823636496197418, 'min_child_weight': 15, 'subsample': 0.9630719769443198, 'colsample_bytree': 0.7547991153247873, 'gamma': 1.315704134017843, 'reg_alpha': 6.232902146709707e-05, 'reg_lambda': 0.0424247819777685}. Best is trial 11 with value: 0.10162783414125443.
Najbolji MAE za swh: 0.1016
Najbolji parametri: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.024196351546920826, 'min_child_weight': 20, 'subsample': 0.8132534049828819, 'colsample_bytree': 0.8501648288953945, 'gamma': 0.055191260763265304, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}

===== OPTUNA XGBOOST: mwp =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 02:19:10,413] Trial 0 finished with value: 0.24069631099700928 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:19:40,180] Trial 1 finished with value: 0.27810585498809814 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:20:08,035] Trial 2 finished with value: 0.2754325568675995 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:20:53,739] Trial 3 finished with value: 0.27653825283050537 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:21:13,630] Trial 4 finished with value: 0.2894906997680664 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:21:47,762] Trial 5 finished with value: 0.27367448806762695 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:23:17,926] Trial 6 finished with value: 0.25553861260414124 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:23:42,250] Trial 7 finished with value: 0.2809302508831024 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:24:05,061] Trial 8 finished with value: 0.25502726435661316 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:24:47,399] Trial 9 finished with value: 0.28153911232948303 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:26:04,530] Trial 10 finished with value: 0.24775515496730804 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.24069631099700928.
[I 2026-08-22 02:27:45,102] Trial 11 finished with value: 0.23923465609550476 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.024196351546920826, 'min_child_weight': 20, 'subsample': 0.8132534049828819, 'colsample_bytree': 0.8501648288953945, 'gamma': 0.055191260763265304, 'reg_alpha': 0.0010740184901328143, 'reg_lambda': 0.002114232397037538}. Best is trial 11 with value: 0.23923465609550476.
[I 2026-08-22 02:28:23,959] Trial 12 finished with value: 0.2506462633609772 and parameters: {'n_estimators': 757, 'max_depth': 10, 'learning_rate': 0.13343285407790653, 'min_child_weight': 20, 'subsample': 0.7874820875551369, 'colsample_bytree': 0.9487283159585305, 'gamma': 1.0361528159684317, 'reg_alpha': 0.0020781973056227185, 'reg_lambda': 0.008036141722925789}. Best is trial 11 with value: 0.23923465609550476.
[I 2026-08-22 02:29:35,169] Trial 13 finished with value: 0.2520264685153961 and parameters: {'n_estimators': 290, 'max_depth': 12, 'learning_rate': 0.021577899865583592, 'min_child_weight': 15, 'subsample': 0.973505717859356, 'colsample_bytree': 0.8255773609241618, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0016611361345790158, 'reg_lambda': 5.797848390044669e-05}. Best is trial 11 with value: 0.23923465609550476.
[I 2026-08-22 02:30:39,454] Trial 14 finished with value: 0.23163780570030212 and parameters: {'n_estimators': 682, 'max_depth': 10, 'learning_rate': 0.09238461825504664, 'min_child_weight': 8, 'subsample': 0.7982817805723873, 'colsample_bytree': 0.7312816737400367, 'gamma': 0.1175093715734351, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 0.02209753057171327}. Best is trial 14 with value: 0.23163780570030212.
[I 2026-08-22 02:31:32,385] Trial 15 finished with value: 0.25719571113586426 and parameters: {'n_estimators': 689, 'max_depth': 8, 'learning_rate': 0.02687398638133187, 'min_child_weight': 7, 'subsample': 0.8183135357109333, 'colsample_bytree': 0.7604022083276454, 'gamma': 1.416446516401817, 'reg_alpha': 0.00017030177671959864, 'reg_lambda': 0.023835528711847923}. Best is trial 14 with value: 0.23163780570030212.
[I 2026-08-22 02:32:15,965] Trial 16 finished with value: 0.2465572953224182 and parameters: {'n_estimators': 697, 'max_depth': 10, 'learning_rate': 0.09713478796027714, 'min_child_weight': 1, 'subsample': 0.8659132989410139, 'colsample_bytree': 0.9003988944050103, 'gamma': 0.6202394596177677, 'reg_alpha': 0.01680941779078386, 'reg_lambda': 1.314053143275926e-08}. Best is trial 14 with value: 0.23163780570030212.
[I 2026-08-22 02:33:04,884] Trial 17 finished with value: 0.2607267200946808 and parameters: {'n_estimators': 791, 'max_depth': 9, 'learning_rate': 0.03208122418549758, 'min_child_weight': 17, 'subsample': 0.7723541598778946, 'colsample_bytree': 0.7163774348253532, 'gamma': 2.533881284358335, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 8.21825253745345}. Best is trial 14 with value: 0.23163780570030212.
[I 2026-08-22 02:34:44,697] Trial 18 finished with value: 0.24783490598201752 and parameters: {'n_estimators': 717, 'max_depth': 10, 'learning_rate': 0.0164279671863374, 'min_child_weight': 9, 'subsample': 0.8693241788465282, 'colsample_bytree': 0.8005828061689466, 'gamma': 0.01827275711178969, 'reg_alpha': 0.0062133129207280185, 'reg_lambda': 2.5191824309949668e-05}. Best is trial 14 with value: 0.23163780570030212.

[I 2026-08-22 02:35:19,897] A new study created in memory with name: xgboost_mwd

[I 2026-08-22 02:35:19,886] Trial 19 finished with value: 0.25671258568763733 and parameters: {'n_estimators': 646, 'max_depth': 8, 'learning_rate': 0.09411145042852655, 'min_child_weight': 6, 'subsample': 0.7595141750400702, 'colsample_bytree': 0.6925137134710048, 'gamma': 1.3250599658996856, 'reg_alpha': 5.799449092292779e-05, 'reg_lambda': 0.03089981338322704}. Best is trial 14 with value: 0.23163780570030212.
Najbolji MAE za mwp: 0.2316
Najbolji parametri: {'n_estimators': 682, 'max_depth': 10, 'learning_rate': 0.09238461825504664, 'min_child_weight': 8, 'subsample': 0.7982817805723873, 'colsample_bytree': 0.7312816737400367, 'gamma': 0.1175093715734351, 'reg_alpha': 0.015936847132186974, 'reg_lambda': 0.02209753057171327}

===== OPTUNA XGBOOST: mwd =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 02:36:34,305] Trial 0 finished with value: 41.31730651855469 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:37:04,763] Trial 1 finished with value: 46.00246810913086 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:37:32,516] Trial 2 finished with value: 44.81797409057617 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:38:24,755] Trial 3 finished with value: 44.159610748291016 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:38:45,101] Trial 4 finished with value: 47.4955940246582 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:39:23,887] Trial 5 finished with value: 43.788787841796875 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:41:49,074] Trial 6 finished with value: 41.44309997558594 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:42:13,715] Trial 7 finished with value: 45.23769760131836 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:42:46,495] Trial 8 finished with value: 41.58372116088867 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:43:27,435] Trial 9 finished with value: 45.411659240722656 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:44:42,660] Trial 10 finished with value: 41.74137496948242 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:45:44,433] Trial 11 finished with value: 42.866493225097656 and parameters: {'n_estimators': 310, 'max_depth': 12, 'learning_rate': 0.12952647434903777, 'min_child_weight': 6, 'subsample': 0.6125516819803676, 'colsample_bytree': 0.7157343310557601, 'gamma': 1.4246658908701484, 'reg_alpha': 0.0005714450150649899, 'reg_lambda': 0.030416998358199502}. Best is trial 0 with value: 41.31730651855469.
[I 2026-08-22 02:48:03,710] Trial 12 finished with value: 41.006919860839844 and parameters: {'n_estimators': 714, 'max_depth': 11, 'learning_rate': 0.02137199952684738, 'min_child_weight': 1, 'subsample': 0.7874820875551369, 'colsample_bytree': 0.741581311842964, 'gamma': 2.698100534013988, 'reg_alpha': 2.0057322817130592e-08, 'reg_lambda': 0.011009732315503996}. Best is trial 12 with value: 41.006919860839844.
[I 2026-08-22 02:49:54,942] Trial 13 finished with value: 41.130855560302734 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.026806587885655573, 'min_child_weight': 1, 'subsample': 0.7870417477164727, 'colsample_bytree': 0.79126871900385, 'gamma': 2.777459525821401, 'reg_alpha': 0.0014756964462303843, 'reg_lambda': 0.008180905933464117}. Best is trial 12 with value: 41.006919860839844.
[I 2026-08-22 02:51:46,876] Trial 14 finished with value: 41.21173095703125 and parameters: {'n_estimators': 793, 'max_depth': 10, 'learning_rate': 0.02552814562399475, 'min_child_weight': 1, 'subsample': 0.8064683779951184, 'colsample_bytree': 0.8124496121405841, 'gamma': 2.8685506993648557, 'reg_alpha': 6.896447494014971e-08, 'reg_lambda': 2.6074749606932284e-05}. Best is trial 12 with value: 41.006919860839844.
[I 2026-08-22 02:53:04,657] Trial 15 finished with value: 41.88725662231445 and parameters: {'n_estimators': 715, 'max_depth': 9, 'learning_rate': 0.021724448812058386, 'min_child_weight': 1, 'subsample': 0.8086053787969886, 'colsample_bytree': 0.8023762036212838, 'gamma': 3.427827396827184, 'reg_alpha': 0.0011129597405245765, 'reg_lambda': 6.243069797304142}. Best is trial 12 with value: 41.006919860839844.
[I 2026-08-22 02:54:46,450] Trial 16 finished with value: 41.3474006652832 and parameters: {'n_estimators': 697, 'max_depth': 10, 'learning_rate': 0.029982029658052384, 'min_child_weight': 1, 'subsample': 0.8642396983313831, 'colsample_bytree': 0.9083213706356454, 'gamma': 2.438361916505133, 'reg_alpha': 1.259211722475341e-05, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 41.006919860839844.
[I 2026-08-22 02:55:47,702] Trial 17 finished with value: 42.927268981933594 and parameters: {'n_estimators': 687, 'max_depth': 8, 'learning_rate': 0.016890543551463393, 'min_child_weight': 5, 'subsample': 0.7627490790695939, 'colsample_bytree': 0.7657424750331814, 'gamma': 4.0699685278891575, 'reg_alpha': 0.009319790049463426, 'reg_lambda': 0.015249917522789886}. Best is trial 12 with value: 41.006919860839844.
[I 2026-08-22 02:57:22,217] Trial 18 finished with value: 41.53779983520508 and parameters: {'n_estimators': 728, 'max_depth': 10, 'learning_rate': 0.01707177535509862, 'min_child_weight': 8, 'subsample': 0.7631807696410763, 'colsample_bytree': 0.69043921638584, 'gamma': 2.8198734951071645, 'reg_alpha': 4.043233571530631e-05, 'reg_lambda': 0.00950928530897988}. Best is trial 12 with value: 41.006919860839844.

[I 2026-08-22 02:59:17,141] A new study created in memory with name: xgboost_sst_c

[I 2026-08-22 02:59:17,127] Trial 19 finished with value: 40.8077278137207 and parameters: {'n_estimators': 658, 'max_depth': 11, 'learning_rate': 0.03530637940808436, 'min_child_weight': 3, 'subsample': 0.866105019164601, 'colsample_bytree': 0.8587134049704088, 'gamma': 3.7506953845182176, 'reg_alpha': 3.35918377898784e-07, 'reg_lambda': 6.851002911379474e-05}. Best is trial 19 with value: 40.8077278137207.
Najbolji MAE za mwd: 40.8077
Najbolji parametri: {'n_estimators': 658, 'max_depth': 11, 'learning_rate': 0.03530637940808436, 'min_child_weight': 3, 'subsample': 0.866105019164601, 'colsample_bytree': 0.8587134049704088, 'gamma': 3.7506953845182176, 'reg_alpha': 3.35918377898784e-07, 'reg_lambda': 6.851002911379474e-05}

===== OPTUNA XGBOOST: sst_c =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 03:00:35,578] Trial 0 finished with value: 0.18978382647037506 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.18978382647037506.
[I 2026-08-22 03:01:39,750] Trial 1 finished with value: 0.17968212068080902 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 1 with value: 0.17968212068080902.
[I 2026-08-22 03:02:38,737] Trial 2 finished with value: 0.17217454314231873 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 2 with value: 0.17217454314231873.
[I 2026-08-22 03:04:16,863] Trial 3 finished with value: 0.22350358963012695 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 2 with value: 0.17217454314231873.
[I 2026-08-22 03:05:00,379] Trial 4 finished with value: 0.19583173096179962 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 2 with value: 0.17217454314231873.
[I 2026-08-22 03:06:07,748] Trial 5 finished with value: 0.15536291897296906 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 5 with value: 0.15536291897296906.
[I 2026-08-22 03:08:37,698] Trial 6 finished with value: 0.18741436302661896 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 5 with value: 0.15536291897296906.
[I 2026-08-22 03:09:30,644] Trial 7 finished with value: 0.1910710334777832 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 5 with value: 0.15536291897296906.
[I 2026-08-22 03:10:16,757] Trial 8 finished with value: 0.20533506572246552 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 5 with value: 0.15536291897296906.
[I 2026-08-22 03:11:45,455] Trial 9 finished with value: 0.1703544706106186 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 5 with value: 0.15536291897296906.
[I 2026-08-22 03:13:22,785] Trial 10 finished with value: 0.14807195961475372 and parameters: {'n_estimators': 780, 'max_depth': 9, 'learning_rate': 0.02558578360568248, 'min_child_weight': 19, 'subsample': 0.807513758853419, 'colsample_bytree': 0.9630659181130071, 'gamma': 3.7215085517650985, 'reg_alpha': 0.0025108089673929043, 'reg_lambda': 4.045675576808379}. Best is trial 10 with value: 0.14807195961475372.
[I 2026-08-22 03:14:59,966] Trial 11 finished with value: 0.14731071889400482 and parameters: {'n_estimators': 799, 'max_depth': 9, 'learning_rate': 0.02622984807833444, 'min_child_weight': 20, 'subsample': 0.8142497056141959, 'colsample_bytree': 0.9986108681785297, 'gamma': 3.766897787133911, 'reg_alpha': 0.001628978887614627, 'reg_lambda': 9.76819173887543}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:16:43,585] Trial 12 finished with value: 0.1473638117313385 and parameters: {'n_estimators': 781, 'max_depth': 9, 'learning_rate': 0.02242557993058527, 'min_child_weight': 20, 'subsample': 0.8095280321215779, 'colsample_bytree': 0.9831228282608743, 'gamma': 3.5058129769688, 'reg_alpha': 0.0005210863481270706, 'reg_lambda': 9.048802222204392}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:18:25,370] Trial 13 finished with value: 0.15198956429958344 and parameters: {'n_estimators': 798, 'max_depth': 9, 'learning_rate': 0.022998468248775716, 'min_child_weight': 20, 'subsample': 0.8176014694418943, 'colsample_bytree': 0.9176100055591068, 'gamma': 3.1875866254489016, 'reg_alpha': 0.0006729008001050692, 'reg_lambda': 9.78455613014293}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:20:08,574] Trial 14 finished with value: 0.15997745096683502 and parameters: {'n_estimators': 693, 'max_depth': 10, 'learning_rate': 0.019823839746988977, 'min_child_weight': 17, 'subsample': 0.8293394456463015, 'colsample_bytree': 0.8870654488898001, 'gamma': 4.0628512776184875, 'reg_alpha': 0.000733064344570866, 'reg_lambda': 0.02209753057171327}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:21:36,473] Trial 15 finished with value: 0.1534576117992401 and parameters: {'n_estimators': 709, 'max_depth': 8, 'learning_rate': 0.029354861455358663, 'min_child_weight': 20, 'subsample': 0.8593576514596838, 'colsample_bytree': 0.9423948071828998, 'gamma': 2.6800789700187573, 'reg_alpha': 8.14177029444509e-05, 'reg_lambda': 0.02211592643670399}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:23:19,159] Trial 16 finished with value: 0.1507844477891922 and parameters: {'n_estimators': 697, 'max_depth': 8, 'learning_rate': 0.017914451441176062, 'min_child_weight': 17, 'subsample': 0.7732828462592263, 'colsample_bytree': 0.9932127280367035, 'gamma': 4.3386206161845555, 'reg_alpha': 0.006469155524473248, 'reg_lambda': 1.314053143275926e-08}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:24:50,706] Trial 17 finished with value: 0.15714076161384583 and parameters: {'n_estimators': 739, 'max_depth': 10, 'learning_rate': 0.03335446477106572, 'min_child_weight': 15, 'subsample': 0.8758697700847069, 'colsample_bytree': 0.8571389722362222, 'gamma': 3.268548079220718, 'reg_alpha': 9.895037986900042e-06, 'reg_lambda': 9.719326626152897}. Best is trial 11 with value: 0.14731071889400482.
[I 2026-08-22 03:26:34,363] Trial 18 finished with value: 0.16468875110149384 and parameters: {'n_estimators': 652, 'max_depth': 7, 'learning_rate': 0.0164279671863374, 'min_child_weight': 18, 'subsample': 0.7742830835268095, 'colsample_bytree': 0.8366070683982902, 'gamma': 2.8162360136018108, 'reg_alpha': 7.332844200411086e-05, 'reg_lambda': 0.08203290617558147}. Best is trial 11 with value: 0.14731071889400482.

[I 2026-08-22 03:27:45,072] A new study created in memory with name: xgboost_msl_hpa

[I 2026-08-22 03:27:45,056] Trial 19 finished with value: 0.15043210983276367 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.10823636496197418, 'min_child_weight': 15, 'subsample': 0.9637642844426868, 'colsample_bytree': 0.9430412756964037, 'gamma': 4.3558730626951725, 'reg_alpha': 0.036476222583722955, 'reg_lambda': 1.5474904443249629}. Best is trial 11 with value: 0.14731071889400482.
Najbolji MAE za sst_c: 0.1473
Najbolji parametri: {'n_estimators': 799, 'max_depth': 9, 'learning_rate': 0.02622984807833444, 'min_child_weight': 20, 'subsample': 0.8142497056141959, 'colsample_bytree': 0.9986108681785297, 'gamma': 3.766897787133911, 'reg_alpha': 0.001628978887614627, 'reg_lambda': 9.76819173887543}

===== OPTUNA XGBOOST: msl_hpa =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 03:32:07,655] Trial 0 finished with value: 0.8031719326972961 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:34:20,075] Trial 1 finished with value: 1.6743848323822021 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:36:16,875] Trial 2 finished with value: 1.6429446935653687 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:39:35,925] Trial 3 finished with value: 1.6402772665023804 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:41:04,571] Trial 4 finished with value: 1.8053982257843018 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:43:46,483] Trial 5 finished with value: 1.5363386869430542 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:50:23,013] Trial 6 finished with value: 1.1357437372207642 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:52:10,447] Trial 7 finished with value: 1.6861391067504883 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:54:03,990] Trial 8 finished with value: 1.1127212047576904 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 03:57:00,935] Trial 9 finished with value: 1.758370041847229 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:01:43,883] Trial 10 finished with value: 1.2636603116989136 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:03:58,596] Trial 11 finished with value: 0.9162648320198059 and parameters: {'n_estimators': 203, 'max_depth': 12, 'learning_rate': 0.10542678149087867, 'min_child_weight': 14, 'subsample': 0.9893423339815978, 'colsample_bytree': 0.6945056225999373, 'gamma': 1.4745556332503273, 'reg_alpha': 1.8228271043666355e-08, 'reg_lambda': 9.665507853342099}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:05:50,958] Trial 12 finished with value: 0.9443607330322266 and parameters: {'n_estimators': 207, 'max_depth': 11, 'learning_rate': 0.12737604190876714, 'min_child_weight': 13, 'subsample': 0.9971317477907701, 'colsample_bytree': 0.7094975278484695, 'gamma': 1.237120888013009, 'reg_alpha': 0.0013416587554225506, 'reg_lambda': 0.010254357357008588}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:09:01,992] Trial 13 finished with value: 0.8526541590690613 and parameters: {'n_estimators': 309, 'max_depth': 12, 'learning_rate': 0.09628063571908314, 'min_child_weight': 20, 'subsample': 0.775110409899155, 'colsample_bytree': 0.7987586652315627, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0004699196295925314, 'reg_lambda': 9.66779358979949}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:11:27,085] Trial 14 finished with value: 1.032252311706543 and parameters: {'n_estimators': 322, 'max_depth': 10, 'learning_rate': 0.0891988796993311, 'min_child_weight': 20, 'subsample': 0.8033823694924689, 'colsample_bytree': 0.7908165351556822, 'gamma': 0.8747179243142184, 'reg_alpha': 0.0019013872412140544, 'reg_lambda': 1.0374653956916587e-05}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:13:49,513] Trial 15 finished with value: 1.349897027015686 and parameters: {'n_estimators': 283, 'max_depth': 10, 'learning_rate': 0.02807215632195136, 'min_child_weight': 17, 'subsample': 0.7794192227560304, 'colsample_bytree': 0.9074355033641801, 'gamma': 0.4125844921414529, 'reg_alpha': 4.5012664001523424e-05, 'reg_lambda': 0.018867726849009354}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:17:15,678] Trial 16 finished with value: 0.8421760201454163 and parameters: {'n_estimators': 320, 'max_depth': 12, 'learning_rate': 0.08099809739025919, 'min_child_weight': 7, 'subsample': 0.6028057255364521, 'colsample_bytree': 0.8064114554738081, 'gamma': 2.382525301925182, 'reg_alpha': 0.02316062671984357, 'reg_lambda': 1.314053143275926e-08}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:19:33,323] Trial 17 finished with value: 1.4847187995910645 and parameters: {'n_estimators': 365, 'max_depth': 8, 'learning_rate': 0.03208122418549758, 'min_child_weight': 7, 'subsample': 0.6023225603594583, 'colsample_bytree': 0.9979247097869253, 'gamma': 2.533881284358335, 'reg_alpha': 0.01302385938648125, 'reg_lambda': 2.1241764509077783e-08}. Best is trial 0 with value: 0.8031719326972961.
[I 2026-08-22 04:23:37,863] Trial 18 finished with value: 0.8779272437095642 and parameters: {'n_estimators': 466, 'max_depth': 11, 'learning_rate': 0.0686801234654511, 'min_child_weight': 10, 'subsample': 0.6303823831112678, 'colsample_bytree': 0.8366070683982902, 'gamma': 3.264423346529435, 'reg_alpha': 0.08842639708590463, 'reg_lambda': 1.807370831354258e-08}. Best is trial 0 with value: 0.8031719326972961.

[I 2026-08-22 04:28:52,789] A new study created in memory with name: xgboost_tcc

[I 2026-08-22 04:28:52,746] Trial 19 finished with value: 1.2411119937896729 and parameters: {'n_estimators': 680, 'max_depth': 10, 'learning_rate': 0.01725130662747314, 'min_child_weight': 1, 'subsample': 0.7211422591005, 'colsample_bytree': 0.920719297129556, 'gamma': 2.9111046405876935, 'reg_alpha': 0.01891109431558191, 'reg_lambda': 7.84423842617657e-05}. Best is trial 0 with value: 0.8031719326972961.
Najbolji MAE za msl_hpa: 0.8032
Najbolji parametri: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}

===== OPTUNA XGBOOST: tcc =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 04:31:52,279] Trial 0 finished with value: 0.15107722580432892 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:34:04,370] Trial 1 finished with value: 0.2289469838142395 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:36:01,875] Trial 2 finished with value: 0.22559568285942078 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:39:08,431] Trial 3 finished with value: 0.22618167102336884 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:40:37,680] Trial 4 finished with value: 0.24159307777881622 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:43:08,146] Trial 5 finished with value: 0.22113005816936493 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:48:02,955] Trial 6 finished with value: 0.1866828203201294 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:49:50,212] Trial 7 finished with value: 0.2302975356578827 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:51:14,964] Trial 8 finished with value: 0.18496465682983398 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:54:04,568] Trial 9 finished with value: 0.23531381785869598 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:58:39,265] Trial 10 finished with value: 0.18683426082134247 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 04:59:54,688] Trial 11 finished with value: 0.1773780733346939 and parameters: {'n_estimators': 203, 'max_depth': 12, 'learning_rate': 0.10542678149087867, 'min_child_weight': 14, 'subsample': 0.9893423339815978, 'colsample_bytree': 0.6945056225999373, 'gamma': 1.4745556332503273, 'reg_alpha': 1.8228271043666355e-08, 'reg_lambda': 9.665507853342099}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:01:06,574] Trial 12 finished with value: 0.17833252251148224 and parameters: {'n_estimators': 207, 'max_depth': 11, 'learning_rate': 0.12737604190876714, 'min_child_weight': 13, 'subsample': 0.9971317477907701, 'colsample_bytree': 0.7094975278484695, 'gamma': 1.237120888013009, 'reg_alpha': 0.0013416587554225506, 'reg_lambda': 0.010254357357008588}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:02:50,841] Trial 13 finished with value: 0.169677272439003 and parameters: {'n_estimators': 309, 'max_depth': 12, 'learning_rate': 0.09628063571908314, 'min_child_weight': 20, 'subsample': 0.775110409899155, 'colsample_bytree': 0.7987586652315627, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0004699196295925314, 'reg_lambda': 9.66779358979949}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:04:41,466] Trial 14 finished with value: 0.1749475598335266 and parameters: {'n_estimators': 322, 'max_depth': 10, 'learning_rate': 0.0891988796993311, 'min_child_weight': 20, 'subsample': 0.8033823694924689, 'colsample_bytree': 0.7908165351556822, 'gamma': 0.8747179243142184, 'reg_alpha': 0.0019013872412140544, 'reg_lambda': 1.0374653956916587e-05}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:06:55,035] Trial 15 finished with value: 0.1962602734565735 and parameters: {'n_estimators': 283, 'max_depth': 10, 'learning_rate': 0.02807215632195136, 'min_child_weight': 17, 'subsample': 0.7794192227560304, 'colsample_bytree': 0.9074355033641801, 'gamma': 0.4125844921414529, 'reg_alpha': 4.5012664001523424e-05, 'reg_lambda': 0.018867726849009354}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:08:31,413] Trial 16 finished with value: 0.18883125483989716 and parameters: {'n_estimators': 320, 'max_depth': 12, 'learning_rate': 0.08099809739025919, 'min_child_weight': 7, 'subsample': 0.6028057255364521, 'colsample_bytree': 0.8064114554738081, 'gamma': 2.382525301925182, 'reg_alpha': 0.02316062671984357, 'reg_lambda': 1.314053143275926e-08}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:10:48,809] Trial 17 finished with value: 0.20900048315525055 and parameters: {'n_estimators': 388, 'max_depth': 8, 'learning_rate': 0.031195021944056264, 'min_child_weight': 10, 'subsample': 0.7521865606498155, 'colsample_bytree': 0.9975779961884794, 'gamma': 0.7207316966706379, 'reg_alpha': 0.021771694669350503, 'reg_lambda': 8.911946129189984}. Best is trial 0 with value: 0.15107722580432892.
[I 2026-08-22 05:13:09,400] Trial 18 finished with value: 0.1908663809299469 and parameters: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.10796100656646772, 'min_child_weight': 1, 'subsample': 0.8505919001558102, 'colsample_bytree': 0.7613495462127717, 'gamma': 2.819873495107165, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 3.9233028601151885e-05}. Best is trial 0 with value: 0.15107722580432892.

[I 2026-08-22 05:15:21,043] A new study created in memory with name: xgboost_cape

[I 2026-08-22 05:15:21,011] Trial 19 finished with value: 0.18101444840431213 and parameters: {'n_estimators': 454, 'max_depth': 10, 'learning_rate': 0.06831608645397476, 'min_child_weight': 17, 'subsample': 0.864621297363901, 'colsample_bytree': 0.8441480844543353, 'gamma': 1.219241047619864, 'reg_alpha': 0.006093812542810912, 'reg_lambda': 0.016997954984894707}. Best is trial 0 with value: 0.15107722580432892.
Najbolji MAE za tcc: 0.1511
Najbolji parametri: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}

===== OPTUNA XGBOOST: cape =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 05:18:35,673] Trial 0 finished with value: 66.50973510742188 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:20:44,787] Trial 1 finished with value: 103.24365997314453 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:22:35,583] Trial 2 finished with value: 99.73307800292969 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:25:15,664] Trial 3 finished with value: 96.32567596435547 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:26:40,755] Trial 4 finished with value: 108.40082550048828 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:29:10,981] Trial 5 finished with value: 94.40900421142578 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:34:24,333] Trial 6 finished with value: 76.7715072631836 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:36:02,553] Trial 7 finished with value: 101.17533111572266 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:37:33,745] Trial 8 finished with value: 76.31523895263672 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:40:02,180] Trial 9 finished with value: 101.73982238769531 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:43:59,378] Trial 10 finished with value: 81.87928009033203 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:45:45,477] Trial 11 finished with value: 69.35308837890625 and parameters: {'n_estimators': 203, 'max_depth': 12, 'learning_rate': 0.10542678149087867, 'min_child_weight': 14, 'subsample': 0.9893423339815978, 'colsample_bytree': 0.6945056225999373, 'gamma': 1.4745556332503273, 'reg_alpha': 1.8228271043666355e-08, 'reg_lambda': 9.665507853342099}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:47:16,987] Trial 12 finished with value: 70.80692291259766 and parameters: {'n_estimators': 207, 'max_depth': 11, 'learning_rate': 0.12737604190876714, 'min_child_weight': 13, 'subsample': 0.9971317477907701, 'colsample_bytree': 0.7094975278484695, 'gamma': 1.237120888013009, 'reg_alpha': 0.0013416587554225506, 'reg_lambda': 0.010254357357008588}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:49:42,847] Trial 13 finished with value: 67.3808822631836 and parameters: {'n_estimators': 309, 'max_depth': 12, 'learning_rate': 0.09628063571908314, 'min_child_weight': 20, 'subsample': 0.775110409899155, 'colsample_bytree': 0.7987586652315627, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0004699196295925314, 'reg_lambda': 9.66779358979949}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:51:41,307] Trial 14 finished with value: 73.85482025146484 and parameters: {'n_estimators': 322, 'max_depth': 10, 'learning_rate': 0.0891988796993311, 'min_child_weight': 20, 'subsample': 0.8033823694924689, 'colsample_bytree': 0.7908165351556822, 'gamma': 0.8747179243142184, 'reg_alpha': 0.0019013872412140544, 'reg_lambda': 1.0374653956916587e-05}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:53:37,633] Trial 15 finished with value: 84.93366241455078 and parameters: {'n_estimators': 283, 'max_depth': 10, 'learning_rate': 0.02807215632195136, 'min_child_weight': 17, 'subsample': 0.7794192227560304, 'colsample_bytree': 0.9074355033641801, 'gamma': 0.4125844921414529, 'reg_alpha': 4.5012664001523424e-05, 'reg_lambda': 0.018867726849009354}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:56:20,210] Trial 16 finished with value: 67.61030578613281 and parameters: {'n_estimators': 320, 'max_depth': 12, 'learning_rate': 0.08099809739025919, 'min_child_weight': 7, 'subsample': 0.6028057255364521, 'colsample_bytree': 0.8064114554738081, 'gamma': 2.382525301925182, 'reg_alpha': 0.02316062671984357, 'reg_lambda': 1.314053143275926e-08}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 05:58:20,618] Trial 17 finished with value: 90.36459350585938 and parameters: {'n_estimators': 388, 'max_depth': 8, 'learning_rate': 0.031195021944056264, 'min_child_weight': 10, 'subsample': 0.7521865606498155, 'colsample_bytree': 0.9975779961884794, 'gamma': 0.7207316966706379, 'reg_alpha': 0.021771694669350503, 'reg_lambda': 8.911946129189984}. Best is trial 0 with value: 66.50973510742188.
[I 2026-08-22 06:03:29,945] Trial 18 finished with value: 64.22740173339844 and parameters: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.10796100656646772, 'min_child_weight': 1, 'subsample': 0.8505919001558102, 'colsample_bytree': 0.7613495462127717, 'gamma': 2.819873495107165, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 3.9233028601151885e-05}. Best is trial 18 with value: 64.22740173339844.

[I 2026-08-22 06:08:07,953] A new study created in memory with name: xgboost_blh

[I 2026-08-22 06:08:07,928] Trial 19 finished with value: 68.4115982055664 and parameters: {'n_estimators': 796, 'max_depth': 10, 'learning_rate': 0.06193229498222443, 'min_child_weight': 1, 'subsample': 0.879713599128111, 'colsample_bytree': 0.6693761544549911, 'gamma': 3.1631519638115915, 'reg_alpha': 2.726680493037923e-05, 'reg_lambda': 2.347372757484223e-05}. Best is trial 18 with value: 64.22740173339844.
Najbolji MAE za cape: 64.2274
Najbolji parametri: {'n_estimators': 725, 'max_depth': 11, 'learning_rate': 0.10796100656646772, 'min_child_weight': 1, 'subsample': 0.8505919001558102, 'colsample_bytree': 0.7613495462127717, 'gamma': 2.819873495107165, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 3.9233028601151885e-05}

===== OPTUNA XGBOOST: blh =====

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-08-22 06:12:02,734] Trial 0 finished with value: 119.74598693847656 and parameters: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:14:18,147] Trial 1 finished with value: 196.59645080566406 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'min_child_weight': 17, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:16:19,637] Trial 2 finished with value: 187.75982666015625 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.05243180891902853, 'min_child_weight': 3, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:19:33,764] Trial 3 finished with value: 184.1214599609375 and parameters: {'n_estimators': 509, 'max_depth': 8, 'learning_rate': 0.011340440501807348, 'min_child_weight': 13, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:21:03,597] Trial 4 finished with value: 214.43650817871094 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'min_child_weight': 9, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:23:49,274] Trial 5 finished with value: 176.826171875 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.04089285700048085, 'min_child_weight': 11, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:30:05,633] Trial 6 finished with value: 145.48854064941406 and parameters: {'n_estimators': 559, 'max_depth': 12, 'learning_rate': 0.012707942999213693, 'min_child_weight': 4, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:31:52,883] Trial 7 finished with value: 192.88983154296875 and parameters: {'n_estimators': 414, 'max_depth': 5, 'learning_rate': 0.043477055106943, 'min_child_weight': 3, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:33:40,723] Trial 8 finished with value: 143.20082092285156 and parameters: {'n_estimators': 203, 'max_depth': 11, 'learning_rate': 0.06781546492336318, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:36:32,854] Trial 9 finished with value: 196.9180145263672 and parameters: {'n_estimators': 574, 'max_depth': 6, 'learning_rate': 0.011878194167382767, 'min_child_weight': 7, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:41:11,603] Trial 10 finished with value: 153.8365478515625 and parameters: {'n_estimators': 771, 'max_depth': 9, 'learning_rate': 0.023007873057190827, 'min_child_weight': 19, 'subsample': 0.8262452362725613, 'colsample_bytree': 0.8571401836030035, 'gamma': 0.0779739982922818, 'reg_alpha': 0.0004450186189827793, 'reg_lambda': 0.001364365672281635}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:43:14,875] Trial 11 finished with value: 128.4580841064453 and parameters: {'n_estimators': 203, 'max_depth': 12, 'learning_rate': 0.10542678149087867, 'min_child_weight': 14, 'subsample': 0.9893423339815978, 'colsample_bytree': 0.6945056225999373, 'gamma': 1.4745556332503273, 'reg_alpha': 1.8228271043666355e-08, 'reg_lambda': 9.665507853342099}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:45:00,664] Trial 12 finished with value: 131.1460418701172 and parameters: {'n_estimators': 207, 'max_depth': 11, 'learning_rate': 0.12737604190876714, 'min_child_weight': 13, 'subsample': 0.9971317477907701, 'colsample_bytree': 0.7094975278484695, 'gamma': 1.237120888013009, 'reg_alpha': 0.0013416587554225506, 'reg_lambda': 0.010254357357008588}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:47:54,596] Trial 13 finished with value: 121.89484405517578 and parameters: {'n_estimators': 309, 'max_depth': 12, 'learning_rate': 0.09628063571908314, 'min_child_weight': 20, 'subsample': 0.775110409899155, 'colsample_bytree': 0.7987586652315627, 'gamma': 0.8870853894513073, 'reg_alpha': 0.0004699196295925314, 'reg_lambda': 9.66779358979949}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:50:13,109] Trial 14 finished with value: 137.2389373779297 and parameters: {'n_estimators': 322, 'max_depth': 10, 'learning_rate': 0.0891988796993311, 'min_child_weight': 20, 'subsample': 0.8033823694924689, 'colsample_bytree': 0.7908165351556822, 'gamma': 0.8747179243142184, 'reg_alpha': 0.0019013872412140544, 'reg_lambda': 1.0374653956916587e-05}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:52:34,457] Trial 15 finished with value: 161.03355407714844 and parameters: {'n_estimators': 283, 'max_depth': 10, 'learning_rate': 0.02807215632195136, 'min_child_weight': 17, 'subsample': 0.7794192227560304, 'colsample_bytree': 0.9074355033641801, 'gamma': 0.4125844921414529, 'reg_alpha': 4.5012664001523424e-05, 'reg_lambda': 0.018867726849009354}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:55:48,716] Trial 16 finished with value: 121.2440185546875 and parameters: {'n_estimators': 320, 'max_depth': 12, 'learning_rate': 0.08099809739025919, 'min_child_weight': 7, 'subsample': 0.6028057255364521, 'colsample_bytree': 0.8064114554738081, 'gamma': 2.382525301925182, 'reg_alpha': 0.02316062671984357, 'reg_lambda': 1.314053143275926e-08}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 06:58:08,765] Trial 17 finished with value: 170.38714599609375 and parameters: {'n_estimators': 365, 'max_depth': 8, 'learning_rate': 0.03208122418549758, 'min_child_weight': 7, 'subsample': 0.6023225603594583, 'colsample_bytree': 0.9979247097869253, 'gamma': 2.533881284358335, 'reg_alpha': 0.01302385938648125, 'reg_lambda': 2.1241764509077783e-08}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 07:01:52,348] Trial 18 finished with value: 124.82256317138672 and parameters: {'n_estimators': 466, 'max_depth': 11, 'learning_rate': 0.0686801234654511, 'min_child_weight': 10, 'subsample': 0.6303823831112678, 'colsample_bytree': 0.8366070683982902, 'gamma': 3.264423346529435, 'reg_alpha': 0.08842639708590463, 'reg_lambda': 1.807370831354258e-08}. Best is trial 0 with value: 119.74598693847656.
[I 2026-08-22 07:07:03,978] Trial 19 finished with value: 151.98797607421875 and parameters: {'n_estimators': 680, 'max_depth': 10, 'learning_rate': 0.01725130662747314, 'min_child_weight': 1, 'subsample': 0.7211422591005, 'colsample_bytree': 0.920719297129556, 'gamma': 2.9111046405876935, 'reg_alpha': 0.01891109431558191, 'reg_lambda': 7.84423842617657e-05}. Best is trial 0 with value: 119.74598693847656.
Najbolji MAE za blh: 119.7460
Najbolji parametri: {'n_estimators': 425, 'max_depth': 12, 'learning_rate': 0.07259248719561363, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}

=== XGBOOST OPTUNA REZULTATI ===

,model,target,best_MAE_optuna,n_trials,n_estimators,max_depth,learning_rate,min_child_weight,subsample,colsample_bytree,gamma,reg_alpha,reg_lambda
0,XGBoost,t2m_c,0.809330,20,725,11,0.088477,5,0.639080,0.611988,1.328913,5.365164e-05,0.000033
1,XGBoost,wind_speed_ms,0.546984,20,725,11,0.107961,1,0.850592,0.761350,2.819873,1.402155e-04,0.000039
2,XGBoost,swh,0.101628,20,798,10,0.024196,20,0.813253,0.850165,0.055191,1.074018e-03,0.002114
3,XGBoost,mwp,0.231638,20,682,10,0.092385,8,0.798282,0.731282,0.117509,1.593685e-02,0.022098
4,XGBoost,mwd,40.807728,20,658,11,0.035306,3,0.866105,0.858713,3.750695,3.359184e-07,0.000069
5,XGBoost,sst_c,0.147311,20,799,9,0.026230,20,0.814250,0.998611,3.766898,1.628979e-03,9.768192
6,XGBoost,msl_hpa,0.803172,20,425,12,0.072592,12,0.662407,0.662398,0.290418,6.245760e-01,0.002571
7,XGBoost,tcc,0.151077,20,425,12,0.072592,12,0.662407,0.662398,0.290418,6.245760e-01,0.002571
8,XGBoost,cape,64.227402,20,725,11,0.107961,1,0.850592,0.761350,2.819873,1.402155e-04,0.000039
9,XGBoost,blh,119.745987,20,425,12,0.072592,12,0.662407,0.662398,0.290418,6.245760e-01,0.002571

Spremljeno u: xgboost_optuna_svi_targeti.csv

In [ ]:
import gc
import optuna
import xgboost as xgb

from sklearn.metrics import mean_absolute_error

OPTUNA_TRIALS = 15
OPTUNA_MAX_ROWS = None
XGBOOST_THREADS = 4